# BASE PAGE / Schedule an interview right widget
SCHEDULE_AN_INTERVIEW_CLOSE_BUTTON = "//div[@class='el-drawer__container el-drawer__open']//i[@class='el-dialog__close el-icon el-icon-close']"
SCHEDULE_AN_INTERVIEW_ATTENDEES = "//input[@placeholder='Type name or email']"
SCHEDULE_AN_INTERVIEW_ADD_ATTENDEES = "//button[contains(@data-testid, 'scheduling_field_attendees_add')]"
SCHEDULE_AN_INTERVIEW_ATTENDEES_SEARCH_TEXT_BOX = "//input[@placeholder='Search for an attendee']"
SCHEDULE_AN_INTERVIEW_ATTENDEES_NAME = "//div[contains(@data-testid, 'assistant_scheduling_lbl_attendee_name') and contains(text(),'{}')]"
SCHEDULE_AN_INTERVIEW_SCHEDULE_BUTTON = "//button[@data-testid='assistant_scheduling_btn_schedule']"
SCHEDULE_AN_INTERVIEW_ADD_INTERVIEW = "//button[contains(@data-testid, 'scheduling_btn_form_add_itv')]"
SCHEDULE_AN_INTERVIEW_SUB_INTERVIEW_FORM = "//div[contains(@data-testid, 'scheduling_btn_sub_form')]"
SCHEDULE_AN_INTERVIEW_INV_TYPE = "(//button[contains(@data-testid, 'scheduling_scheduling_btn_itv_menu')])[last()]"
SCHEDULE_AN_INTERVIEW_INV_VIRTUAL_TYPE = "//ul[contains(@x-placement, 'bottom-start')]//span[contains(text(), '{}')]"
SCHEDULE_AN_INTERVIEW_SETTING_TAB = "//div[contains(@id, 'tab-schedule_settings')]"
SCHEDULE_AN_INTERVIEW_APPLY_BTN = "//button[contains(@data-testid, 'scheduling_field_attendees_apply')]"
SCHEDULE_AN_INTERVIEW_CONFIRM_CLOSE_BTN = "//button[contains(@data-testid, 'scheduling_btn_close_itv_confirm')]"
SCHEDULE_AN_INTERVIEW_SCHEDULE_POS_BTN = "//button[contains(@data-testid, 'scheduling_btn_schedule')]//span[contains(text(), '{}')]"
SCHEDULE_AN_INTERVIEW_SCHEDULE_CONFIRM_STATUS = "//div[contains(@id,'panel-scheduling-opened')]//div[contains(text(), '{}')]"
SCHEDULE_AN_INTERVIEW_OPTION_TYPE_INTERVIEW = "//div[contains(@data-testid, 'assistant_scheduling_lbl_type') and contains(text(), 'Interview')]"
SCHEDULE_MODULE_ADD_INSTRUCTION = "//button[contains(@data-testid, 'scheduling_btn_add_instruction')]"
SCHEDULE_MODULE_INV_TYPE = "//ul[contains(@class, 'el-dropdown-menu el-popper ') and contains(@x-placement, '-start')]//span[contains(text(), '{}')]"
SCHEDULE_MODULE_CLOSE_MODULE_BUTTON = "//*[contains(@data-testid, 'scheduling_btn_form_close')]//i"
SCHEDULE_MODAL = "//div[contains(@class, 'el-drawer__container el-drawer')]//div[contains(@aria-labelledby,'el-drawer')]"
SCHEDULE_MODULE_NEVER_MIND_BUTTON = "//*[contains(@class,'el-button el-button--default')]/span[contains(text(),'Nevermind')]"
SCHEDULE_MODULE_EXIT_BUTTON = "//*[contains(@class,'el-button el-button--default el-button--danger')]//span[contains(text(),'Exit')]"
SCHEDULE_MODULE_EXIT_SCHEDULING_MODAL = "//*[contains(@aria-label,'Exit Scheduling')]//div[contains(@class,'ol-confirm')]"
SCHEDULE_MODULE_CONFIRM_EXIT_SCHEDULING = "//*[contains(@class,'el-drawer__container el-drawer__open')]//div[contains(@aria-labelledby,'el-drawer__title') and contains(@class,'el-drawer rtl')]"
SCHEDULE_AN_INTERVIEW_ATTENDEES_SELECT = "//input[@placeholder='Add an attendees']"
SCHEDULE_AN_INTERVIEW_WARNING_ICON = "(//i[contains(@class,'icon-warn')])[last()]"
SCHEDULE_AN_INTERVIEW_MISSING_REQUIRED_INFO = "//div[contains(text(),'\"Interview Details\" is missing required information.')]"

# InPerson type
LOCATION_INPUT = "//input[contains(@id, 'interview_location')]"
SEARCH_FOR_A_LOCATION_TEXTBOX = "//input[contains(@placeholder,'Search for a location')]"
LOCATION_OPTIONS = "//div[contains(@class,'el-tree-node is-expanded is-focusable')]//em[contains(text(),'{}')]"
SCHEDULE_LOCATION_OPTIONS = "(//div[contains(@class,'el-collapse-item__wrap')]//i[contains(@class, 'icon-location')]//following-sibling::div//em[contains(text(), '{}')])[last()]"
SCHEDULE_LOCATION_PRIVATE_OPTIONS = "//div[contains(@class, 'is-expanded is-focusable')]//em[contains(text(), '{}')]"
LOCATION_LABEL_NAME = "//i[contains(@class, 'icon icon-location')]/following-sibling::span[contains(@class, 'has-check-icon')]"
LOCATION_ICON_IN_PROGRESS_SEARCHING = "//div//i[contains(@class, 'icon icon-location _')]"
ROOM_BUTTON = "//button[contains(@data-testid, 'scheduling_room_select')]"
DURATION_INPUT = "//div[contains(@id, 'panel-scheduling-opened')]//div[contains(@class, 'scheduling-timeline-item__duration')]//input[contains(@placeholder, 'Select')]"
DURATION_OPTION = "//span[contains(@class, 'el-radio__label') and contains(text(), '{}')]"
DURATION_TIME_OPTION = "//span[contains(@class, 'el-radio__label')]/span[text()='{}']"
DURATION_CUSTOM = "//span[contains(@class, 'el-radio__label') and contains(text(), 'Custom')]"
DURATION_CUSTOM_INPUT_HOUR = "(//div[contains(@class, 'el-input-number is-controls-right')]//input)[1]"
DURATION_CUSTOM_INPUT_MIN = "(//div[contains(@class, 'el-input-number is-controls-right')]//input)[2]"
DURATION_CUSTOM_APPLY_BTN = "//div[contains(@role, 'tooltip') and contains(@x-placement, '-end')]//button[contains(@class, 'el-button el-button--primary el-button--small')]//span[contains(text(), 'Apply')]"

# Scheduling Candidate summary
CANDIDATE_INFO_SUMMARY = "//div[contains(@class, 'text-overflow') and contains(text(), '{}')]"
CANDIDATE_INFO_CANDIDATE_NAME = "//div[contains(@class, 'text-overflow')]//div[contains(text(), '{}')]"
CANDIDATE_INFO_CANDIDATE_HOVER_SHOW_FULL = "//div[contains(@class, 'el-tooltip__popper is-light') and not(contains(@style, 'display'))]//div"
CANDIDATE_DETAIL_INFO_STATUS_CAPTURE = "//div[contains(@class, 'text-overflow') and contains(text(), 'Capture Complete')]"

# Setting/Other
OLIVIA_ASSIST_TEXT = "//div[contains(@data-testid, 'assist_suggestion_action_0')]"
SCHEDULING_TIMELINES_TOGGLE = "//div[@data-testid='scheduling_btn_timeline']//span"
LIMIT_RESCHEDULING_INTERVIEWS_TOGGLE = "//div[@data-testid='scheduling_btn_limit_itv']//span"
HAVE_ATTENDEE_SCHEDULE_INTERVIEW_TOGGLE = "//input[contains(@id,'have_attendee_schedule')]//following-sibling::span"
PRIVATE_CALENDAR_EVENT_TOGGLE = "//div[contains(@data-testid,'scheduling_btn_private_calendar_event_on')]//span"
BASIC_USER_SPAN = "//span[contains(@class,'el-avatar el-avatar')]//following-sibling::span[contains(text(),'{}')]"
SELECT_INTERVIEWER_INPUT = "//div[contains(@class,'el-row')]//input[contains(@placeholder,'Select Interviewer')]"
VIRTUAL_INTERVIEW_URL_TOGGLE = "//div[contains(@data-testid,'scheduling_btn_generate_virtual_url')]//following-sibling::span"
CANDIDATE_TIMEZONE = "//div[contains(@data-testid,'scheduling_btn_candidate_timezone_on')]//following-sibling::span"
MINIMUM_DROPDOWN = "//div[@data-testid='scheduling_advanced_settings_select_timeline_min']//input"
MINIMUM_MAXIMUM_TIME_OPTION = "//div[contains(@x-placement,'top') or contains(@x-placement,'bottom')]//li[contains(@class,'el-select-dropdown')]//span[text()='{}']"
MAXIMUM_DROPDOWN = "//div[@data-testid='scheduling_advanced_settings_select_timeline_max']//input"
LIMIT_NUMBER_OF_TIME_CANDIDATE_CAN_RESCHEDULE_DROPDOWN = "//div[@data-testid='scheduling_advanced_settings_select_times_limit']//input"
CANDIDATE_CAN_RESCHEDULE_INTERVIEW_DROPDOWN = "//div[@data-testid='scheduling_advanced_settings_select_limit']//input"
DETERMINE_SCHEDULING_APPROACH_BUTTON = "//button[contains(@data-testid,'scheduling_btn_scheduling_approach')]"
DETERMINE_SCHEDULING_APPROACH_BUTTON_OPTION = "//ul[contains(@x-placement,'bottom-start') or contains(@x-placement,'top-start')]//span[contains(text(),'{}')]"
DETERMINE_SCHEDULING_APPROACH_COUNT = "//ul[contains(@x-placement,'bottom-start') or contains(@x-placement,'top-start')]/li[contains(@class,'el-dropdown-menu__item')]"
TRAVEL_REQUIRED_TOGGLE = "//div[contains(@data-testid,'scheduling_btn_itv_travel_required')]//span"
UPDATE_TIME_ZONE_DROPDOWN_ICON = "//*[contains(text(),'Update Timezone')]//parent::div//parent::div//i[contains(@class,'el-icon-arrow-up')]"
UPDATE_TIMEZONE_DROPDOWN = "(//*[contains(@placeholder, 'Select')])[last()]"
UPDATE_TIMEZONE_INPUT = "//input[contains(@placeholder,'Search for Timezone')]"
UPDATE_TIMEZONE_OPTIONS = "//div[contains(@x-placement,'top') or contains(@x-placement, 'bottom')]//li[contains(@class,'el-select-dropdown')]//span[contains(text(),'{}')]"
CTA_WARNING_LOCATOR = "//button[contains(@data-testid,'scheduling_btn_schedule')]//following-sibling::i"
CTA_WARNING_LOCATOR_MESSAGE = "//div[contains(@class,'el-tooltip__popper is-light') and contains(text(),'Your settings have changed')]"
WARNING_BUTTON = "//div[@id='panel-scheduling-opened']//span[contains(@class,'el-popover')]//button[contains(@class,'el-button el-button--default')]//i[contains(@class,'icon icon-warn')]"
SCHEDULING_TIMELINES_TOGGLE_INPUT = "//div[@data-testid='scheduling_btn_timeline']/input[contains(@id,'sched_timeline_on')]"
LIMIT_RESCHEDULING_INTERVIEWS_TOGGLE_INPUT = "//div[@data-testid='scheduling_btn_limit_itv']/input[contains(@id,'limit_itv_on')]"
HAVE_ATTENDEE_SCHEDULE_INTERVIEW_TOGGLE_INPUT = "//input[contains(@id,'have_attendee_schedule')]"

# Interviewer
ROUND_ROBIN_INTERVIEWER = "//div[contains(text(), 'Round Robin Groups')]/parent::div/following-sibling::div//li[contains(@data-testid, 'assistant_scheduling_attendee_item')]"
EMAIL_INTERVIEWER_LOCATOR = "//div[contains(@class,'el-scrollbar__wrap')]//div[contains(@class,'text-truncate')]"
SCROLL_INTERVIEWER_LOCATOR = "(//div[contains(@class,'el-scrollbar')]//div[contains(@class,'el-scrollbar')]//div[contains(@class,'el-scrollbar')]//div[contains(@class,'el-scrollbar__bar is-vertical')]//div[contains(@class,'el-scrollbar__thumb')])[last()]"
ICON_REMOVE_INTERVIEWER_LOCATOR = "(//div[contains(@class,'el-scrollbar')]//i[contains(@class,'icon icon-remove')])[{}]"
NAME_INTERVIEWER_INPUT = "(//input[contains(@data-testid,'scheduling_sequential_itv_name') and contains(@placeholder,'Add Interview Name')])[{}]"
SELECT_SUB_INTERVIEWER_CHECKBOX = "(//div[contains(@data-testid,'scheduling_btn_sub_form')]//span[contains(@class,'el-checkbox__input')]/span)[{}]"

# BASE PAGE / Schedule an interview right widget
EDIT_CANDIDATE_BUTTON = "//li[contains(@data-testid, 'candidatemenu_btn_editinfo')]"
EDIT_CANDIDATE_SAVE_BUTTON = "//button//span//span[contains(text(), 'Save')]"
STATUS_PROFILE_CANDIDATE = "//span[contains(@class, 'hidden-xs-only') and contains(text(), '{}')]"
STATUS_PROFILE_CANDIDATE_DROPDOWN = "//div[contains(@class,'el-collapse-item__header')]//div[text()='{}']"
STATUS_OPTION_ITEM = "//li[contains(@class,'el-dropdown-menu__item') and contains(text(),'{}')]"
UPDATE_STATUS_CONFIRM_BUTTON = "//div[@aria-label='Confirm Status Update']//button//span[contains(text(),'Confirm')]"
CANDIDATE_NAME = "//strong[contains(@data-testid, 'candidateprofile_lbl_name')]"
CANDIDATE_NAME_SCHEDULING_LOCATOR = "(//div[contains(@class, 'text-overflow')]//div[contains(text(), '')])[1]"
ADD_INTERVIEW_BUTTON ="//button[@data-testid='scheduling_btn_form_add_itv']//span[contains(text(), 'Add Interview')]"
INTERVIEWER_BUTTON = "//*[@id='sequential_interviewers']//span[contains(text(),'Add Interviewers')]"
ADD_INTERVIEWER_BUTTON_INDEX = "(//*[@id='sequential_interviewers']//span[contains(text(),'Add Interviewers')])[1]"
ADD_INTERVIEWERS_BUTTON = "(//*[@id='sequential_interviewers']//span[contains(text(),'Add Interviewers')])[last()]"
INTERVIEWER_LOCATOR = "(//li[@data-testid='assistant_scheduling_attendee_item']//div[contains(text(),'{}')])[last()]"
APPLY_INTERVIEWER_BUTTON = "(//button[@data-testid='scheduling_field_attendees_apply'])[last()]"
CANCEL_INTERVIEWER_BUTTON = "(//button[@data-testid='scheduling_field_attendees_cancel'])[last()]"
INTERVIEWER_ADDED_PATTERN = "//div[contains(@class,'el-scrollbar__view')]//div[contains(text(),'{}')]"
APPLY_TIME_BUTTON = "(//button[@class='el-button el-button--primary el-button--small'])[last()]"
FIND_TIMES_BUTTON = "(//div[@class='ol-apd__footer']//button[@data-testid='scheduling_btn_schedule'])[last()]"
DETERMINE_SCHEDULING_APPROACH_LABEL = "//label[contains(text(),'Determine Scheduling Approach')]"
INTERVIEW_TYPE_DROPDOWN = "//ul[contains(@x-placement,'bottom-start')]//span[contains(text(),'Phone Interview')]"
INTERVIEW_DROPDOWN = "(//button[@data-testid='scheduling_scheduling_btn_itv_menu'])[last()]"
DURATION_DROPDOWN = "//div[contains(@class, 'scheduling-timeline-item')]//div[contains(@class, 'el-input el-input--suffix is-selected')]"
DURATION_LAST_DROPDOWN = "(//div[contains(@class, 'scheduling-timeline-item')]//div[contains(@class, 'el-input el-input--suffix is-selected')])[last()]"
DURATION_TIME_PATTERN_SLECTION = "//span[contains(@class,'el-radio__label')]//span[contains(text(),'{}')]"
DURATION_APPLY_CANCEL_BUTTON = "//div[contains(@role,'tooltip') and contains(@aria-hidden,'false')]//button//span[contains(text(),'{}')]"
TYPE_INTERVIEW_TEXT = "//div[contains(@class,'el-scrollbar__view')]//div[contains(text(),'Interview Summary')]"
SCHEDULE_AN_INTERVIEW_TEXT = "//div[contains(text(),'Schedule an Interview')]"
OLIVIA_ASSIST_IMAGE_LOCATOR = "//div[@data-testid='assist_header_title']//img"
CANDIDATE_DETAIL_LOCATOR = "//div[@class='el-scrollbar']//div[@class='el-tooltip']"
CANDIDATE_SECTION_LOCATOR = "//div[contains(@class,'color-lighter text-overflow')]//div[contains(@class,'el-tooltip')]"
SEQUENTIAL_INTERVIEW_TYPE_DROPDOWN = "//button[@data-testid='scheduling_btn_itv_sequent_menu']"
SEARCH_INTERVIEWER_INPUT = "(//div[@data-testid='assistant_scheduling_input_search']/input)[last()]"
CHOOSE_TIME_BUTTON = "//button[@data-testid='scheduling_btn_pick_time']"
SCHEDULE_INTERVIEW_PATTERN_SCHEDULE_BUTTON = "//button[contains(@data-testid,'scheduling_btn_schedule')]//*[contains(text(),'{}')]"
CLOSE_SCHEDULE_BUTTON = "//button[@data-testid='scheduling_btn_close_itv_confirm']"
DURATION_DROPDOWN_INDEX = "(//div[contains(@class,'scheduling-timeline-item__content scheduling-timeline-item__duration')]//input[contains(@class,'el-input__inner')])[1]"
SCHEDULE_CANCEL_BUTTON = "//button[@data-testid='scheduling_btn_nervermind']"
SCHEDULE_INTERVIEW_SCHEDULE_BUTTON = "//button[@data-testid='scheduling_btn_schedule']"

#INTERVIEW DETAILS
INTERVIEW_SUMMARY_OPTION = "//section[contains(@class,'el-drawer__body')]//div[@class='el-scrollbar']//div[contains(@class,'el-scrollbar__view')]//span[contains(text(),'{}')]"
TIME_INTERVIEW_SPAN = "(//div[contains(@class,'scheduling-timeline-item')]//span[contains(@class, 'el-tooltip')])[last()]"
TIME_INTERVIEW_SPAN_CHECKBOX_VALUE = "(//label[contains(@class,'el-radio is-checked')]//span[@class='el-radio__label']/span)[last()]"
INTERVIEW_SUMMARY_TIME_LOCATOR = "//div[@class='el-scrollbar']//div[@class='color-lighter']"
INTERVIEW_SUMMARY_TITLE = "//div[@class='el-scrollbar']//div[contains(text(),'{}')]"
INTERVIEW_DETAILS_ELLIPSES_SUB_LOCATOR = "(//div[contains(@class,'scheduling-block')]//button[@data-testid='scheduling_sequential_btn_menu'])[{}]"
INTERVIEW_DETAILS_ELLIPSES_LOCATOR = "(//div[contains(@class,'scheduling-block')]//button[@data-testid='scheduling_sequential_btn_menu'])[last()]"
INTERVIEW_DETAILS_DELETE_INTERVIEW_BUTTON = "(//ul[contains(@class,'el-dropdown-menu el-popper')]//span[contains(text(),'Delete Interview')])[last()]"
INTERVIEW_DETAILS_MOVE_INTERVIEW_BUTTON = "//ul[contains(@x-placement,'bottom-end')]//span[contains(text(),'{}')]"
INTERVIEW_DETAILS_NAME_INTERVIEW_INPUT = "(//input[contains(@placeholder,'Add Interview Name')])[{}]"
INTERVIEW_DETAILS_EXPAND_ICON = "(//i[contains(@data-testid, 'scheduling_sequential_btn_collapse')])[{}]"

#SCHEDULE MODULE / Prep & Instructions
ADD_INTERVIEW_PREP_BUTTON = "//button[contains(@data-testid,'scheduling_btn_prep')]"
CANDIDATE_PREP_DROPDOWN = "//div[@id='prep_candidate']//button[contains(@data-testid,'scheduling_btn_itv_sequent_menu')]"
INTERVIEWER_PREP_DROPDOWN = "//div[@id='prep_interviewer']//button[contains(@data-testid,'scheduling_btn_itv_sequent_menu')]"
CANDIDATE_INTERVIEWER_PREP_DROPDOWN_OPTIONS = "//ul[contains(@x-placement,'top-start') or contains(@x-placement,'bottom-start')]//li[contains(@class,'el-dropdown-menu__item')]//span[contains(text(),'{}')]"
PREP_ESCAPE_BUTTON = "(//button[@data-testid='scheduling_prep_select_btn_menu'])[{}]"
EDIT_INTERVIEW_PREP_BUTTON = "//ul[contains(@x-placement,'bottom-end') or contains(@x-placement,'top-end')]//span[text()='Edit Interview Prep']"
INTERVIEW_INSTRUCTIONS_TEXTAREA = "//textarea[@data-testid='scheduling_input_instruction']"
PREP_AND_INSTRUCTIONS_TEXT = "//div[contains(@id,'tab-schedule_prep')]"

#INTERVIEWER RR
EXPAND_ICON_RR = "//div[text()='{}']/parent::div//following::div//i[contains(@class,'icon icon-chevron-down')]"
SCROLL_INTERVIEWER_RR_LOCATOR = "(//div[@data-testid='scheduling_btn_sub_form']//div[contains(@class,'el-scrollbar__bar is-vertical')])[last()]"
ROUND_ROBIN_INTERVIEWER_NAME_OPTION = "//div[contains(@class, 'scheduling-timeline-interviewer')]//div[normalize-space()='{}']"

#SCHEDULE MODULE / CHOOSE TIME
CHOOSE_TIME_NEXT_DATE_LOCATOR = "//i[@data-testid='scheuduling_pick_time_btn_next_date']"
CHOOSE_TIME_PREVIOUS_DATE_LOCATOR = "//i[@data-testid='scheuduling_pick_time_btn_previous_date']"
CHOOSE_TIME_VIEW_MORE_TIME_TOP_BUTTON = "//button[@data-testid='scheduling_view_more_time_btn_top']"
CHOOSE_TIME_VIEW_MORE_TIME_BOTTOM_BUTTON = "//button[@data-testid='scheduling_view_more_time_btn_bottom']"
CHOOSE_TIME_TIME_OPTIONS = "//div[contains(@class,'el-scrollbar__wrap')]//div[@data-testid='scheduling_slot_btn']/div[@class='el-tooltip']/span[contains(text(),'{}')]"
CHOOSE_TIME_SCHEDULE_TIME_BUTTON = "//button[@data-testid='scheduling_pick_time_btn_schedule']"
CHOOSE_TIME_TIME_SLOT_LOCATOR = "//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'undefined')]"
CHOOSE_TIME_TIME_SLOT_INDEX = "(//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'undefined')])[{}]"
CHOOSE_TIME_TIME_SLOT_FIRST = "(//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'undefined')])[1]"
CHOOSE_TIME_SLOT_UNAVAILABLE_LOCATOR = "//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'slot-unavailable')]"
CHOOSE_TIME_SLOT_UNAVAILABLE_OPTIONS = "//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'slot-unavailable')]//i[contains(@class,'icon-cal-neutral')]//following-sibling::span[contains(text(),'{}')]"
CHOOSE_TIME_TIME_SLOT_OPTIONS = "(//div[contains(@data-testid,'scheduling_slot_btn') and contains(@class,'undefined')])[{}]"
CHOOSE_TIME_SCHEDULE_OVER_UNAVAILABLE_TIMES_TOGGLE = "//div[contains(@data-testid,'scheduling_btn_override')]//span"
CHOOSE_TIME_SCHEDULE_OVER_UNAVAILABLE_TIMES_INPUT = "//div[contains(@data-testid,'scheduling_btn_override')]//input"
CHOOSE_TIME_LIST_TIMEZONE_DROPDOWN_ICON = "//i[contains(@class,'el-icon-caret-top')]"
CHOOSE_TIME_LIST_TIMEZONE_INPUT = "//input[contains(@placeholder,'Search for Timezone')]"
CHOOSE_TIME_LIST_TIMEZONE_OPTIONS = "//li[contains(@class,'el-select-dropdown')]//span[contains(text(),'{}')]"
CHOOSE_TIME_LIST_TIMEZONE_DEFAULT_VALUE = "//li[contains(@class,'selected hover')]//span[contains(text(),'{}')]"
CHOOSE_TIME_ANY_ORDER_BUTTON = "//button[contains(@data-testid,'scheduling_pick_time_btn_any_order')]"
CHOOSE_TIME_ANY_ORDER_SPAN = "//button[contains(@data-testid,'scheduling_pick_time_btn_any_order')]//span[contains(text(),'Any Order')]"
CHOOSE_TIME_ANY_ORDER_ICON_CHECKED = "//span[contains(text(),'Any Order')]//following-sibling::i[contains(@class,'icon-check2')]"
CHOOSE_TIME_IN_ORDER_BUTTON = "//button[contains(@data-testid,'scheduling_pick_time_btn_in_order')]"
CHOOSE_TIME_IN_ORDER_SPAN = "//button[contains(@data-testid,'scheduling_pick_time_btn_in_order')]//span[contains(text(),'In-Order')]"
CHOOSE_TIME_IN_ORDER_ICON_CHECKED = "(//*[contains(text(),'{}')]//following-sibling::i[contains(@class,'icon-check2')])[last()]"
CHOOSE_TIME_BACK_BUTTON = "//button[contains(@data-testid,'scheduling_pick_time_btn_cancel')]//span[contains(text(),'Back')]"
CHOOSE_TIME_TIME_ZONE_DEFAULT = "//li[contains(@class,'el-select-dropdown__item selected')]//span[contains(text(),'{}')]//following-sibling::i[contains(@class,'icon-check2')]"
CHOOSE_TIME_CALENDAR_SHOW_DATE = "//div[contains(@data-testid,'scheduling_pick_time_show_calendar')]//span"
CHOOSE_TIME_CALENDAR_ICON = "//div[contains(@data-testid,'scheduling_pick_time_show_calendar')]//i[contains(@class,'icon-cal-blank')]"
CHOOSE_TIME_CALENDAR_MODAL = "//div[contains(@class,'default-flatpickr')]"
CHOOSE_TIME_CALENDAR_DATE_OPTIONS = "(//span[contains(@class,'flatpickr-day') and not(contains(@class,'disable'))])[{}]"
CHOOSE_TIME_CALENDAR_DATE_SELECTED = "//div[contains(@class, 'dayContainer')]//span[contains(@class,'selected')]"

#SCHEDULE MODULE/ SELECT SCHEDULE TYPE
INTERVIEW_SCHEDULE_TYPE = "//div[contains(@data-testid,'scheduling_btn_select_type')]//div[@data-testid='scheduling_lbl_type' and normalize-space()='Interview']"
ORIENTATION_SCHEDULE_TYPE = "//div[@data-testid='scheduling_lbl_type' and contains(text(), 'Orientation Event')]"
OLIVIA_RECORDED_INTERVIEW_BUTTON = "//div[contains(@data-testid,'scheduling_lbl_type') and contains(text(),'Olivia Recorded Interview') or contains(text(), 'Luci Recorded Interview')]"
INTERVIEW_SCHEDULE_TYPE_OPTION = "//div[contains(@data-testid,'scheduling_btn_select_type')]//div[@data-testid='scheduling_lbl_type' and normalize-space()='{}']"

#CANCEL INTERVIEW MODAL
CANCEL_INTERVIEW_MODAL = "//div[contains(@aria-label,'Cancel Interview')]"
CANCEL_INTERVIEW_NEVER_MIND_BUTTON = "//button[contains(@data-testid,'scheduling_cancel_btn_nervermind')]//span[contains(text(),'Nevermind')]"
CANCEL_INTERVIEW_CONFIRM_BUTTON = "//button[contains(@data-testid,'scheduling_cancel_btn_confirm')]//span[contains(text(),'Confirm')]"
CANCEL_MULTIPLE_INTERVIEW_BUTTON = "//button[contains(@data-testid,'scheduling_btn_cancel_itv')]"
CANCEL_INTERVIEW_MODAL_TEXTAREA = "//textarea[@id='cancelMessage']"

# BASE PAGE / Add, Edit schedule
MORE_BUTTON = "//button[contains(@data-testid, 'btn_candidate_more')]"
CANDIDATE_MENU_SCHEDULE_BUTTON = "//button[contains(@data-testid, 'candidatemenu_btn_schedule')]//span[contains(text(),'Schedule')]"
SCHEDULING_SCHEDULE_BUTTON = "//button[contains(@data-testid, 'scheduling_btn_schedule')]//span[contains(text(),'Schedule')]"
INTERVIEW_BUTTON = "//div[contains(@data-testid, 'scheduling_lbl_type') and contains(text(), 'Interview')]"
SCHEDULE_INTERVIEW_TYPE_DROPDOWN = "//button[contains(@data-testid, 'scheduling_btn_itv_menu')]"
SCHEDULE_EVENT_BUTTON = "//div[contains(@data-testid, 'scheduling_lbl_type') and contains(text(), 'Event')]"
IN_PERSON_TYPE = "//li//span[contains(text(), 'In-Person Interview')]"
INTERVIEW_TYPE_PATTERN = "//li//span[contains(text(), '{}')]"
ADD_INTERVIEWER_BUTTON = "//button[contains(@id, 'sequential_interviewers')]"
INPUT_SEARCH_ATTENDEES = "//*[contains(@data-testid, 'assistant_scheduling_input_search')]//input"
ATTENDEES_NAME = "//div[contains(@data-testid, 'assistant_scheduling_lbl_attendee_name')]"
SAVE_INTERVIEWER_BUTTON = "//button[contains(@data-testid, 'scheduling_field_attendees_apply')]"
INPUT_INTERVIEW_LOCATION = "//input[contains(@id, 'interview_location')]"
NAME_LOCATION = "//i[contains(@class, 'icon-location')]//following-sibling::span//span[contains(text(), '{}')]"
CANDIDATE_NAME_LOCATOR = "//span[contains(text(), '{}')]"
SAVE_BUTTON = "//button//span//span[contains(text(), 'Save')]"
CANCEL_REQUEST = "//button[contains(@data-testid, 'scheduling_summary_btn_cancel')]//span[contains(text(), 'Cancel Request')]"
CONFIRM_CANCEL_REQUEST = "//button[contains(@data-testid, 'scheduling_cancel_btn_confirm')]//span[contains(text(), 'Confirm')]"
RESCHEDULE_BUTTON_IN_MODAL = "//button[contains(@data-testid,'scheduling_btn_schedule')]"

#UPDATE, EDIT, CANCEL SCHEDULE INTERVIEW
UPDATE_INTERVIEW_CANDIDATE_NAME = "//div[contains(text(), 'Candidate')]//following-sibling::div//div[contains(text(), '{}')]"
UPDATE_INTERVIEW_EVENT_NAME = "//div[contains(text(), 'Interview Summary')]//following-sibling::div//span[contains(text(), '{}')]"
ALL_CANDIDATES_SCHEDULE_UPDATE_BUTTON = "//span[@class='el-link--inner']/span[text()='Update']"
ALL_CANDIDATES_SCHEDULE_CANCEL_INTERVIEW_BUTTON = "//button[@data-testid='scheduling_summary_btn_cancel']//span[contains(text(),'Cancel Interview')]"
ALL_CANDIDATES_SCHEDULE_EDIT_INTERVIEW_BUTTON = "//button[@data-testid='scheduling_summary_btn_edit']//span[contains(text(),'Edit Interview')]"
ALL_CANDIDATES_SCHEDULE_RESCHEDULE_INTERVIEW_BUTTON = "//button[@data-testid='scheduling_summary_btn_reschedule']//span[contains(text(),'Reschedule')]"
ALL_CANDIDATES_SCHEDULE_CONFIRM_BUTTON = "//button[@data-testid='scheduling_cancel_btn_confirm']//span[contains(text(),'Confirm')]"
ALL_CANDIDATES_SCHEDULE_CLOSE_BUTTON = "//button[@data-testid='scheduling_detail_btn_close']//span[contains(text(),'Close')]"
ALL_CANDIDATES_SCHEDULE_EVENT_CLOSE_BUTTON = "//button[@data-testid='scheduling_event_btn_close']//span[contains(text(),'Close')]"
ALL_CANDIDATES_SCHEDULE_INTERVIEW_TYPE = "//i[contains(@class, 'icon-phone')]//following-sibling::span[normalize-space()='{}']"
ALL_CANDIDATES_SCHEDULE_INTERVIEWER_NAME = "//i[contains(@class, 'icon-interview-group')]//following-sibling::span[normalize-space()='{}']"

#BASE PAGE / SCHEDULE TYPE / SCHEDULE TO OLIVIA RECORDED INTERVIEW
SCHEDULE_TO_OLIVIA_RECORDED_INTERVIEW_DROPDOWN = "//input[contains(@id,'recordedId')]"
SCHEDULE_TO_OLIVIA_RECORDED_INTERVIEW_DROPDOWN_OPTION = "//div[contains(@class, 'el-select-dropdown__wrap el-scrollbar')]//div[contains(text(),'{}')]"
SCHEDULE_TO_OLIVIA_RECORDED_INTERVIEW_SEND_BUTTON = "//button[contains(@data-testid, 'scheduling_record_btn_send')]"
SCHEDULE_TO_OLIVIA_RECORDED_SEARCH_INTERVIEW_INPUT = "//*[contains(@class, 'el-select-input-search')]//input"

# SEND FORM
CEM_CANDIDATE_JOURNEY_SEND_FORM_BUTTON = "//button//span[contains(text(), 'Send Form')]"

# CALENDAR SCHEDULE
COLLAPSE_SCHEDULE_BUTTON = "//button[contains(@class, 'btn-collapse')]//i[contains(@class, 'icon-remove')]"

# SCHEDULE ORIENTATION
SCHEDULE_ORIENTATION_EVENT_SEARCH_INPUT = "//div[contains(@data-testid, 'input_search')]//input"
SCHEDULE_ORIENTATION_SUBMIT_BUTTON = "//button[contains(@data-testid, 'scheduling_orientation_btn_submit')]"
SCHEDULE_ORIENTATION_INTERVIEW_SUBMIT_BUTTON = "(//button[contains(@data-testid, 'scheduling_orientation_btn_submit')])[last()]"
SCHEDULE_ORIENTATION_CLOSE_BUTTON = "//button[contains(@data-testid, 'scheduling_event_btn_close')]"

# OFFER
CLOSE_REVIEW_OFFER_X_BUTTON = "//*[contains(@class, 'el-drawer')]//*[contains(@class, 'icon-remove')]"
CONFIRM_UN_SAVE_OFFER_BUTTON = "//button//span[contains(text(), 'Discard')]"

# REFERRED BY
TIME_FILTER_COMBOBOX = "//div[@data-testid='time_filter_selected_lbl']"
EMPLOYEE_REFERRED_TABLE = "//div[contains(@class,'body-wrapper')]"
EMPLOYEE_REFERRED_ALL_NAME = "//strong[contains(@class,'text-overflow')]"
