# BASE PAGE
APPROVAL_BUILDER_CONFIRM_OVERLAY = "//div[contains(@class,'confirm-modal in')]"
APPROVAL_BUILDER_BUTTON_CONFIRM_DELETE = "//div[@class='modal-dialog']//button[normalize-space()='Delete']"
APPROVAL_BUILDER_BUTTON_CONFIRM_EDIT = "//div[@class='modal-dialog']//button[normalize-space()='Confirm']"
APPROVAL_BUILDER_BUTTON_CANCEL_DELETE = "//div[contains(@class,'confirm-modal')]//div[@class='modal-dialog']//button[normalize-space()='Cancel']"
APPROVAL_BUILDER_ADD_APPROVAL_FLOW_BUTTON = "//div[contains(@id, 'toolbar')]//button[contains(text(), 'Add Approval Flow')]"
APPROVAL_BUILDER_DELETE_DIALOG = "//div[contains(normalize-space(),'Delete Approval Flow')]//div[@class='modal-dialog']"
APPROVAL_BUILDER_INPUT_SEARCH_APPROVAL_FLOW = "//input[contains(@placeholder, 'Search approval flow')]"
APPROVAL_BUILDER_CANCEL_ADD_BUTTON = "//*[@class='ai-sidebar-footer']//*[contains(text(),'Cancel')]"

# APPROVAL FLOW MODAL
APPROVAL_BUILDER_MODAL = "//*[@id='approval-builder-modal']"
APPROVAL_BUILDER_ADD_APPROVER_ITEM = "//*[@class='approver-item']"
APPROVAL_BUILDER_ADD_APPROVER_BUTTON = "//button[contains(text(), 'Add Approver')]"
APPROVAL_BUILDER_INPUT_SEARCH_USER_APPROVER = "//div[@class='add-approver']//input[contains(@placeholder, 'Search for users')]"
APPROVAL_BUILDER_INPUT_APPROVAL_FLOW_NAME = "//input[contains(@placeholder, 'Enter approval flow name')]"
APPROVAL_BUILDER_MODAL_CANCEL_BUTTON = "//*[@class='ai-sidebar-footer']//*[contains(text(),'Cancel')]"
APPROVAL_BUILDER_MODAL_SAVE_BUTTON = "//*[@class='ai-sidebar-footer']//*[contains(text(),'Save')]"
APPROVAL_BUILDER_CREATE_APPROVAL_FLOW_BUTTON = "//button[contains(text(), 'Create')]"
APPROVAL_BUILDER_USER_NAME = "//div[contains(@class, 'user-name')]//*[contains(text(), '{}')]"
APPROVAL_BUILDER_MODAL_OVERLAY = "//div[contains(@class,'ai-sidebar-overlay--in')]"
APPROVAL_BUILDER_APPROVER_ITEM = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item-body']"
APPROVAL_BUILDER_APPROVER_ORDER = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item-body']//div[@class='approver-order']"
APPROVAL_BUILDER_APPROVER_REORDER = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item']//div[@class='approver-reorder']//i[contains(@class,'icon-reorder')]"
APPROVAL_BUILDER_APPROVER_ITEM_INPUT_SEARCH = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item']//input[contains(@placeholder, 'Search for users')]"
APPROVAL_BUILDER_APPROVER_ROLE = "//div[@id='v-group-accordion-new-approver-selector']//a[contains(text(),'{}')]"
APPROVAL_BUILDER_SEARCHED_USER_NAME = "//div[@id='approval-builder-modal-content']//span[contains(text(),'{}')]"
APPROVAL_BUILDER_CHANGE_USER = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item-body']//i[contains(@class,'icon-reorder2')]"
APPROVAL_BUILDER_DELETE_USER = "//*[@class='approver-list']//*[contains(text(),'{}')]//ancestor::div[@class='approver-item-body']//i[contains(@class,'icon-delete2')]"
APPROVAL_BUILDER_LAST_USER = "//div[@id='approval-builder-modal-content'][last()]//span[contains(text(),'{}')]//following-sibling::span[contains(text(),'{}')]"
APPROVAL_BUILDER_SAVE_BUTTON = "//*[@id='approval-builder-modal']//button[contains(text(),'Save')]"
APPROVAL_BUILDER_CONFIRM_ADD_APRROVER_BUTTON = "//button[contains(@class,'btn btn-primary btn-sm ok-btn') and contains(text(),'Confirm')]"
APPROVAL_BUILDER_CONFIRM_ADD_APPROVER_TEXT = "//*[contains(@class,'modal-body')]//*[contains(text(),'{}')]//following-sibling::strong[contains(text(),'{}')]"
APPROVAL_BUILDER_CONFIRM_ADD_APPROVER_POPUP = "//*[contains(@class,'modal-content printable')]"
APPROVAL_BUILDER_HEADER_TEXT = "//*[contains(@class,'header-1-text cursor-pt text-overflow') and contains(text(),'{}')]"
APPROVAL_BUILDER_APPROVER_LIST = "//*[contains(@class,'approver-name text-overflow')]"

# TABLE
APPROVAL_BUILDER_SCHOOL_EMPTY_ASSIGNED_OF_ROW = "//*[normalize-space()='{}']//ancestor::div[@class='row']//p[contains(text(), '—')]"
APPROVAL_BUILDER_SCHOOL_ASSIGNED_AVAILABLE_OF_ROW = "//*[contains(text(),'{}')]//ancestor::div[@class='row']//following::span[contains(text(),'{}')]//ancestor::div//p[contains(text(),'{}')]"
APPROVAL_BUILDER_A_SCHOOL_ASSIGNED_AVAILABLE_OF_ROW = "//*[normalize-space()='{}']//ancestor::div[@class='row']//p[contains(text(), '{}')]"
APPROVAL_BUILDER_SCHOOL_ASSIGNED_OPTIONS_DROPDOWN = "//li[contains(@class,'dropdown-item')]//following-sibling::span[contains(text(),'{}')]"
APPROVAL_BUILDER_SCHOOL_ASSIGNED_OPTIONS_DROPDOWN_ROW = "//li[contains(@class,'dropdown-item')]//following-sibling::span"
APPROVAL_BUILDER_SCHOOL_ASSIGNED_DROPDOWN = "//span[contains(@class,'number-badge') and contains(text(),'{}')]"
APPROVAL_BUILDER_ROW_ELIPSIS = "//*[normalize-space()='{}']//ancestor::div[@class='row']//*[contains(@class,'icon-menu')]"
APPROVAL_BUILDER_SUBMENU_DELETE = "//*[normalize-space()='{}']//ancestor::div[@class='row']//*[contains(text(),'Delete')]"
APPROVAL_BUILDER_SUBMENU_EDIT = "//*[normalize-space()='{}']//ancestor::div[@class='row']//*[contains(text(),'Edit')]"
APPROVAL_BUILDER_SUBMENU_DUPLICATE = "//*[normalize-space()='{}']//ancestor::div[@class='row']//*[contains(text(),'Duplicate')]"
APPROVAL_BUILDER_NO_APPROVAL_MESSAGE_TEXT = "//*[@id='approvals-builder-list']//*[contains(text(),'{}')]"
