# BASE PAGE
COMPANY_INFORMATION_PATTERN_NAV_TAB = "//div[contains(@class,'nav-text') and contains(text(),'{}')]"
COMPANY_INFORMATION_PATTERN_TITLE_TAB = "//div[contains(@class,'vue-portal-target')]//*[contains(text(),'{}')]"
COMPANY_INFORMATION_PATTERN_DESCRIPTION_TAB = "//div[contains(@class,'vue-portal-target')]//div[contains(text(),'{}')]"

# BASE PAGE // Details tab
DETAIL_TAB_UPLOAD_IMAGE = "//div[contains(@data-testid,'company-info-logo-img')]"
DETAIL_TAB_PATTERN_LABEL = "//label[contains(text(),'{}')]"
DETAIL_TAB_ACCOUNT_NAME_INPUT = "//input[contains(@data-testid,'company-info-account-name-input')]"
DETAIL_TAB_PUBLIC_NAME_INPUT = "//input[contains(@data-testid,'company-info-multilingual-name-input')]"
DETAIL_TAB_PHONE_NUMBER_INPUT = "//div[contains(@data-testid,'company-info-phone-number-input')]"
DETAIL_TAB_COUNTRY_DROPDOWN = "//div[contains(@data-testid,'company-info-country-selection')]"
DETAIL_TAB_STREET_INPUT = "//input[contains(@data-testid,'company-info-primary-address-input')]"
DETAIL_TAB_CITY_INPUT = "//input[contains(@data-testid,'company-info-city-input')]"
DETAIL_TAB_STATE_INPUT = "//input[contains(@placeholder,'State')]"
DETAIL_TAB_CODE_ZIP_INPUT = "//input[contains(@data-testid,'company-info-zip-code-input')]"
DETAIL_TAB_DAY_SELECTION = "//label[contains(text(),'Business hours')]//following-sibling::div[contains(@class,'el-form-item__content')]"
DETAIL_TAB_TIME_INPUT = "//label[contains(text(),'Business hours')]//parent::div[contains(@class,'el-form-item')]/following-sibling::div"
DETAIL_TAB_SECONDARY_ADDRESS_INPUT = "//input[contains(@placeholder,'Apt, Suite, Room')]"

# BASE PAGE // Brand Management tab
BRAND_MANAGEMENT_TAB_ADD_BRAND_BUTTON = "//button[contains(@data-testid,'brand-management-add-btn')]"
BRAND_MANAGEMENT_TAB_ADD_EDIT_BRAND_HEADER = "//header[contains(@id,'el-drawer__title')]//*[contains(text(),'{}')]"
BRAND_MANAGEMENT_TAB_UPLOAD_IMAGE = "//div[contains(@data-testid,'brand-management-edit-drawer-logo-img')]"
BRAND_MANAGEMENT_TAB_UPLOAD_IMAGE_INPUT = "//input[contains(@name,'image')]"
BRAND_MANAGEMENT_TAB_UPLOADED_IMAGE_VISIBLE = "//div[contains(@data-testid,'brand-management-edit-drawer-logo-img')]/img[not(contains(@style,'display: none;'))]"
BRAND_MANAGEMENT_TAB_PATTERN_LABEL = "//div[contains(@role,'dialog')]//label[contains(text(),'{}')]"
BRAND_MANAGEMENT_TAB_BRAND_NAME_INPUT = "//input[contains(@data-testid,'brand-management-edit-drawer-brand-name-input')]"
BRAND_MANAGEMENT_TAB_EXTERNAL_ID_INPUT = "//input[contains(@data-testid,'brand-management-edit-drawer-external-id-input')]"
BRAND_MANAGEMENT_TAB_SAVE_CANCEL_BUTTON = "//div[contains(@class,'config-drawer__footer')]//*[contains(text(),'{}')]//parent::button"
BRAND_MANAGEMENT_TAB_SAVE_V1 = """//div[contains(@class,'config-drawer__footer')]//*[contains(text(),'save')]//parent::button"""
BRAND_MANAGEMENT_TAB_SAVE_DISABLE_BUTTON = "//div[contains(@class,'config-drawer__footer')]//button[contains(@disabled,'disabled')]//*[contains(text(),'Save')]"
BRAND_MANAGEMENT_TAB_CROP_IMAGE_CONFIRM_CANCEL = "//*[contains(@class,'dialog-footer')]//button//*[contains(text(),'{}')]"
BRAND_MANAGEMENT_CREATED_BRAND_NAME = "//div[contains(@data-testid,'brand-management-brand-name-lbl') and contains(text(),'{}')]"
BRAND_MANAGEMENT_TAB_BRAND_TOOL_BUTTON = "//div[contains(@data-testid,'brand-management-brand-name-lbl') and contains(text(),'{}')]//parent::div//preceding-sibling::div//button"
BRAND_MANAGEMENT_TAB_BRAND_EDIT_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none'))]//li[contains(@data-testid,'brand-management-action-edit-btn')]//*[contains(text(),'Edit')]"
BRAND_MANAGEMENT_TAB_BRAND_DEACTIVATE_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//li[contains(@data-testid,'brand-management-action-deactivate-btn')]//*[contains(text(),'Deactivate')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_HEADER = "//div[contains(@aria-label,'Deactivate Brand')]//div[contains(@class,'el-message-box__header')]//*[contains(text(),'Deactivate Brand')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_CONTAIN = "//div[contains(@aria-label,'Deactivate Brand')]//div[contains(@class,'el-message-box__content')]//*[contains(text(),'Are you sure you want to deactivate the ')]//span[contains(text(),'{}')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_DEACTIVATE_CANCEL_BUTTON = "//div[contains(@aria-label,'Deactivate Brand')]//button//*[contains(text(),'{}')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_WARNING_HEADER = "//div[contains(@class,'el-message-box__title')]//*[contains(text(),'Cannot deactivate this brand')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_WARNING_HELP_TEXT = "//div[contains(@class,'el-message-box__message' )]//span[contains(@data-msgid,'You must delete or')]"
BRAND_MANAGEMENT_TAB_POPUP_DEACTIVATE_WARNING_GOTO_JOB_WEB_BUTTON = "//div[contains(@class,'el-message-box__message' )]//button//*[contains(text(),'{}')]"
