# CONVERSATION BUILDER PAGE
CONVERSATION_PAGE_BROWSER_TITLE = "//title[contains(text(),'Conversation Builder')]"
CONVERSATION_TITLE = "//div[contains(@class,'content-title') and text()='Conversation Builder']"
CONVERSATION_EMPTY_TITLE = "//span[contains(@class,'el-table__empty-text')]"
CONVERSATION_LIST = "//table[@class='el-table__body']"
CONVERSATION_ROW_ECLIPSE_ICON = "//strong[contains(text(),'{}')]//ancestor::td//following-sibling::td[last()]//button//i"
ECLIPSE_ICON = "(//i[@class='icon icon-menu'])"
CONVERSATION_SEARCH_BOX = "//div[@data-fetch-key='ConversationMainList:0']//input[@placeholder='Search']"
SEARCH_CONVERSATION_INPUT = "(//div[contains(@class, 'el-input')]//input[@placeholder='Search'])[last()]"
ROW_CONVERSATION_NAME = "//strong[@class='text__highlight' and text()='{}']"
CONVERSATION_NAME_IN_ROW = "//td[contains(@class, 'conversation-name')]//span[contains(.,'{}')]"
ADD_CONVERSATION_BUTTON = "//button[contains(@class,'button--primary')]//*[contains(text(),'Add Conversation')]"
ADD_NEW_CONVERSATION = "//*[contains(@class,'dropdown-menu')]//*[contains(text(),'Add New Conversation')]"
ADD_CUSTOM_CONVERSATION = "//*[contains(@class,'dropdown-menu')]//*[contains(text(),'Add Custom Conversation')]"
CONVERSATION_BUILDER_PAGE_RIGHT_NAV_TEXT = "//div[contains(@class,'nav-text') and normalize-space()='{}']"
CONVERSATION_BUILDER_PAGE_TEMPLATE_CONVERSATION_NUMBER = "//div[contains(@class,'nav-text') and text()='{}']//following-sibling::div"

# CONVERSATION BUILDER PAGE / Eclipse Menu
ECLIPSE_DUPLICATE_BUTTON = "(//ul[contains(@id,'dropdown')]//i[@class='icon-duplicate-o'])[last()]"
CONFIRM_DUPLICATE_BUTTON = "//button[@data-testid='conversation_duplicate_dialog_btn_duppicate']"
ECLIPSE_DELETE_BUTTON = "(//ul[contains(@id,'dropdown')]//i[@class='icon-delete'])[last()]"
CONFIRM_DELETE_BUTTON = "//div[@aria-label='Deactivate this Conversation']//button//span[contains(text(),'Deactive')]"
USED_CONVERSATION_ALERT = "//button[@data-testid='conversationbld_btn_used_items_alert']"
ECLIPSE_EDIT_BUTTON = "(//ul[contains(@id,'dropdown')]//i[contains(@class,'icon-edit')])[last()]"

# ADD CONVERSATION PAGE
CONVERSATION_NAME_TEXTBOX = "//input[@data-testid='conversationbld_input_conversation_name']"
CONVERSATION_TEMPLATE_DROPDOWN = "//*[contains(@class, 'el-select-dropdown')]//span[contains(text(), '{}')]"
CONVERSATION_TYPE = "//span[text()='{}']"
CONVERSATION_SECTION_TITLE = "//*[contains(@data-testid, 'conversationbld_btn_collapse')]//span[contains(text(),'{}')]"
CONVERSATION_DISABLE_SECTION_TITLE = "//*[contains(@class, 'disabled')]//*[contains(@data-testid, 'conversationbld_btn_collapse')]//span[contains(text(),'{}')]"
CONVERSATION_TEMPLATE = "//div[@data-testid='conversationbld_select_template_type']"
CONVERSATION_WHATS_APP = "//div[@data-testid='conversationbld_select_whatsapp']"
CONVERSATION_WHATS_APP_DROPDOWN = "//*[contains(@class, 'el-select-dropdown')]//span[contains(text(), '{}')]"
QUESTION_TOOLTIP_MENU = "//div[contains(@id,'el-popover') and @aria-hidden='false']//span[text()='{}']"
QUESTION_CONTENT = "//input[contains(@data-testid,'conversationbld_input_global_screenings')]//parent::div//parent::div//following-sibling::div[@data-testid='conversationbld_text_area_global_screenings_content_undefined']//div[@contenteditable='true']"
CONVERSATION_PUBLIC_STATUS_LABEL = "//div[contains(@class, 'status published')]"
PUBLIC_STATUS_BUTTON = "//button[@data-testid='customconvo_btn_publish']"
PUBLIC_BUTTON = "//button[@data-testid='conversationbld_btn_publish']"
TOOLTIP_MESSAGE = "//div[@role='tooltip' and text()='{}']"
QUESTION_BOX = "//div[contains(@data-testid,'conversationbld_div_question_content')]"
CONVERSATION_PUBLIC_STATUS_LABEL = "//div[contains(@class, 'status published')]"
REMOVE_TOOL_POPUP_MESSAGE = "//div[@class='el-dialog__body']//span[@data-testid='conversationbld_lbl_remove_tool_content']"
REMOVE_TOOL_NO_BUTTON = "//div[@class='el-dialog__body']//following-sibling::div[@class='el-dialog__footer']//span[@class='dialog-footer']//button[@class='el-button el-button--default']"
REMOVE_TOOL_YES_BUTTON = "//div[@class='el-dialog__body']//following-sibling::div[@class='el-dialog__footer']//span[@class='dialog-footer']//button[@class='el-button el-button--primary']"
DELETE_QUESTION_POPUP_MESSAGE = "//div[@class='el-message-box ol-confirm']//div[@class='el-message-box__message']"
DELETE_QUESTION_NO_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default']"
DELETE_QUESTION_YES_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default el-button--primary']"
CONFIRM_CHANGES_MESSAGE = "//div[@class='el-message-box ol-confirm']//div[@class='el-message-box__message']"
CANCEL_CHANGES_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default']"
CONFIRM_CHANGES_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default el-button--primary']"
REMOVE_CHANGES_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default el-button--danger']"
CANDIDATE_JOURNEY_DROPDOWN = "//div[@data-testid='cj-group-select']"
SEARCH_GROUP_TEXT_BOX = "//input[@placeholder='Search for Group']"
SELECT_GROUP_DROPDOWN = "//input[contains(@placeholder,'Select Group')]"
SEARCH_JOURNEY_TEXT_BOX = "//input[@placeholder='Search for candidate journey']"
SEARCH_JOURNEY_VALUE = "//div[contains(@class,'el-scrollbar')]//li[contains(@class, 'el-select-dropdown__item')]//span[contains(text(), '{}')]"
LOCATION_ATTRIBUTE_LIST = "//*[contains(@class,'suggest-item')]"
CONVERSATION_OUTBOUND_INPUT = "//span[contains(text(), 'Outbound')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_INTRODUCTION_INPUT = "//span[contains(text(), 'Introduction')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_CONTACT_INFORMATION_INPUT = "//span[contains(text(), 'Contact Information')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_COMMUNICATION_PREFERENCE_INPUT = "//span[contains(text(), 'Communication Preference')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_EEO_INPUT = "//span[contains(text(), 'Equal Employment')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_CLOSING_INPUT = "//span[contains(text(), 'Closing')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
CONVERSATION_THANKYOU_INPUT = "//span[contains(text(), 'Thank you')]/parent::div[contains(@data-testid, 'conversationbld_btn_collapse')]/following-sibling::div//div[contains(@data-testid, 'conversationbld_text_area_')]//div[contains(@contenteditable, 'true')]"
DELETE_CONVERSATION_BUTTON = "//button/i[contains(@class, 'icon-delete2')]"
EMAIL_TOGGLE = "//span[contains(text(),'Email')]/ancestor::div[contains(@data-testid,'conversationbld_div_question_content')]//*[contains(@data-testid,'conversationbld_button_toggle_tool')]"
PHONE_NUMBER_TOGGLE = "//span[contains(text(),'Phone Number')]/ancestor::div[contains(@data-testid,'conversationbld_div_question_content')]//*[contains(@data-testid,'conversationbld_button_toggle_tool')]"
COMMUNICATION_PREFERENCE_TOGGLE = "//span[contains(text(),'Communication Preference')]/ancestor::div[contains(@data-testid,'conversationbld_div_question_content')]//*[contains(@data-testid,'conversationbld_button_toggle_tool')]"
CONVERSATION_DELETE_ICON = "//i[@class='icon icon-delete2']"
CONVERSATION_DEACTIVATE_BUTTON = "//button[contains(@class,'button--danger')]//*[contains(text(),'Deactivate')]"
OK_BUTTON = "//div[contains(text(), 'Conversation Name is required')]//following-sibling::div//span[contains(text(), 'Ok')]"
CONVERSATION_LANGUAGE_DROPDOWN = "//*[contains(@data-testid, 'converastionbld_select_languages')]"
CONVERSATION_SEARCH_LANGUAGE_TEXTBOX = "//input[@placeholder='Search Languages']"
CONVERSATION_LANGUAGE_TAB = "//*[contains(@id, '{}')]"

# ADD CONVERSATION PAGE / Available locations popup
AVAILABLE_LOCATIONS_DROPDOWN = "//div[@data-testid='conversationbld_select_location_groups']//span[@class='el-input__suffix-inner']"
AVAILABLE_LOCATIONS_SELECT_LOCATION_OPTION = "//label[@data-testid='select_location_type_options_0']"
AVAILABLE_LOCATIONS_REMOTE_OPTION = "//label[@data-testid='select_location_type_options_1']"
AVAILABLE_LOCATIONS_UNASSIGNED_OPTION = "//label[@data-testid='select_location_type_options_2']"
AVAILABLE_LOCATIONS_FIND_LOCATION_TEXT_BOX = "//input[@placeholder='Find a location']"
AVAILABLE_LOCATIONS_SELECT_ALL_CHECK_BOX = "//*[contains(text(),'Select all')]//ancestor-or-self::div[@class='el-tree-node__content']//label//span[@class='el-checkbox__input']"
AVAILABLE_LOCATIONS_SELECT_BY_LOCATION_NAME = "//*[contains(text(),'{}')]//ancestor-or-self::div[@class='el-tree-node__content']//label//span[@class='el-checkbox__input']"
AVAILABLE_LOCATIONS_LOCATION_NAME_CHECKBOX = "//*[contains(@class, 'tree-node__content') and contains(normalize-space(), '{}')]//*[contains(@class, 'el-checkbox__inner')]"

# ADD CONVERSATION / Dynamic ATS conversation
ADD_CANDIDATE_QUESTION_BUTTON = "//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div/div[not(contains(@style,'display: none'))]//div[@data-testid='conversationbld_block_adding_question']"
CANDIDATE_QUESTION_SUBTOOL_BUTTON = "//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::i[contains(@data-testid,'conversationbld_icon_subTool')]"
CANDIDATE_QUESTION_1_LABEL = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[1]"
CANDIDATE_QUESTION_2_LABEL = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[2]"
CANDIDATE_QUESTION_3_LABEL = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[3]"
CANDIDATE_QUESTION_CONDITION_TOOLTIP = "//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'condition')]"
ADD_SCREENING_QUESTION_BUTTON= "//span[contains(text(),'Screening')]//parent::div//following-sibling::div//child::div[@data-testid='conversationbld_block_adding_question']"
SCREENING_QUESTION = "//span[contains(text(),'. Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')]"
SCREENING_QUESTION_SUBTOOL_BUTTON = "//span[contains(text(),'Screening')]//parent::div//following-sibling::div//child::i[contains(@data-testid,'conversationbld_icon_subTool')]"
SCREENING_QUESTION_CONDITION_TOOLTIP = "//span[contains(text(),'. Screening')]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'condition')]"
SCREENING_QUESTION_1_LABEL = "(//span[contains(text(),'Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[1]"
SCREENING_QUESTION_2_LABEL = "(//span[contains(text(),'Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[2]"
CANDIDATE_QUESTION_REORDER_TARGET = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[2]//parent::div//parent::div//following-sibling::div[@class='editor-container']"
CANDIDATE_QUESTION_REORDER_SOURCE = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::div[contains(@class,'draggable')])[2]//i[contains(@class,'icon-reorder')]"
CANDIDATE_QUESTION_SUBTOOL_BUTTON_2 = "(//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::i[contains(@data-testid,'conversationbld_icon_subTool')])[2]"
CANDIDATE_QUESTION_DISABLED = "//span[contains(text(),'. Additional Candidates Questions')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings') and @disabled='disabled']"
CONVERSATION_TEMPLATE_INPUT_SECTION = "//span[normalize-space()='{}']//ancestor::div[contains(@data-testid, 'question_content')]//div[contains(@class, 'editor-container')]"
ICON_SUBTOOL_MENU_EACH_SECTION = "//span[normalize-space()='{}']//ancestor::div[contains(@data-testid, 'question_content')]//i[contains(@class, 'el-popover')]"
ICON_ATS_MAPPING = "//span[contains(text(),'{}')]//ancestor::div[contains(@data-testid, 'question_content')]//span[contains(@class, 'icon-ats-map')]"
SECTION_TOGGLE = "//span[normalize-space()='{}']//ancestor::div[contains(@data-testid, 'question_content')]//span[contains(@class, 'el-switch')]"

# ADD CONVERSATION / Multiple Path
GROUP_QUESTION_CONTENT = "//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div//div[@data-testid='conversationbld_text_area_global_screenings_content_undefined']//div[@class='el-input__inner']"
ADD_GROUP_1_QUESTION = "//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[1]//div[@data-testid='conversationbld_block_adding_question']"
GROUP_1_QUESTION_1_LABEL = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[1]//input[@class='el-input__inner'])[1]"
GROUP_1_QUESTION_2_LABEL = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[1]//input[@class='el-input__inner'])[2]"
GROUP_1_QUESTION_1_SUBTOOL_BUTTON = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div//div[contains(text(),'group')])[1]//parent::div//following-sibling::div//i[contains(@data-testid,'conversationbld_icon_subTool')]"
GROUP_1_QUESTION_2_SUBTOOL_BUTTON = "((//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div//div[contains(text(),'group')])[1]//parent::div//following-sibling::div//i[contains(@data-testid,'conversationbld_icon_subTool')])[2]"
GROUP_1_QUESTION_2_HIDE_TOOLTIP = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div//div[contains(text(),'group')])[1]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'icon-eye-blocked')]"
GROUP_1_QUESTION_1_CONDITION_TOOLTIP = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div//div[contains(text(),'group')])[1]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'condition')]"
ADD_GROUP_2_QUESTION = "//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[2]//div[@data-testid='conversationbld_block_adding_question']"
GROUP_2_QUESTION = "//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[2]//input"
GROUP_2_QUESTION_1_LABEL = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[2]//input[@class='el-input__inner'])[1]"
GROUP_2_QUESTION_2_LABEL = "(//span[contains(text(),'. Groups Screening')]//parent::div//following-sibling::div/div[2]//input[@class='el-input__inner'])[2]"
MULTIPLE_PATH_EDIT_GROUP_BUTTON = "//button[contains(@type,'button')]//child::*[contains(text(),'Edit group')]"

# ADD CONVERSATION / Multiple Path / Edit group
MULTIPLE_PATH_EDIT_GROUP_DIALOG_TITLE = "//div[contains(@class,'el-dialog__body')]//child::span"
MULTIPLE_PATH_SELECT_GROUP_DROPDOWN = "//div[contains(@class,'el-dialog__body')]//div[@data-testid='group_{}']//child::input[contains(@placeholder,'Select group')]"
MULTIPLE_PATH_SEARCH_GROUP_BOX = "//div[contains(@x-placement,'bottom')]//input[contains(@class,'el-input__inner')]"
MULTIPLE_PATH_SEARCH_RESULT = "//li[contains(@data-testid,'option_of_group_{}')]//span[contains(text(),'{}')]"
MULTIPLE_PATH_CANCEL_SAVE_BUTTON = "(//div[@data-testid='select_groups_dialog']//button[contains(@class,'el-button')]//span[contains(text(),'{}')])[last()]"

# ADD CONVERSATION / Single Path
ADD_GLOBAL_SCREENING_QUESTION = "//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div/div[not(contains(@style,'display: none'))]//div[@data-testid='conversationbld_block_adding_question']"
GLOBAL_SCREENING_QUESTION_CONTENT_1 = "(//span[contains(text(),'Global Screening')]//parent::div//following-sibling::div//div[contains(@data-testid,'conversationbld_text_area')]//div[@class='el-input__inner'])[1]"
GLOBAL_SCREENING_QUESTION_CONTENT_2 = "(//span[contains(text(),'Global Screening')]//parent::div//following-sibling::div//div[contains(@data-testid,'conversationbld_text_area')]//div[@class='el-input__inner'])[2]"
GLOBAL_SCREENING_QUESTION_1_LABEL = "(//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[1]"
GLOBAL_SCREENING_QUESTION_2_LABEL = "(//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings')])[2]"
GLOBAL_SCREENING_QUESTION_SUBTOOL_BUTTON = "//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//child::i[contains(@data-testid,'conversationbld_icon_subTool')]"
GLOBAL_SCREENING_QUESTION_SUBTOOL_BUTTON_2 = "(//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//child::i[contains(@data-testid,'conversationbld_icon_subTool')])[2]"
GLOBAL_SCREENING_QUESTION_CONDITION_TOOLTIP = "//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'condition')]"
GLOBAL_SCREENING_QUESTION_DISABLED = "//span[contains(text(),'. Global Screening')]//parent::div//following-sibling::div//child::input[contains(@data-testid,'conversationbld_input_global_screenings') and @disabled='disabled']"
GLOBAL_SCREENING_QUESTION_DELETE_ICON = "(//*[contains(@data-testid,'conversationbld_btn_tool')]//*[contains(@class,'icon-delete')])[last()]"
CONFIRM_DELETE_QUESTION_BUTTON = "(//span[contains(text(),'Yes')])[last()]"
SINGLE_PATH_QUESTION_TOGGLE = "//*[contains(@data-testid, 'question_content') and contains(normalize-space(),'{}')]//span[contains(@class, 'el-switch__core')]"

# ADD CONVERSATION / Single Path / Add Tool
VIDEO_RESPONSE_TOOL = "//div[contains(@data-testid,'conversationbld_block_action')]//strong[text()='Video Response']"
VIDEO_RESPONSE_SAVE_BUTTON = "//div[@aria-label='Video Response']//button[@data-testid='conversationbld_btn_action']"
LIST_SELECT_TOOL = "//div[contains(@data-testid,'conversationbld_block_action')]//strong[text()='List Select']"
DOCUMENT_UPLOAD_TOOL = "//div[contains(@data-testid,'conversationbld_block_action')]//strong[text()='Document Upload']"
ADD_TOOL_NEXT_BUTTON = "//div[@aria-label='Select a Tool']//button[@data-testid='conversationbld_btn_action']"
LIST_SELECT_TOOL_ADD_ITEM_BUTTON = "//button[@data-testid='conversationbld_btn_add_item']"
LIST_ITEM_1_NAME = "//input[@data-testid='conversationbld_input_listItem_0_name']"
LIST_ITEM_2_NAME = "//input[@data-testid='conversationbld_input_listItem_1_name']"
LIST_ITEM_3_NAME = "//input[@data-testid='conversationbld_input_listItem_2_name']"
LIST_SELECT_SAVE_BUTTON = "//div[@aria-label='List Select']//button[@data-testid='conversationbld_btn_action']"
DOCUMENT_UPLOAD_SAVE_BUTTON = "//div[@aria-label='Document Upload']//button[@data-testid='conversationbld_btn_action']"
USED_TOOL_ERROR = "//div[@class='toasted toasted-primary error']"
CONVERSATION_QUESTION_OPTION_TOGGLE = "(//*[contains(text(),'{}')])[last()]//ancestor::div[contains(@class,'el-row')]//div//following-sibling::*//*[@role='switch']"
CONVERSATION_QUESTION_OPTION_DOCUMENT_UPLOAD_TOGGLE = "(//*[contains(text(),'{}')])[last()]//following-sibling::div"

# ADD CONVERSATION / Skip Next Question Tool
STARTING_VALUE_DISABLED = "//label[@data-msgid='Starting Value']//following-sibling::div//input[contains(@disabled, 'disabled')]"
STARTING_VALUE_ENABLED = "//label[@data-msgid='Starting Value']//following-sibling::div//input[not(contains(@disabled, 'disabled'))]"
STARTING_VALUE_TEXT = "//label[@data-msgid='Starting Value']//following-sibling::div//input"
STARTING_VALUE_DROPDOWN = "//label[contains(text(), 'Starting Value')]//parent::div//following-sibling::div"
STARTING_VALUE_DROPDOWN_2 = "(//label[contains(text(), 'Starting Value')]//parent::div//following-sibling::div)[2]"
SKIP_QUESTION_DISABLED = "//label[@data-msgid='Skip Question']//following-sibling::div//input[contains(@disabled, 'disabled')]"
SCREEN_FOR_DROPDOWN = "//label[@data-msgid='Screen For']//following-sibling::div"
SCREEN_FOR_DROPDOWN_2 = "(//label[@data-msgid='Screen For']//following-sibling::div)[2]"
SCREEN_FOR_IS_OPTION = "(//*[contains(@class,'dropdown__list')])[last()]//span[normalize-space()='Is']"
SCREEN_FOR_IS_NOT_OPTION = "(//*[contains(@class,'dropdown__list')])[last()]//span[normalize-space()='Is Not']"
TEXT_INPUT_TEXTBOX = "//label[@data-msgid='Text Input']//following-sibling::div//input[not(contains(@disabled, 'disabled'))]"
TEXT_INPUT_TEXTBOX_2 = "(//label[@data-msgid='Text Input']//following-sibling::div//input[not(contains(@disabled, 'disabled'))])[2]"
TEXT_INPUT_TEXTBOX_EMPTY_ERROR = "//div[@class='el-form-item__error']"
TEXT_INPUT_DROPDOWN_ICON = "//label[@data-msgid='Text Input']//following-sibling::*//i[contains(@class,'el-icon-arrow')]"
TEXT_INPUT_DROPDOWN_ICON_2 = "(//label[@data-msgid='Text Input']//following-sibling::*//i[contains(@class,'el-icon-arrow')])[2]"
SKIP_QUESTION_APPLY_BUTTON = "//div[@id='skip-condition-drawer-top-title']//ancestor::div[@aria-labelledby='el-drawer__title']//button[contains(@class,'primary')]"
SKIP_QUESTION_CANCEL_BUTTON = "//div[@id='skip-condition-drawer-top-title']//ancestor::div[@aria-labelledby='el-drawer__title']//button[@class='el-button el-button--default el-button--medium']"
SKIP_QUESTION_REMOVE_BUTTON = "//div[@id='skip-condition-drawer-top-title']//ancestor::div[@aria-labelledby='el-drawer__title']//button[@class='el-button el-button--danger el-button--medium']"
SKIP_QUESTION_OR_BUTTON = "//button[@data-testid='customconvo_statement_btn_or']"
TEXT_INPUT_DROPDOWN = "//label[@data-msgid='Text Input']//following-sibling::span//div[@data-testid='btn_show_menu']"
TEXT_INPUT_DROPDOWN_INPUT = "//label[@data-msgid='Text Input']//following-sibling::span//div[@data-testid='btn_show_menu']//input"
TEXT_INPUT_POPUP_APPLY_BUTTON = "//div[@data-testid='multidropdown_input_search']//parent::div//button[@data-testid='multidropdown_btn_apply']"
SKIP_QUESTION_TOOL_DROPDOWN_OPTION = "(//*[contains(@class,'dropdown__list')])[last()]//span[normalize-space()='{}']"
SKIP_QUESTION_TOOL_DROPDOWN_CHECKBOX = "//span[text()='{}']//parent::span//parent::label//child::span[@class='el-checkbox__input']"
CONDITION_DELETE_BUTTON = "//form[contains(@class,'el-form')]//i[@class='icon icon-delete2']"
CONDITION_DUPLICATE_ERROR = "//form[contains(@class,'duplicate-error')]"

# ADD CONVERSATION PAGE / ATS MAPPING POPUP
ATS_FIELD_TEXTBOX = "//div[@aria-label='ATS Mapping']//div[@class='el-input']//input"
ATS_MAPPING_INPUT_WITH_ADDRESS_DATA_METHOD = "//span[contains(text(), '{}')]//parent::div//div[@class='el-input']//input"
ATS_PICK_LIST_ID_TEXTBOX = "//label[@for='pick_list_id']//following-sibling::div//input[@class='el-input__inner']"
ATS_DATA_METHOD_DROPDOWN = "//div[@aria-label='ATS Mapping']//div[@class='el-input el-input--suffix']"
ATS_DATA_METHOD_VALUE = "(//*[contains(@class,'dropdown__list')])[last()]//span[normalize-space()='{}']"
ATS_POPUP_SAVE_BUTTON = "(//div[@aria-label='ATS Mapping']//button[@data-testid='customconvo_ats_mapping_dialog_btn_save'])[last()]"
ATS_POPUP_REMOVE_BUTTON = "//div[@data-testid='customconvo_ats_mapping_dialog' and not(contains(@style,'display: none;'))]//button[@data-testid='customconvo_ats_mapping_dialog_btn_remove']"
ATS_CONFIRM_CHANGES_MESSAGE = "//div[@class='el-message-box ol-confirm ']//div[@class='el-message-box__message']"
ATS_CANCEL_CHANGES_BUTTON = "//div[@class='el-message-box ol-confirm ']//button[@class='el-button el-button--default']"
ATS_CONFIRM_CHANGES_BUTTON = "//div[@class='el-message-box ol-confirm ']//button[@class='el-button el-button--default el-button--primary']"

# ADD CONVERSATION PAGE / ATS MAPPING POPUP / Remove ats mapping
ATS_WARNING_POPUP_MESSAGE = "//div[@data-testid='customconvo_ats_mapping_warning_dialog']//div[@class='el-dialog__body']"
ATS_WARNING_POPUP_NO_BUTTON = "//div[@data-testid='customconvo_ats_mapping_warning_dialog']//button[@class='el-button el-button--default']"
ATS_WARNING_POPUP_YES_BUTTON = "//div[@data-testid='customconvo_ats_mapping_warning_dialog']//button[@class='el-button el-button--primary']"

# ADD CONVERSATION PAGE / System Attributes popup
SYSTEM_ATTR_METHOD = "//div[@data-testid='customconvo_candiate_attr_methods_select']"
SYSTEM_ATTR_METHOD_VALUE = "(//*[contains(@class,'dropdown__list')])[last()]//span[normalize-space()='{}']"
MAP_TO_SYSTEM_ATTR = "//div[@data-testid='customconvo_candiate_attr_item_select']"
SYSTEM_ATTR_POPUP_CANCEL = "//span[@data-testid='customconvo_candiate_attr_dialog_title']//ancestor::div[@class='el-dialog__body']//following-sibling::div[@class='el-dialog__footer']//button[@data-testid='customconvo_candiate_attr_btn_cancel']"
SYSTEM_ATTR_POPUP_SAVE = "//span[@data-testid='customconvo_candiate_attr_dialog_title']//ancestor::div[@class='el-dialog__body']//following-sibling::div[@class='el-dialog__footer']//button[@data-testid='customconvo_candiate_attr_btn_save']"

# ADD CONVERSATION / Conditional Conversation
CONVERSATION_BLOCK_ADD_QUESTION_NO = "//div[contains(text(), 'A. No')]//parent::div//following-sibling::div//div[contains(@data-testid, 'conversationbld_block_adding_question')]"
QUESTION_NO_1_LABEL = "(//div[contains(text(), 'A. No')]//parent::div//following-sibling::div//input)[1]"
QUESTION_NO_2_LABEL = "(//div[contains(text(), 'A. No')]//parent::div//following-sibling::div//input)[2]"
CONVERSATION_BLOCK_ADD_QUESTION_DEFAULT = "//div[contains(text(), 'B. Default')]//parent::div//following-sibling::div//div[contains(@data-testid, 'conversationbld_block_adding_question')]"
QUESTION_DEFAULT_1_LABEL = "(//div[contains(text(), 'B. Default')]//parent::div//following-sibling::div//input)[1]"
QUESTION_DEFAULT_2_LABEL = "(//div[contains(text(), 'B. Default')]//parent::div//following-sibling::div//input)[2]"
CONVERSATION_BLOCK_ADD_QUESTION_YES = "//div[contains(text(), 'C. Yes')]//parent::div//following-sibling::div//div[contains(@data-testid, 'conversationbld_block_adding_question')]"
QUESTION_YES_1_LABEL = "(//div[contains(text(), 'C. Yes')]//parent::div//following-sibling::div//input)[1]"
QUESTION_YES_2_LABEL = "(//div[contains(text(), 'C. Yes')]//parent::div//following-sibling::div//input)[2]"
QUESTION_YES_SUBTOOL_BUTTON = "(//div[contains(text(), 'Yes')]//parent::div//following-sibling::div//i[contains(@data-testid, 'conversationbld_icon_subTool')])[1]"
QUESTION_YES_CONDITION_TOOLTIP = "//div[contains(text(),'Yes')]//parent::div//following-sibling::div//div[@class='mentionable']//span[contains(@class,'condition')]"
QUESTION_YES_ICON_CONDITION_TOOLTIP_1 = "(//div[contains(text(),'Yes')]//parent::div//div[@class='mentionable']//span[contains(@class,'condition')])[1]"
QUESTION_YES_SUBTOOL_BUTTON_1 = "(//div[contains(text(), 'Yes')]//parent::div//following-sibling::div//i[contains(@data-testid, 'conversationbld_icon_subTool')])[2]"
ADD_AND_SCREEN = "//span[contains(text(), 'Add & Screen')]"
ADD_AND_SCHEDULE = "//span[contains(text(), 'Add & Schedule')]"
LIST_SELECT_CONDITION = "//div[@data-testid='btn_show_menu']//div"
SEND_SCREEN_BUTTON = "(//span[text()='Send'])[1]"
DROPDOWN_CARET_BUTTON = "//button[contains(@class, 'el-button el-button--primary el-dropdown__caret-button')]"
SKIP_BUTTON = "//*[contains(text(), 'Skip')]"
CONDITION_CONVERSATION_SEARCH_BOX = "//div[@data-testid='input_search']//input"

# ADD CONVERSATION / Screening and Actions
ADD_SCREENING_AND_ACTION_BUTTON = "//*[contains(@data-testid,'conversationbld_btn_add_new_condition')]"
SCREENING_AND_ACTION_THEN_DROPDOWN = "//*[contains(@data-testid,'conversationbld_select_action')]"
SCREENING_AND_ACTION_THEN_OPTION_BY_NAME = "//*[contains(@class,'select-dropdown')]//*[contains(text(),'{}')]"
SCREENING_AND_ACTION_SEND_SCHEDULE_TEXTBOX = "//*[contains(@data-testid,'conversationbld_text_area_schedule_msg')]//*[contains(@contenteditable,'true')]"
SCREENING_AND_ACTION_SEND_SCHEDULE_TO_EVENT_TEXTBOX = "//*[contains(@data-testid,'conversationbld_text_area_event_schedule_msg')]//*[contains(@contenteditable,'true')]"
SCREENING_AND_ACTION_SEND_OVERRIDE_CLOSING_MESSAGE_TEXTBOX = "//*[contains(@data-testid,'conversationbld_text_area_override_msg')]//*[contains(@contenteditable,'true')]"

# ADD CONVERSATION / Communication Preference / Provide the following contact methods to the candidate
CONVERSATION_CONTACT_METHOD_TITLE = "//div[contains(text(), 'contact methods')]/following-sibling::div//span[contains(@class, 'el-checkbox__label') and contains(text(), '{}')]"
CONVERSATION_CONTACT_METHOD_CHECKED_CHECKBOX= "//div[contains(text(), 'contact methods')]/following-sibling::div//span[contains(@class, 'el-checkbox__label') and contains(text(), '{}')]/parent::label//input[@type='checkbox' and contains(@value, 'on')]/parent::span"
