# BASE PAGE
DYNAMIC_CONTENT_TITLE = "//p[contains(text(),'Dynamic Content')]"
DYNAMIC_CONTENT_SEARCH_ICON = "//div[contains(@class,'cms-dynamic-content-dashboard')]//div[contains(@class,'v-search-box white')]//div[contains(@class,'search')]//child::span"
DYNAMIC_CONTENT_SEARCH_CONTENT = "//div[contains(@class,'search-inner')]//input[contains(@class,'search-cms') and contains(@placeholder,'Search Content')]"
DYNAMIC_CONTENT_SEARCH_INPUT = "//input[contains(@aria-label,'Search Content')]"
DYNAMIC_CONTENT_ROW = "//div[contains(@class,'data-list-container')]//div[contains(@class,'items')]"
DYNAMIC_CONTENT_ADD_COLLECTION_BUTTON = "//button[contains(@class,'btn-primary cms-dynamic-content-dashboard__add-new-btn')]"
DYNAMIC_CONTENT_DESCRIPTION = "//div[contains(@class,'cms-dynamic-content-dashboard__title')]//p[contains(@class,'desc')]"
DYNAMIC_CONTENT_TABLE_EMPTY = "//div[contains(@class,'data-empty')]"
DYNAMIC_CONTENT_COLLECTION_NAME = "//div[contains(@class,'header')]//div[contains(text(),'Collection Name')]"
DYNAMIC_CONTENT_ASSIGNED_AUDIENCE = "//div[contains(@class,'header')]//div[contains(text(),'Assigned Audience')]"
DYNAMIC_CONTENT_LAST_EDITED = "//div[contains(@class,'header')]//div[contains(text(),'Last Edited')]"
DYNAMIC_CONTENT_SAVE_CHANGE_ALERT = "//div[contains(@class,'jq-toast') and contains(text(),'Save change dynamic content successfully')]"
DYNAMIC_CONTENT_SUB_MEMU_ICON = "//div[@id='sub-menu']"

# BASE PAGE / ICON SUB-MENU
DYNAMIC_CONTENT_SUB_MENU_OPTION = "//div[contains(@class,'menu') and contains(@style,'display: block')]//span[contains(text(),'{}')]"
DYNAMIC_CONTENT_CONFIRM_MODAL_DELETE_BUTTON = "//div[contains(@class,'modal-footer')]//button[contains(text(),'Delete')]"
DYNAMIC_CONTENT_CONFIRM_MODAL_CANCEL_BUTTON = "//div[contains(@class,'modal-content printable')]//div[contains(@class,'modal-footer')]//button[contains(text(),'Cancel')]"

# BASE PAGE / Add Collection
COLLECTION_HEADER = "//div[contains(@class,'cms-content-header')]//label[contains(text(),'Name your content collection')]"
COLLECTION_HEADER_EDIT_ICON = "//div[contains(@class,'cms-content-header')]//i[contains(@class,'icon icon-edit')]"
COLLECTION_HEADER_INPUT_NAME = "//*[contains(text(),'Name your content collection') or contains(@placeholder,'Name your content collection')]"
COLLECTION_CANCEL_BUTTON = "//div[contains(@class,'cms-content-header__buttons')]//button[contains(@class,'btn btn-default')]"
COLLECTION_CREATE_BUTTON = "//div[contains(@class,'cms-content-header__buttons')]//button[contains(text(),'Create')]"
CONTENT_COLLECTION_TITLE = "//div[contains(@class,'cms-content-collection--title')]"
CONTENT_COLLECTION_DESCRIPTION = "//div[contains(@class,'cms-content-collection')]//div[contains(@class,'note')]"
CONTENT_COLLECTION_ADD_MEDIA_BUTTON = "//div[contains(@class,'cms-content-detail')]//button[contains(@class,'btn btn-default custom-btn') and contains(text(),'Add Media')]"
AUDIENCE_TITLE = "//div[contains(@class,'cms-content-audience--title')]"
AUDIENCE_DESCRIPTION = "//div[contains(@class,'cms-content-audience')]//div[contains(@class,'note')]"
CONTENT_COLLECTION_LIST = "//div[contains(@class,'body')]//div[contains(@class,'card__header')]"

# BASE PAGE / Add Collection / Add Media
COLLECTION_ADD_MEDIA_MODAL = "//div[contains(@id,'content_modal')]"
COLLECTION_ADD_MEDIA_MODAL_TITLE = "//div[contains(@id,'content_modal')]//span[contains(text(),'Add Media')]"
COLLECTION_ADD_MEDIA_MODAL_CLOSE_ICON = "//div[@id='content_modal']//div[contains(@class, 'modal-header')]//i[contains(@class,'btn-close-add-modal')]"
COLLECTION_ADD_MEDIA_MODAL_SEARCH_BOX = "//div[contains(@id,'media_contents_modal')]//input[contains(@id,'search-content')]"
COLLECTION_ADD_MEDIA_MODAL_ADD_NEW_BUTTON = "//div[contains(@id,'media_contents_modal')]//span[contains(text(),'Add New')]"
COLLECTION_ADD_MEDIA_MODAL_MEDIA_TYPE_TAB = "//div[contains(@id,'media_contents_modal')]//span[contains(text(),'{}')]"
COLLECTION_ADD_MEDIA_MODAL_VIDEO_TAB = "//div[contains(@id,'media_contents_modal')]//span[contains(text(),'Video')]"
COLLECTION_ADD_MEDIA_MODAL_IMAGE_TAB = "//div[contains(@id,'media_contents_modal')]//span[contains(text(),'Image/GIF')]"
COLLECTION_ADD_MEDIA_MODAL_HYPERLINKS_TAB = "//div[contains(@id,'media_contents_modal')]//span[contains(text(),'Hyperlinks')]"
COLLECTION_ADD_MEDIA_MODAL_CANCEL_BUTTON = "//div[contains(@id,'media_contents_modal')]//button[contains(text(),'Cancel')]"
COLLECTION_ADD_MEDIA_MODAL_ADD_BUTTON = "//div[contains(@id,'media_contents_modal')]//button[contains(text(),'Add')]"
COLLECTION_ADD_MEDIA_MODAL_LIST_MEDIA = "//div[contains(@class,'item__media')]"

# BASE PAGE / Add Collection / Add Media /Add New
COLLECTION_ADD_NEW_MEDIA_MODAL = "//div[contains(@id,'content_modal')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_TITLE = "//div[contains(@id,'content_modal')]//span[contains(text(),'Add New Media')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_CLOSE_ICON = "//div[@id='content_modal']//div[contains(@class, 'modal-header')]//i[contains(@class,'btn-close-add-modal')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_STEP_ITEM = "//div[@id='create_media_modal']//div[contains(@class, 'add-content-body__title') and contains(text(),'{}')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_MEDIA_TYPE = "//div[contains(@id,'create_media_modal')]//child::div[contains(text(),'Select Media Type')]"
COLLECTION_ADD_NEW_MEDIA_TYPE = "//div[contains(@class,'cusstom-radio')]//label[contains(text(),'{}')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_VIDEO = "//input[contains(@id,'video')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_IMAGE = "//input[contains(@id,'image')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_HYPERLINKS = "//input[contains(@id,'link')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_NAME_CONTENT_TEXTBOX = "//input[contains(@placeholder,'Enter content title')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_ADD_ALT_TEXT = "//input[contains(@placeholder,'Enter alt text')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_UPLOAD_FILE = "//div[contains(@class,'media-upload')]//input[contains(@name,'csrfmiddlewaretoken')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_URL = "//input[@id='media-upload-url']"
COLLECTION_ADD_NEW_MEDIA_MODAL_HYPERLINKS_URL = "//input[@id='content-url']"
COLLECTION_ADD_NEW_MEDIA_MODAL_CANCEL_BUTTON = "//div[contains(@class,'add-content-footer')]//button[contains(text(),'Cancel')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_CREATE_BUTTON = "//div[contains(@class,'add-content-footer')]//button[contains(text(),'Create')]"
COLLECTION_ADD_NEW_MEDIA_MODAL_VIDEO_LIST = "//div[contains(@class,'list-media')]//input[contains(@type,'checkbox')]"
COLLECTION_ADD_NEW_MEDIA_CROP_COMFIRM_BUTTON = "//div[contains(@class,'modal ai-modal dropzone-modal in')]//button[contains(text(),'Confirm')]"

# BASE PAGE / Add Collection / Add Audience
COLLECTION_ADD_AUDIENCE_BUTTON = "//div[contains(@id,'content')]//div[@class='btn-cnt']//button[contains(text(), 'Add Audience')]"
COLLECTION_AUDIENCE_LIST = "//ul[contains(@class,'audience-list')]//li"
COLLECTION_AUDIENCE_ITEM = "//ul[contains(@class,'audience-list')]//li//label[contains(text(),'{}')]"
COLLECTION_AUDIENCE_LIST_ITEM_LABEL = "//ul[contains(@class,'audience-list')]//div[contains(@class,'info')]"
COLLECTION_AUDIENCE_FIRST_CONTENT = "//div[contains(@class,'audience-info')]//div[contains(@class,'content') and contains(text(),'Conversation State is Email')]"
COLLECTION_AUDIENCE_APPLY_BUTTON = "//div[contains(@class,'cms-content-audience__dropdown-btn')]//child::button[contains(text(),'Apply')]"
