# BASE PAGE
EMPLOYER_TAX_INFO_CLOSE_MODAL_ICON = "(//*[@data-dismiss='modal' and contains(@class,  'icon-remove')])[last()]"
EMPLOYER_TAX_INFO_PUBLISH_BUTTON = "//button[contains(@class, 'btn-publish') and text()='Publish']"
EMPLOYER_TAX_INFO_MENU_ICON_BY_NAME = "//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'row cursor-pt')]//child::span[contains(@class, 'icon-menu')]"
EMPLOYER_TAX_INFO_DELETE_ICON = "(//*[@data-type='delete']//*[contains(@class,  'icon-delete2')])[last()]"
EMPLOYER_TAX_INFO_SEARCH_EMPLOYER_TEXTBOX = "//*[@placeholder='Search employer']"
EMPLOYER_TAX_INFO_CONFIRM_DELETE_BUTTON = "(//*[contains(@class, 'ok-btn') and text()='Delete'])[last()]"
EMPLOYER_TAX_INFO_SUCCESS_MESSAGE = "//*[contains(@class, 'icon-success') and contains(text(), '{}')]"

# ADD EMPLOYER MODAL
EMPLOYER_TAX_INFO_ADD_NEW_EMPLOYER_BUTTON = "//*[contains(@class, 'add-new-btn') and text()='Add New Employer']"
EMPLOYER_TAX_INFO_EMPLOYER_NAME_TEXTBOX = "//input[@id='id_employer_name']"
EMPLOYER_TAX_INFO_FULL_NAME_TEXTBOX = "//input[@id='id_person_name']"
EMPLOYER_TAX_INFO_PHONE_NUMBER_TEXTBOX = "//input[@id='id_telephone_number']"
EMPLOYER_TAX_INFO_STATE_SELECT = "(//div[contains(@class, 'address-info')]//select)[last()]"
EMPLOYER_TAX_INFO_FEI_NUMBER_TEXTBOX = "//input[@id='id_FEI_number']"
EMPLOYER_TAX_INFO_STATE_TAX_TEXTBOX = "//input[@id='id_state_tax']"
EMPLOYER_TAX_INFO_STREET_ADDRESS_TEXTBOX = "//input[@placeholder='Street address']"
EMPLOYER_TAX_INFO_SUITE_ROOM_TEXTBOX = "//input[@placeholder='Apt, Suite, Room']"
EMPLOYER_TAX_INFO_CITY_TEXTBOX = "//input[@placeholder='City']"
EMPLOYER_TAX_INFO_ZIPCODE_TEXTBOX = "//*[@placeholder='ZIP Code']"
EMPLOYER_TAX_INFO_STATE_DROPDOWN = "//*[contains(@class, 'controls state')]//select"
ADD_EMPLOYER_MODAL_CANCEL_BUTTON = "(//*[contains(@class, 'btn-default')]//span[text()='Cancel'])[last()]"
ADD_EMPLOYER_MODAL_SAVE_BUTTON = "(//*[contains(@class, 'btn-approve')]//span[text()='Save'])[last()]"
ADD_EMPLOYER_MODAL_ASSIGNED_LOCATION_TAB = "//div[contains(@id, 'detail-employer-tax-info')]//div[contains(text(), 'Assigned Location')]"
EMPLOYER_TAX_INFO_SEARCH_LOCATION_TEXTBOX = "//*[@placeholder='Search location']"
EMPLOYER_TAX_INFO_SEARCH_FOR_LOCATION_TEXTBOX = "//*[@placeholder='Search for location']"
EMPLOYER_TAX_INFO_LOCATION_CHECKBOX = "//*[contains(@id, 'switch') and @data-name='{}']//ancestor::div[contains(@class, 'custom-checkbox')]"
ADD_EMPLOYER_MODAL_APPLY_BUTTON = "(//*[contains(@class, 'btn-approve')]//span[text()='Apply'])[last()]"
EMPLOYER_TAX_INFO_ADD_LOCATION_BUTTON = "//*[contains(@class, 'btn-add-location') and text()='Add Location']"
