# EVENT TEMPLATES LIST
CREATE_EVENT_TEMPLATE_GROUP_BUTTON = "//button[contains(text(),'New Event Template Group')]"
EVENT_TEMPLATE_GROUP_NAME_TEXTBOX = "//input[contains(@placeholder,'Enter a name for your event template group')]"
SAVE_BUTTON_POPUP = "//button[contains(@class,'ok-btn') and contains(text(),'Save')]"
DRAFT_EVENT_TEMPLATE = "//div[contains(text(), '{}')]//following-sibling::div[contains(text(), 'Draft')]"
PUBLISHED_EVENT_TEMPLATE = "//div[contains(text(), '{}')]//following-sibling::div[contains(text(), 'Published')]"
EVENT_TEMPLATE_SETTINGS_ICON = "//div[contains(@class, 'action-setting')]//i[contains(@class, 'icon')]"
EVENT_TEMPLATE_GROUP_NAME_LABEL = "//*[contains(@data-testid, 'event_template_groups_lbl_name') and contains(text(), '{}')]"

# CREATE EVENT TEMPLATE
CREATE_EVENT_TEMPLATE_BUTTON = "//*[contains(@data-testid, 'new_event_template')]"
TEMPLATE_BY_NAME = "//*[contains(@class,'templates')]//div[contains(text(),'{}')]"
PUBLIC_TEMPLATE_NAME_TEXTBOX = "//*[contains(@data-testid, 'event_builder_input_public_event_name')]"
INTERNAL_EVENT_NAME_CHECKBOX = "//input[contains(@class, 'cbx-input')]"
VENUE_LOCATION_TEXTBOX = "id:id-venue-location-selectized"
VENUE_NAME_TEXTBOX = "id:id-location-title"
EVENT_TEMPLATE_VENUE_DROPDOWN = "id:id_event_venue"
PUBLISH_EVENT_TEMPLATE_BUTTON = "//button[contains(@class,'btn-publish')]"
ICON_MENU_BY_TEMPLATE_NAME = "//div[contains(text(),'{}')]/ancestor::div/div[contains(@class,'action')]"
EVENT_TEMPLATE_DELETE_ICON = "(//*[contains(@class,'icon-delete')])[last()]"
EVENT_TEMPLATE_DUPLICATE_ICON = "(//*[contains(@class,'icon-copy')])[last()]"
EVENT_TEMPLATE_EDIT_ICON = "(//*[contains(@class,'icon-edit')])[last()]"
CONFIRM_POPUP_BUTTON = "(//button[contains(@class,'ok-btn')])[last()]"
INPUT_SELECT_EVENT_TYPE = "//*[contains(@data-testid, 'event_builder_select_event_type')]"
EVENT_TEMPLATE_INPUT_SCHOOL = "//*[contains(@data-testid, 'event_builder_select_school_id')]"
SELECT_EVENT_TYPE = "//*[contains(@class, 'el-select-dropdown')]//*[contains(text(), '{}')]"
CAMPUS_EVENT_TOGGLE = "//*[contains(@data-testid, 'event_builder_switch_is_campus_event')]"
EVENT_BUDGET_AND_EXPENSES_INPUT_DISABLE = "//div[contains(text(), '{}')]//parent::div//input[contains(@disabled, 'disabled')]"
EVENT_TEMPLATE_SELECT_OPTIONS = "//option[contains(text(), '{}')]"

# TEAM TAB
EVENT_TEMPLATE_TEAM_TEXT = "//span[contains(@class, 'ico-text') and contains(text(),'Team')]"
EVENT_TEMPLATE_INPUT_ADD_EVENT_TEAM = "//input[contains(@placeholder, 'Add Event Team Members')]"
EVENT_TEMPLATE_TEAM_MEMBERS_DROPDOWN = "//div[text()='{}' and contains(@class, 'title')]"
EVENT_TEMPLATE_ADD_TEAM_MEMBER_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Add Team Members')]"

# REGISTRATION TAB
EVENT_TEMPLATE_REGISTRATION_TEXT = "//span[contains(@class, 'ico-text') and contains(text(),'Registration')]"
EVENT_TEMPLATE_SET_TIME_TYPE_SELECT = "//div[contains(@class, 'select-time-type')]//div[contains(@class, 'selectize-control')]"
SCHEDULING_CONDITION_ADVANCED_SETTINGS = "//div[contains(text(), 'Scheduling Conditions & Advanced Settings')]"
EVENT_TEMPLATE_CONVERSATION_SELECT = "id:conversation_id-selectized"
EVENT_TEMPLATE_EVENT_CONVERSATION = "//span[contains(@class, 'item-title') and contains(text(), '{}')]"
EVENT_TEMPLATE_ADD_OUTCOME_BUTTON = "//button[contains(@class, 'btn-add-outcome')]"
EVENT_TEMPLATE_NAME_OUTCOME_INPUT = "//input[contains(@placeholder, 'Name Your Outcome')]"
EVENT_TEMPLATE_STARTING_VALUE_SELECT = "//div[contains(@class, 'condition-type-selector')]"
EVENT_TEMPLATE_ASSIGNED_LOCATION = "//div[contains(@class, 'condition-type-selector')]//span[contains(@class, 'icon-location')]"
EVENT_TEMPLATE_ASSIGNED_GROUP = "//div[contains(@class, 'condition-type-selector')]//span[contains(@class, 'icon-group')]"
EVENT_TEMPLATE_MATCHES_SELECT = "//div[contains(text(), 'Matches')]//following-sibling::div//span[contains(@class, 'selected-item')]"
EVENT_TEMPLATE_AND_STATEMENT = "//button[contains(@class, 'add-condition')]//i[contains(@class, 'icon-plus')]"
EVENT_TEMPLATE_OR_STATEMENT = "//button[contains(@class, 'or-condition')]//i[contains(@class, 'icon-plus')]"
EVENT_TEMPLATE_INPUT_DROPDOWN = "//div[contains(text(), 'Input')]//following-sibling::div//span[contains(@class, 'selected-item')]"
EVENT_TEMPLATE_INPUT_LOCATION = "//div[contains(@class, 'ai-handle') and contains(., '{}')]//div[contains(@class, 'custom-checkbox')]"
EVENT_TEMPLATE_APPLY_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Apply')]"
EVENT_TEMPLATE_CANCEL_ADD_OUTCOME_BUTTON = "(//div[contains(@class, 'modal-footer')]//button[contains(@class, 'cancel-btn')])[1]"
EVENT_TEMPLATE_OK_ADD_OUTCOME_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Add outcome')]"
EVENT_TEMPLATE_OK_SAVE_OUTCOME_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Save')]"
ICON_MENU_BY_DEFAULT_OUTCOME = "//div[contains(@class, 'outcome-item')]//*[contains(@class, 'icon-menu')]"
ICON_MENU_BY_REGISTRATION_OUTCOME = "//div[contains(@class, 'outcome-item') and contains(., '{}')]//*[contains(@class, 'icon-menu')]"
EVENT_TEMPLATE_OUTCOME_ACTION_SELECT = "//div[contains(@class, 'outcome-action-selection')]"
EVENT_TEMPLATE_DEFAULT_OUTCOME_ACTION_SELECT = "//div[contains(@class, 'outcome-action-selection')]//span[contains(text(), '{}')]"
EVENT_TEMPLATE_MESSAGE_CONTENT_BOX = "(//div[contains(@class, 'message-content-input')])[1]"
EVENT_TEMPLATE_OUTCOME_NAME_IN_LIST = "//div[contains(@class, 'outcome-content')]//div[contains(@class, 'outcome-name')]"
EVENT_TEMPLATE_OUTCOME_CONDITIONS_IN_LIST = "//div[contains(@class, 'outcome-name') and contains(text(), '{}')]//following-sibling::div[contains(@class, 'outcome-conditions')]"

# TOOLS TAB
EVENT_TEMPLATE_TOOLS_TEXT = "//span[contains(@class, 'ico-text') and contains(text(),'Tools')]"

# SCHEDULE TAB
EVENT_TEMPLATE_SCHEDULE_TEXT = "//span[contains(@class, 'ico-text') and contains(text(),'Schedule')]"
EVENT_TEMPLATE_CREATE_NEW_SESSION_BUTTON = "//button[contains(text(), 'Create New Session') and not(contains(@class, 'hidden'))]"
EVENT_TEMPLATE_CATEGORY_INFO = "//div[contains(@class, 'itv-item') and contains(., '{}')]//div[contains(@class, 'category-info')]"
EVENT_TEMPLATE_SESSION_ITEM_TITLE = "//div[contains(@class, 'itv-item')]//div[contains(@class, 'title') and contains(text(), '{}')]"
ICON_MENU_BY_SESSION_NAME = "//div[contains(@class,'session-item') and contains(.,'{}')]//span[contains(@class, 'icon-menu')]"
EVENT_TEMPLATE_CONFIRM_DELETE_SESSION_BUTTON = "//button[contains(@class,'ok-btn') and contains(text(),'Delete Session')]"
EVENT_TEMPLATE_CANCEL_DELETE_SESSION_BUTTON = "//button[contains(@class,'cancel-btn') and contains(text(),'Do nothing')]"

# SESSION SLIDE
EVENT_TEMPLATE_SESSION_NAME_TEXTBOX = "//input[contains(@placeholder,'Session name') and contains(@id, 'name')]"
EVENT_TEMPLATE_INTERVIEW_SESSION_INPUT = "//input[contains(@value,'Interview Session')]"
EVENT_TEMPLATE_INTERVIEW_TYPE_SELECT = "//select[contains(@class,'select-type')]"
EVENT_TEMPLATE_DURATION_HOURS_SELECT = "//select[contains(@id,'duration_hours')]"
EVENT_TEMPLATE_DURATION_MINUTES_SELECT = "//select[contains(@id,'duration_minutes')]"
EVENT_TEMPLATE_INTERVIEW_PER_DURATION_SELECT = "//select[contains(@id,'interviews_per_duration')]"
EVENT_TEMPLATE_ADD_INSTRUCTIONS_BUTTON = "//div[contains(@class,'btn-add-instructions')]//i[contains(@class, 'icon-plus')]"
EVENT_TEMPLATE_CANCEL_ADD_SESSION_BUTTON = "//button[contains(@class,'btn-close-itv') and contains(text(), 'Cancel')]"
EVENT_TEMPLATE_CONFIRM_ADD_SESSION_BUTTON = "//button[contains(@class,'btn-save-itv') and contains(text(), 'Create Session')]"
EVENT_TEMPLATE_UPDATE_SESSION_BUTTON = "//button[contains(@class,'btn-update-itv') and contains(text(), 'Update')]"
EVENT_TEMPLATE_SESSION_NAME = "//div[contains(@class, 'itv-item')]//div[contains(@class, 'title') and contains(text(), '{}')]"
