MODAL_CREATE_EVENT_HIRING_EVENT_TYPE_BUTTON = "//div[contains(@data-testid, 'event_selection_type_general')]"
MODAL_CREATE_EVENT_NEXT_STEP_BUTTON = "//span[contains(text(),'Next')]/parent::button"
MODAL_CREATE_EVENT_BLANK_TEMPLATE = "//div[contains(@data-testid, 'event_selection_template_0')]"
MODAL_CREATE_EVENT_CREATE_EVENT = "//button[contains(@data-testid, 'event_btn_create')]"
MODAL_CREATE_NEW_EVENT = "//span[contains(@data-testid, 'event_lbl_create')]"
MODAL_HIRING_EVENT = "//div[contains(@data-testid, 'event_selection_type_general')]"
MODAL_BUTTON_NEXT = "//div[contains(@data-testid, 'create_event_dialog')]//button[contains(@class, 'el-button el-button--primary')]"
MODAL_BUTTON_CREATE_EVENT = "//div[contains(@data-testid, 'create_event_dialog')]//span[contains(text(), 'Create Event')]"
EVENT_NAME_INPUT = "//input[contains(@data-testid, 'event_builder_input_public_event_name')]"
INTERNAL_EVENT_CHECKBOX = "//*[contains(@data-testid,'event_builder_cbx_is_same_name')]//input"
INTERNAL_EVENT_NAME_INPUT = "//input[contains(@data-testid, 'event_builder_input_internal_event_name')]"
EVENT_REPORTING_CATEGORY_DROPDOWN = "//*[contains(@data-testid, 'event_builder_select_event_type')]"
EVENT_HIRING_TYPE = "//ul[contains(@id, 'select2-id_event_type-results')]//li[contains(text(), 'Hiring Event')]"
DATE_TIME_TYPE = "//span[contains(@class, 'select2-selection select2-selection--single') and contains(@aria-labelledby, 'select2-id_occurrence_type-container')]"
BUTTON_NEXT = "//div[contains(@class, 'navigation-btn')]//button[contains(text(), 'Next')]"
SESSION_TIME_CALENDAR = "//tr[contains(@class, 'fc-minor') and not(contains(@class, 'disabled'))]/td[contains(@class,'fc-widget-content') and not(contains(@class, 'fc-time'))]"
VIRTUAL_BOOTH = "//div[contains(text(), 'Virtual Chat Booth')]"
BOOTH_DIA_SAVE_BUTTON = "//div[contains(@id, 'add-session-modal')]//button[contains(text(), 'Save')]"
CONVERSATION_CB_TYPE = "//*[contains(@data-testid,'event_builder_registration_select_conversation')]//input"
LANDING_PAGE = "//div[contains(text(), 'Event Landing Page')]"
DESCRIPTION_LADING_PAGE = "//*[contains(@data-testid,'event_editor_text')]//div[contains(@class,'ql-editor')]"
INPUT_UPLOAD_FILE = "//input[@type='file']"
SAVE_BTN_LANDING_CONFIG = "//div[contains(@id, '#engagement4')]//button[contains(text(), 'Save')]"
CONFIRM_UPLOAD_IMAGE = "//div[contains(@class, 'modal ai-modal dropzone-modal in')]//button[contains(text(), 'Confirm')]"
VENUE_TYPE_MODAL = "//span[contains(@data-testid, 'create_event_lbl_event_venue_type')]"
SCHEDULE_AVAILABLE_TIME = "(//tr[not (contains(@class, 'disabled'))]/td[contains(@class,'fc-timegrid-slot-lane')])[1]"
SCHEDULE_AVAILABLE_TIME_BLOCK_1 = "(//tr[not (contains(@class, 'disabled'))]/td[contains(@class,'fc-timegrid-slot-lane')])[1]"
SCHEDULE_AVAILABLE_TIME_BLOCK_2 = "(//tr[not (contains(@class, 'disabled'))]/td[contains(@class,'fc-timegrid-slot-lane')])[2]"
SCHEDULE_AVAILABLE_TIME_BLOCK_3 = "(//tr[not (contains(@class, 'disabled'))]/td[contains(@class,'fc-timegrid-slot-lane')])[3]"
SCHEDULE_AVAILABLE_TIME_BLOCK_WITH_DATATIME = "//tr[not (contains(@class, 'disabled'))]/td[contains(@class,'fc-timegrid-slot-lane') and contains(@data-time, '{}')]"
EVENT_SESSION_CREATED = "//div[contains(text(), 'Event Session')]"
NEXT_BUTTON_EVENT = "//button[@data-testid='event_builder_btn_next']"
SAVE_BOOTH_NAME = "//div[contains(@class, 'modal-footer flex-end')]//button[contains(text(), 'Save')]"
ADD_IMAGE_CONFIRM_BUTTON = "//button[contains(@class,'primary')]//span[contains(text(), 'Confirm')]"
PREVIEW_BACKGROUND = "//*[@id='file-upload']//div//img"
SAVE_LANDING_PAGE = "//button[@data-testid='event_tool_btn_save']"
ICON_SETTING_EVENT_HOME = "//i[contains(@class, 'icon icon-settings')]"
UPLOAD_IMAGE = "//span[contains(text(), 'Upload Image')]"
SCHEDULE_TAB = "//span[contains(text(),'Schedule')]"
INCLUDES_CREATE_A_CUSTOM_SCHEDULE = "//span[contains(text(), 'Create a custom schedule that your event team and scheduled')]"
CREATE_A_MOBILE_MESSAGE = "//p[contains(text(), 'Create a mobile-first experience for virtual')]"
EVENT_CREATION_TYPE = "//div[contains(@data-testid, 'event_selection_template_0')]//p[2]"
EVENT_TEMPLATE_NAME = "//div[contains(@data-testid, 'event_selection_template_0')]//p[1]"
EVENT_TEMPLATE_NAME_PUBLISHED = "//div[contains(@data-testid, 'event_selection_template')]//p[contains(text(), '{}')]"
EVENT_SELECTION_TEMPLATE_SEARCH = "//div[contains(@data-testid, 'event_selection_template_ipt_search')]//input"
EVENT_TEMPLATE_MODAL_CREATE_EVENT = "//*[contains(text(), 'Event Templates')]"
CREATE_VIRTUAL_EVENT_SESSIONS = "//p[contains(text(), 'Create virtual event sessions that candidates can be registered for.')]"
CREATE_VIRTUAL_CHAT_BOOTHS = "//p[contains(text(), 'Create virtual chat booths to chat virtually with all registered candidates at one time.')]"
CREATE_EITHER_IN_PERSON = "//p[contains(text(), 'Create either in-person')]"
CREATE_TIME_SLOTS_FOR_EITHER = "//p[contains(text(), 'Create time slots for either ')]"
INCLUDE_TIE_A_REGISTRATION = "//span[contains(text(), 'Tie a registration conversation to your event that allows')]"
EVENT_TYPE_MODAL = "//span[contains(@data-testid, 'create_event_lbl_event_type')]"
CHOOSE_YOUR_EVENT_TYPE = "//span[contains(@data-testid, 'create_event_lbl_event_type')]"
HIRING_EVENT_BUTTON_MODAL_CREATE_EVENT = "//div[contains(@data-testid, 'event_selection_type_general')]//*[contains(text(), 'Hiring Event')]"
EVENT_TEMPLATES_BUTTON_MODAL_CREATE_EVENT = "//ul[contains(@id, 'select2-id_event_type-results')]//li[contains(text(), 'Template')]"
NEXT_BUTTON = "//div[contains(@data-testid, 'create_event_dialog')]//button[contains(@class, 'el-button el-button--primary')]"
CREATE_EVENT_BUTTON_VENUE_TYPE_MODAL = "//span[contains(text(), 'Create Event')]/ancestor::button"
CREATE_NEW_EVENT_DETAIL_MODAL_LABEL = "//span[contains(@class, 'header-1-text text-overflow') and contains(text(), 'Create New Event')]"
DATE_CALENDAR_START = "(//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'disabled')) and text()='{}'])[1]"
DATE_CALENDAR_END = "(//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'disabled')) and not(contains(@class, 'nextMonthDay')) and text()='{}'])[last()]"
EVENT_CREATE_START_DATE_PICKER = "//div[contains(@class, 'start-date-picker')]//div[contains(@class, 'dayContainer')]//span[contains(@aria-label, '{}')]"
EVENT_CREATE_END_DATE_PICKER = "//div[contains(@class, 'end-date-picker')]//div[contains(@class, 'dayContainer')]//span[contains(@aria-label, '{}')]"
OVERVIEW_LABEL = "//div[contains(text(), 'Overview')]"
REGISTRATION_TEXT = "//span[text()='Registration']"
ICON_NEXT_DAY = "//*[contains(@data-testid,'event_builder_schedule_btn_next')]"
SESSION_TITLE = "//*[contains(@data-testid,'session_content_lbl_name') and contains(text(),'{}')]"
SESSION_TITLE_NAME_LABEl = "//*[contains(@data-testid,'session_content_lbl_name')]"
SHOW_INTERVIEW_DETAIL_ICON = "//*[contains(@id,'collapse-head') and contains(text(),'Interview Details')]"
SESSION_VENUE_DROPDOWN = "//*[contains(@data-testid,'session_detail_select_venue_type')]"
MAIN_CONTENT_EVENT_TEXT = "//main[contains(@class, 'el-main')]//div[contains(@class, 'show')]//*[contains(., '{}')]"

# CEM PAGE
ADD_NEW_CANDIDATE_BUTTON = "//div[contains(@class,'toolbar-buttons')]//following-sibling::*//i[@class='icon icon-plus']"
CONFIRM_ADD_CANDIDATE_BUTTON = "//div[@data-testid='cem_add_candidate_dialog']//span[text()='Add Candidate']"
CANDIDATE_MORE_BUTTON = "//button[@data-testid='btn_candidate_more']"
CANDIDATE_SCHEDULE_BUTTON = "//button[@data-testid='candidatemenu_btn_schedule']"
EVENT_ASSISTANT_BUTTON = "//div[@data-testid='assistant_scheduling_lbl_type' and contains(text(),'Event')]"
EVENT_ID_DROPDOWN = "//div[@data-testid='btn_show_menu']"
EVENT_ID_TEXTBOX = "//div[contains(@class,'input-search')]//input"
EVENT_NAME_FILTERED = "//li//*[contains(text(),'{}')]"
SESSION_DROPDOWN = "//div[@data-testid='assistant_scheduling_select_session']"
SESSION_NAME_ITEM = "//div[text()='vt_schedule_session_test']"
SUBMIT_SCHEDULE_BUTTON = "//button[@data-testid='scheduling_event_btn_submit']"
FIRST_CONVERSATION = "(//span[@data-testid='candidateblock_lbl_name'])[1]"
CONVERSATION_HISTORY_BUTTON = "//i[@class='el-tooltip icon icon-history1']"
CONVERSATION_HISTORY_STATUS = "(//div[@data-testid='messenger_lbl_system'])[2]"

# event modal type
ORIENT_EVENT_TYPE = "//div[contains(@data-testid, 'event_selection_type_orientation')]"
ORIENT_BUTTON_MODAL_CREATE_ORIENT = "//div[contains(@data-testid, 'event_selection_type_orientation')]//*[contains(text(), 'Orientation')]"

# EVENT CREATOR PAGE
OVERVIEW_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Overview')]"
TEAM_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Team')]"
SCHEDULE_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Schedule')]"
REGISTRATION_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Registration')]"
TOOLS_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Tools')]"
EVENT_VENUE_DROPDOWN = "//*[contains(@data-testid,'event_builder_select_event_venue')]"
VENUE_LOCATION_TEXTBOX = "//input[contains(@data-testid, 'event_builder_input_venue_location')]"
VENUE_NAME_TEXTBOX = "//input[contains(@data-testid, 'event_builder_input_location_title')]"
VENUE_LOCATION_SEARCH_RESULTS = "//span[contains(@data-testid,'event_builder_popover_location_content')]/div/div/div[contains(.,'Search Results')]/following-sibling::div"
CANDIDATE_VENUE_LOCATION_TEXTBOX = "//input[contains(@placeholder,'candidate-location-address')]"
CANDIDATE_VENUE_NAME_TEXTBOX = "//input[contains(@placeholder,'candidate-location-name')]"
EVENT_BUILDER_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid, 'event_builder_select_occurrence_type')]//input"
EVENT_SINGLE_TYPE = "//li[contains(@class,'el-select-dropdown__item')]//div[contains(text(),'Single Event')]"
EVENT_RECURRING_TYPE = "//li[contains(@class, 'select2-results__option') and contains(text(), 'Recurring')]"
EVENT_START_DATE = "//input[contains(@data-testid,'event_builder_pickr_start_date')]/following-sibling::input"
EVENT_START_DATE_VALUE = "//input[contains(@data-testid,'event_builder_pickr_start_date')]"
EVENT_START_TIME = "//*[contains(@data-testid,'event_builder_select_start_time')]"
EVENT_START_TIME_OPTION = "(//li[contains(@class,'dropdown')]//*[contains(text(),'{}')])[last()]"
EVENT_END_DATE = "//input[contains(@data-testid,'event_builder_pickr_end_date')]/following-sibling::input"
EVENT_END_TIME = "//*[contains(@data-testid,'event_builder_select_end_time')]"
EVENT_END_TIME_OPTION = "(//li[contains(@class,'dropdown')]//*[contains(text(),'{}')])[last()]"
START_DATE_NEXT_MONTH_OPTION = "(//span[contains(@class, 'nextMonthDay')])[1]"
EVENT_TIMEZONE_DROPDOWN = "//*[contains(@data-testid, 'event_builder_select_timezone')]"
EVENT_TIMEZONE_DROPDOWN_VALUE = "//*[contains(@data-testid, 'event_builder_select_timezone')]//input[@placeholder='Select']"
EVENT_TIMEZONE_DROPDOWN_OPTION = "//*[contains(@class, 'select-dropdown')]//div[contains(text(), '{}')]"
EVENT_SEARCH_TIMEZONE_TEXTBOX = "//input[contains(@placeholder, 'Find a timezone')]"
LAST_EVENT_END_TIME_VALUE = "//li[contains(@data-select2-id,'end_time')][last()]"
SAVE_SESSION_NAME = "//button[contains(@data-testid,'session_detail_btn_save')]"
CLOSE_REGISTRATION_TYPE_DROPDOWN = "//*[@data-testid='event_builder_close_regis_select_close_time_type']//div[@data-testid='btn_show_menu']"
NUMBER_OF_CANDIDATES_DROPDOWN = "//*[contains(@data-testid,'event_builder_close_regis_select_registered_type')]//div[contains(@data-testid,'btn_show_menu')]"
SPECIFIC_NUMBER_OF_CANDIDATES_TEXTBOX = "//input[contains(@placeholder,'Type number')]"
NUMBER_OF_CANDIDATES_APPLY_BTN = "//button[contains(@data-testid,'event_builder_close_regis_btn_apply_candidate_type')]"
CREATE_EVENT_BUTTON_LANDING_PAGE = "//button[contains(@data-testid,'event_builder_btn_next')]"
SCHEDULED_INTERVIEWS_LABEL = "//div[contains(text(), 'Scheduled Interviews')]"
LIVE_VIDEO_BROADCAST_LABEL = "//div[contains(text(), 'Live Video Broadcast')]"
SESSION_NAME_TEXTBOX = "//input[contains(@data-testid,'session_detail_input_name')]"
EVENT_SESSION_DATE_SELECT = "//input[contains(@data-testid,'session_detail_select_date')]"
EVENT_SESSION_DATE_OPTION_SELECT = "//ul[contains(@class, 'dropdown-menu')]//li//span[contains(text(), '{}')]"
SESSION_TEMPLATE_SELECT = "//div[contains(@data-testid,'session_detail_select_template')]"
EVENT_TEMPLATE_CREATED = "//div[contains(text(),\"{}\")]//parent::li"
SESSION_URL_TEXTBOX = "//input[contains(@data-testid,'session_detail_input_url')]"
SESSION_URL_PASS_TEXTBOX = "//input[contains(@data-testid,'session_detail_input_pass_url')]"
HIDE_URL_TOGGLE = "//div[contains(@data-testid,'session_detail_btn_hide_url')]"
USE_WEB_EX_TOGGLE = "//div[contains(@data-testid,'session_detail_btn_toggle_webEx')]"
EVENT_INTERVIEW_TYPE_DROPDOWN = "//*[contains(@data-testid,'event_builder_btn_itv_menu') or contains(@data-testid,'session_detail_select_venue_type')]"
EVENT_INTERVIEW_DROPDOWN_OPTION = "//li[contains(@class,'dropdown')]//*[contains(text(),'{}')]"
EVENT_INTERVIEW_DROPDOWN_OPTION_SELECTED = "//li[contains(@class,'dropdown')]//*[contains(text(),'{}')]/following-sibling::i[contains(@class,'icon-check')]"
CANDIDATES_PER_ITV = "//input[contains(@data-testid,'session_detail_input_candidates_per_itv')]"
INTERVIEW_DURATION_DROPDOWN = "//*[contains(@data-testid,'session_detail_lbl_itv_duration')]//ancestor::*[contains(@class, 'el-col')]//input[@placeholder='Select']"
INTERVIEW_DURATION_CUSTOM_HOUR_INPUT = "//input[contains(@role,'spinbutton') and contains(@max,'6')]"
INTERVIEW_DURATION_CUSTOM_MINUTE_INPUT = "//input[contains(@role,'spinbutton') and contains(@max,'55')]"
INTERVIEW_TIME_SLOT_DROPDOWN = "//*[contains(@data-testid,'session_detail_select_itv_per_duration')]//button"
COMMON_SPAN_INTERVIEW_TIME_SLOT = "//span[contains(text(), 'Interview Time Slot')]"
INTERVIEW_ADD_INSTRUCTIONS_BUTTON = "//button[contains(@data-testid,'session_detail_btn_add_instruction')]"
START_TIME_TXT = "//*[contains(@data-testid,'session_detail_select_start_time')]"
START_TIME_INPUT = "//*[contains(@data-testid,'session_detail_select_start_time')]//span//span"
END_TIME_TXT = "//*[contains(@data-testid,'session_detail_select_end_time')]"
END_TIME_INPUT = "//*[contains(@data-testid,'event_builder_select_end_time')]//span/span"
SESSION_DATE_PREVIEW = "//div[contains(@data-testid,'session_detail_lbl_title')]//following-sibling::div//i[contains(@class, 'icon-cal-blank')]/following-sibling::span"
SESSION_TIME_PREVIEW = "//div[contains(@data-testid,'session_detail_lbl_title')]//following-sibling::div//i[contains(@class, 'icon-time')]/following-sibling::span"
END_TIME = "//label[contains(text(), 'End Time') and contains(@for, 'id-session-end-time')]"
START_TIME = "//label[contains(text(), 'Start Time') and contains(@for, 'id-session-start-time')]"
TEAM_EVENT_MEMBER = "//input[contains(@data-testid, 'event_attendee_input_search')]"
TEAM_EVENT_MEMBER_CHECKBOX = "//*[contains(text(),'{}')]/ancestor::*[contains(@data-testid,'event_attendee_cbx_selection')]//span[contains(@class,'el-checkbox__inner')]"
ADD_TEAM_MEMBER_BUTTON = "//button[contains(@data-testid, 'event_attendee_btn_add')]"
RECURRING_RULES_TAB = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Recurring Rules')]"
SUMMARY_TAB = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Summary')]"
SAVE_BUTTON_RECURRING = "//button[contains(@data-testid, 'recurring_detail_btn_save')]"
HIDE_URL_PASSWORD = "//div[contains(@class,'hide-session')]//label[@class='toggle-btn large']"
OUTCOME_CARD = "//*[@class='outcome-name' and contains(text(),'{}')]"
SESSION_SELECTION = "//*[@class='session-selection__label']"
FIRST_SESSION = "//*[@class='custom-checkbox session-selection__dropdown-item__label']"
APPLY_SESSION_BUTTON = "//*[@class='btn btn-sm btn-primary']"
SAVE_SESSION_BUTTON = "//*[@class='form-registration-outcome']//*[@class='btn btn-primary btn-sm ok-btn']"
SAVE_EVENT_BUTTON = "//button[@data-testid='event_builder_btn_next']"
MERGE_CANDIDATE_BUTTON = "//*[text()='Merge']"
CONFIRM_SAVE_BUTTON = "//button[contains(@class,'primary')]//span[normalize-space(text())='Confirm & Save']"
UPDATE_EVENT_BUTTON = "//button[contains(@class, 'primary')]//span[contains(text(), 'Update Event')]"
UPDATE_SESSIONS_BUTTON = "//button[contains(@data-testid, 'event_builder_schedule_btn_update_session')]"
CANCEL_EVENT_BUTTON = "//button[contains(@data-testid, 'event_builder_btn_cancel')]"
CONFIRM_CANCEL_EVENT = "//button[contains(@class, 'button--danger')]//span[contains(text(), 'Confirm')]"
CANCEL_AND_SEND_BUTTON = "//button[contains(@class, 'button--primary')]//span[contains(text(), 'Cancel and Send')]"
DELETE_EVENT_BUTTON = "//button[contains(@data-testid, 'event_builder_btn_delete')]"
CONFIRM_DELETE_EVENT_BUTTON = "//button[contains(@class, 'danger')]//span[contains(text(), 'Delete event')]"
CAMPUS_TOGGLE = "//*[contains(@data-testid, 'event_builder_switch_is_campus_event')]"
SCHOOL_NAME_DROPDOWN = "//*[contains(@data-testid, 'event_builder_select_school_id')]"
DROPDOWN_OPTION = "(//li[contains(@class,'dropdown')]//*[contains(text(),'{}')])[last()]"
DROPDOWN_FIRST_OPTION = "//li[contains(@class,'select-dropdown')]//div[1]"
EVENT_OCCURRENCE_TYPE = "//li[contains(@class, 'select2-results__option') and contains(text(), '{}')]"
EVENT_CREATOR_TOOLBAR_BACK_TO_EVENTS = "//div[@id='toolbar-action']//span[@class='header-0 confirm-leave cursor-pt']"
DATE_RECURRING_RULE = "//td[contains(@class, 'fc-day-future') and contains(@data-date, '{}')]"
EDIT_RECURRING_RULES_BUTTON = "//button[contains(@data-testid,'event_builder_recurring_btn_edit')]"
START_DATE_FIRST_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_lbl_start_date')]//ancestor::div[contains(@class,'form-item')]//div[contains(@class,'default-flatpickr')]"
DATE_FIRST_OCCURRENCE = "(//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'disabled')) and not(contains(@class, 'nextMonthDay')) and text()='{}'])[1]"
START_TIME_FIRST_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_select_start_time')]"
END_DATE_FIRST_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_lbl_start_time_of_first_occurrence')]//ancestor::div[contains(@class,'form-item')]//div[contains(@class,'default-flatpickr')]"
END_DATE_FIRST_OCCURRENCE = "(//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'disabled')) and not(contains(@class, 'nextMonthDay')) and text()='{}'])[2]"
END_TIME_FIRST_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_select_end_time')]"
FREQUENCY_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_select_frequency')]//input"
END_OF_RECURRING_EVENT_DROPDOWN = "//*[contains(@data-testid,'recurring_detail_lbl_end_of_event')]//ancestor::div[contains(@class,'form-item')]//div[contains(@class,'default-flatpickr')]"
END_OF_RECURRING_EVENT = "(//span[contains(@class, 'flatpickr-day') and not(contains(@class, 'disabled')) and not(contains(@class, 'nextMonthDay')) and text()='{}'])[last()]"
EVENT_OCCURRENCE_DROPDOWN = "//*[contains(@data-testid,'event_occurrence_dropdown')]"
EVENT_OCCURRENCE_ITEM = "//li[contains(@class,'occurrence-item')]"
EVENT_OCCURRENCE_LAST_ITEM = "(//li[contains(@class,'occurrence-item')])[last()]"
EVENT_OCCURRENCE_WITH_TEXT = "//li[contains(@class,'occurrence-item')]//div[contains(text(),'{}')]"
ON_THESE_DAYS_SELECTED_VALUE = "(//label[@aria-checked='true' and contains(@data-testid, 'recurring_detail_cbx')]//span)[last()]"
SELECTED_EVENT_DAYS = "//*[contains(@class, 'has-bg-event')]"
SELECTED_EVENT_DAYS_TEXT = "//*[contains(@class, 'has-bg-event')]//*[contains(@class,'day-top')]//a"
ALL_FUTURE_OCCURRENCES_RADIO = "//*[contains(@data-testid,'event_builder_recurring_confirm_radio_all_occurrence')]//span[contains(@class,'radio__inner')]"
ONLY_THIS_OCCURRENCE_RADIO = "//*[contains(@data-testid,'event_builder_recurring_confirm_radio_only_occurrence')]//span[contains(@class,'radio__inner')]"
THIS_OCCURRENCE_AND_FUTURE_RADIO = "//*[contains(@data-testid,'event_builder_recurring_confirm_radio_following_occurrence')]//span[contains(@class,'radio__inner')]"
CUSTOM_RADIO = "//*[contains(@data-testid,'event_builder_recurring_confirm_radio_custom_occurrence')]//span[contains(@class,'radio__inner')]"
OCCURRENCES_CHECKBOX = "//*[contains(@data-testid,'event_builder_recurring_confirm_cbx_occurrence')]//input[@type='checkbox']"
SEARCH_OCCURRENCES_TEXTBOX = "//*[contains(@data-testid,'event_builder_recurring_confirm_input_search_occurrence')]//input"
CONFIRM_AND_SAVE_BUTTON = "//div[@role='dialog']//button[contains(@class,'primary')]//span[contains(text(), 'Confirm')]"
CANCEL_UPDATE_EVENT_BUTTON = "//button[@data-testid='event_builder_recurring_confirm_btn_cancel']"
START_DATE_OCCURRENCE_DROPDOWN = "//div[contains(@data-testid,'occurrence_start_input')]"
SAVE_BUTTON_EDIT_OCCURRENCE = "(//span[contains(text(),'Save')])[last()]"
CANDIDATE_CARE_TOGGLE_STATUS_ON = "//span[contains(text(), 'Candidate Care')]//following-sibling::div[contains(@class, 'is-checked') and contains(@data-testid, 'event_landing_switch_care')]"
EVENT_CANDIDATE_CARE_TOGGLE = "//div[contains(@data-testid, 'event_landing_switch_care')]"
SESSION_NAME_IN_WARNING_POPUP = "//*[contains(@data-testid,'warning_session_lbl') and contains(text(),'{}')]"
SCHEDULED_INTERVIEWS_TIMEZONE_LABEL = "//*[contains(@data-testid, 'event_builder_schedule_lbl_tz_abbr')]"
SCHEDULED_INTERVIEWS_DATETIME_LABEL = "//*[contains(@data-testid, 'event_builder_schedule_lbl_header_title')]"
SESSION_ADD_INSTRUCTIONS_TEXTBOX = "//*[contains(@data-testid, 'scheduling_input_instruction')]"
SESSION_REMOVE_INSTRUCTIONS_BUTTON = "//button[contains(@data-testid, 'scheduling_btn_add_instruction')]//following-sibling::*[contains(@class, 'icon-remove')]"
SESSION_ERROR_MESSAGE = "//*[contains(@class, 'item__error')]//span"
RECURRING_EVENT_CONFIRM_AND_SAVE_BUTTON = "//button[contains(@data-testid, 'event_builder_recurring_confirm_btn_confirm')]"

# EVENT_PLANING
CAMPUS_CARE_TOGGLE = "//div[contains(@data-testid, 'event_builder_switch_is_campus_event')]"
EVENT_PLANING_LABEL = "//div[contains(@data-testid, 'event_builder_tab_6')]"
INPUT_ACTUAL_PRICE_DISABLED = "//input[contains(@data-testid, 'budget_item_ipt_actual_price') and contains(@disabled, 'disabled')]"
INPUT_ACTUAL_PRICE = "(//input[contains(@data-testid, 'budget_item_ipt_actual_price') and not(contains(@disabled, 'disabled'))])[1]"
INPUT_ACTUAL_PRICE_1 = "(//input[contains(@data-testid, 'budget_item_ipt_actual_price') and not(contains(@disabled, 'disabled'))])[2]"
INPUT_PLANNED_PRICE = "(//input[contains(@data-testid, 'budget_item_ipt_planned_price') and not(contains(@disabled, 'disabled'))])[1]"
INPUT_PLANNED_PRICE_1 = "(//input[contains(@data-testid, 'budget_item_ipt_planned_price') and not(contains(@disabled, 'disabled'))])[2]"
INPUT_PLANNED_PRICE_DISABLED = "//input[contains(@data-testid, 'budget_item_ipt_planned_price') and (contains(@disabled, 'disabled'))]"
INPUT_SELECT_SCHOOL_NAME = "//input[contains(@placeholder, 'Select school name')]"
INPUT_ADD_EVENT_TEAM = "//input[contains(@placeholder, 'Add Event Team Members')]"
TOTAL_SUM_ACTUAL_PRICE = "//div[contains(@data-testid, 'final_expenses_item_actual')]//div[contains(text(), '{}')]"
INPUT_LINE_ITEM_NAME = "//input[contains(@data-testid, 'budget_item_ipt_name')]"
TOTAL_SUM_PLANNED_PRICE = "//div[contains(@data-testid, 'final_expenses_item_planned')]//div[contains(text(), '{}')]"
FINAL_EXPENSES_WIDGET_MODAL = "//div[contains(@data-testid, 'final_expenses_widget_drawer')]"
CLOSE_FINAL_EXPENSES_WIDGET_MODAL = "//header[contains(@class, 'el-drawer')]//button//i[contains(@class, 'el-icon-close')]"
ICON_REORDER_LINE_ITEM = "(//i[contains(@class, 'icon icon-reorder')])[1]"
ICON_REORDER_LINE_ITEM_2 = "(//i[contains(@class, 'icon icon-reorder')])[2]"
INCOMPLETE_FINALIZING_STATUS = "//div[contains(text(), 'Event Budget & Expenses')]//ancestor::div[contains(@class, 'el-card__body')]//span[text()='Incomplete']"
INPUT_SEARCH_BUDGET_TYPE = "//input[contains(@placeholder,  'Search for budget type')]"

# CAMPUS
INPUT_CAMPUS_NAME = "//input[contains(@data-testid, 'event_builder_input_internal_event_name')]"
ACTIVE_DETAILS_LABEL = "//div[contains(@data-testid, 'event_builder_tab_0')]"
ACTIVE_PLANING_LABEL = "//div[contains(@data-testid, 'event_builder_tab_2')]"
EVENT_TOOLS_TEXT = "//div[contains(@data-testid, 'event_builder_tab_4')]"
MY_ACTIVE_LABEL = "//div[contains(@data-testid, 'event_builder_tab_1')]"
FINALIZE_EXPENSES_BUTTON = "//a[contains(@data-testid, 'budget_widget_finalize_expenses')]"
ATTENDEE_ON_DROPDOWN = "//div[contains(@data-testid, 'event_attendee_lbl_title') and contains(text(), '{}')]"
SUBMIT_APPROVAL_BUTTON = "//button[contains(@data-testid, 'approval_status_btn_submit')]"
CONFIRM_BUDGET_NEVER_MIND_BUTTON = "//button[contains(@data-testid, 'confirm_budget_nevermind')]"
FINAL_EXPENSES_NEVER_MIND_BUTTON = "//button[contains(@data-testid, 'final_expenses_btn_never_mind')]"
DENY_BUTTON = "//button[contains(@data-testid, 'approval_status_btn_deny')]"
FINALIZE_EXPENSES_SUBMIT_BUTTON = "//button[contains(@data-testid, 'final_expenses_btn_submit')]"
FINALIZE_EXPENSES_SUBMIT_DISABLED_BUTTON = "//button[contains(@data-testid, 'final_expenses_btn_submit') and contains(@class, 'is-disabled')]"
APPROVAL_BUTTON = "//button[contains(@data-testid, 'approval_status_btn_approve')]"
CONFIRM_BUDGET_SUBMIT_BUTTON = "//button[contains(@data-testid, 'confirm_budget_submid_final')]"
BUDGET_TYPE_DROPDOWN_ADVERTISING = "//div[contains(@data-testid, 'budget_types_dropdown0')]"
SUCCESS_CRITERIA_ENGAGEMENT_GOAL="//input[@data-testid='event_builder_planning_input_engagement_goal']"
SUCCESS_CRITERIA_SCHEDULED_INTERVIEW_GOAL="//input[@data-testid='event_builder_planning_input_scheduled_interviews_goal']"
CONFIRM_APPROVAL_BUTTON = "//button/span[contains(text(), 'Confirm')]"
INPUT_SEARCH_CAMPUS_BUTTON = "//div[contains(@data-testid, 'campus_header_ipt_search')]//input"
EXPENSES_VALUE = "//td[contains(@class, 'el-table__cell')]/div[contains(text(),'{}')]"
DELETE_ITEM_EXPENSES_VALUE = "//div//span[contains(@data-testid, 'budget_item_btn_delete')]"
CONFIRM_DELETE_EXPENSES_VALUE = "//button//span[contains(text(), 'Delete Item')]"
CAMPUS_ACTIVITY_BUTTON_MODAL_CREATE_CAMPUS = "//div[contains(@data-testid, 'event_selection_type_activity')]//*[contains(text(), 'Campus Activity')]"
EVENT_ACTIVITY_DASHBOARD_VIEW_APPROVAL_FLOW_BUTTON = "//*[@data-testid='round_box_lbl_title']"
EVENT_ACTIVITY_DASHBOARD_APPROVAL_FLOW_HISTORY_BUTTON = "//*[@id='tab-history']"
EVENT_ACTIVITY_DASHBOARD_APPROVAL_FLOW_MODAL_CLOSE_BUTTON = "//*[contains(@class,'el-icon-close')]"
EVENT_ACTIVITY_DASHBOARD_CONFIRM_DENY_BUTTON = "//div[contains(@class,'el-dialog__footer')]//*[contains(text(),'Deny and Send')]"
EVENT_ACTIVITY_DASHBOARD_REMOVE_APPROVAL_BUTTON = "//*[@data-testid='approval_status_btn_remove']"
EVENT_ACTIVITY_UPCOMING_DELETE_BUTTON = "//*[@class='el-dropdown-menu__item']//*[contains(text(), 'Delete Activity')]"
EVENT_ACTIVITY_UPCOMING_DELETE_CONFIRM_BUTTON = "//button[contains(normalize-space(), 'Delete activity')]"
CAMPUS_APPROVAL_STATUS = "(//*[@data-testid='approval_status_lbl_status'][contains(text(),'{}')])[last()]"
CAMPUS_EVENT_NAME = "//*[@data-testid='event_card_lbl_name']//*[contains(text(),'{}')]"
CAMPUS_SUBMIT_APPROVAL_BUTTON = "//button[@data-testid='approval_status_btn_submit']"
CAMPUS_CONFIRM_SEND_APPROVAL_BUTTON = "//button[contains(@class,'el-button el-button--default')]//following::span[contains(text(),'Confirm')]"
CAMPUS_TURN_BACK_EVENT_ICON = "//*[contains(@class,'icon-arrow-left')]"
CAMPUS_VIEW_APPROVAL_FLOW_BUTTON = "//*[contains(@data-testid,'round_box_lbl_title')]"
CAMPUS_VIEW_APPROVAL_FLOW_USER_POSITION_TEXT = "//div[contains(text(),'{}')]//parent::div//*[contains(text(),'{}')]"
CAMPUS_VIEW_APPROVAL_FLOW_CLOSE_MODAL_ICON = "//*[contains(@class,'el-dialog__close el-icon el-icon-close')]"
CAMPUS_SETTING_ICON = "//*[@id='content-header']//i[contains(@aria-haspopup,'list')]"
CAMPUS_DELETE_CONFIRM_ACTIVITY_BUTTON = "//button[contains(@class,'el-button el-button--default el-button--danger')]//span[contains(text(),'Delete activity')]"
CAMPUS_VIEW_APPROVAL_HISTORY_STATUS_TITLE = "//div[contains(text(),'{}')]//parent::div//following-sibling::div//div[contains(text(),'{}')]"
EVENT_ACTIVITY_DASHBOARD_DIALOG="//*[contains(@class, 'el-dialog') and @role='dialog']"
EVENT_ACTIVITY_DASHBOARD_CONFIRM_AND_SEND="//div[contains(@class,'el-dialog__footer')]//*[contains(text(),'Confirm and Send')]"

# EVENT CREATOR PAGE / Unsaved Changes popup
EVENT_CREATOR_PAGE_DISCARD_BUTTON = "//div[@class='el-message-box ol-confirm msg-box-confirm']//button[@class='el-button el-button--default']"

# EVENT CREATOR PAGE - REGISTRATION
OUTCOME_ORDER_2 = "//span[@class='order' and text()=2]"
SCHEDULE_CONDITION = "//div[@class='scheduling-conditions-content']//div[@class='tool-content']"
ADD_SCHEDULE_CONDITION = "//button[@class='btn btn-primary btn-sm btn-add-scheduling-condition']"
SCHEDULE_RULE_CONDITION = "//div[@class='form-group col-md-3 col-xs-3']//li//span[text()='Select Rule']"
ASSIGNED_LOCATION_RULE = "//div[@class='custom-select__dropdown-item__label' and contains(text(),'Assigned Location')]"
MATCHES_CONDITION = "//div[@class='form-group col-md-2 col-xs-2']//span[text()='Select']"
MATCHES_IS_NOT = "//div[contains(text(),'Is not') and @class='custom-select__dropdown-item__label']"
MATCHES_IS = "(//div[@role='tooltip']//div[contains(text(),'Is')])[1]"
MATCHES_NO = "(//div[@role='tooltip']//div[contains(text(),'No')])[3]"
LOCATION_SELECTION = "//div[@id='locationLabel_0_0']"
LOCATION_CHECKBOX = "//*[contains(text(),'{}')]//parent::label//parent::div//self::div[@class='custom-checkbox']//span"
APPLY_LOCATION_BUTTON = "//div[@id='location-content-0_0']//button[contains(@class,'ok-btn')]"
SAVE_SCHEDULE_CONDITION_BUTTON = "//div[@id='add-scheduling-condition-modal']//div[@class='modal-footer']//button[contains(@class,'ok-btn')]"
EVENT_ADD_OUTCOME_BUTTON = "//button[contains(@data-testid,'event_builder_outcome_btn_add_outcome')]"
OUTCOME_ACTION_ORDER_2 = "//span[@class='order' and text()=2]//parent::div//following-sibling::div[@class='outcome-actions']"
DELETE_OUTCOME_BUTTON = "//button[contains(@data-testid,'event_builder_drawer_btn_delete')]"
CONFIRM_DELETE_OUTCOME_BUTTON = "(//button[contains(@class,'danger')]//span[contains(text(),'Delete Outcome')])[last()]"
REGISTRATION_CONVERSATION_NAME = "//span[@class='item-title' and text()='{}']"
EVENT_OCCURRENCE_MENU_ITEM = "//*[contains(@data-testid, 'occurrence_dropdown')]//*[contains(@class,'icon-menu')]"
EVENT_OCCURRENCE_LAST_MENU_ITEM = "(//*[contains(@data-testid, 'occurrence_dropdown')]//*[contains(@class,'icon-menu')])[last()]"
EDIT_EVENT_OCCURRENCE_ICON = "(//*[contains(@data-testid, 'edit_occurrence')])[last()]"
DELETE_EVENT_OCCURRENCE_ICON = "(//*[contains(@data-testid, 'delete_occurrence')])[last()]"
DELETE_OUTCOME_DIALOG_TITLE = "//*[contains(@class,'title')]//span[contains(text(),'Delete Outcome')]"
SCHEDULE_CONDITION_ADVANCED_SETTING_BUTTON = "//*[contains(@data-testid,'event_builder_registration_btn_scheduling')]"
SCHEDULE_MAXIMUM_CANDIDATE_DROPDOWN = "//*[contains(@data-testid,'dropdown_schedule_maximum_candidates')]"
SCHEDULE_ADVANCED_SETTING_BUTTON_SAVE = "//*[contains(@data-testid,'event_builder_scheduling_btn_save')]"


## EVENT CREATOR PAGE - REGISTRATION/ADD OUTCOME
NAME_YOUR_OUTCOME_TEXTBOX = "//*[contains(@data-testid,'event_builder_outcome_drawer_input_name_outcome')]//input"
STARTING_VALUE_DROPDOWN = "//*[contains(@data-testid,'event_builder_outcome_drawer_select_outcome_condition_type')]"
STARTING_VALUE_DROPDOWN_2 = "(//*[contains(@data-testid,'event_builder_outcome_drawer_select_outcome_condition_type')])[2]//*[@data-testid='btn_show_menu']"
ASSIGNED_LOCATION_VALUE = "//span[@class='icon icon-location']"
MATCHES_VALUE_DROPDOWN = "//*[contains(@data-testid,'event_builder_outcome_drawer_select_outcome_condition_match')]"
MATCHES_VALUE_DROPDOWN_2 = "(//*[contains(@data-testid,'event_builder_outcome_drawer_select_outcome_condition_match')])[2]//*[@data-testid='btn_show_menu']"
MATCHES_IS_ANY = "//div[contains(text(),'Is Any Of') and @class='custom-select__dropdown-item__label']"
INPUT_DROPDOWN = "//*[contains(@data-testid,'dropdown_outcome_condition')]//*[contains(@data-testid,'btn_show_menu')]"
INPUT_DROPDOWN_2 = "(//*[contains(@data-testid,'dropdown_outcome_condition')]//*[contains(@data-testid,'btn_show_menu')])[2]"
INPUT_VALUE = "//label[@class='input-label' and contains(text(),'{}')]"
APPLY_INPUT_BUTTON = "//div[@class='location-content dropdown-menu']//button[contains(@class,'ok-btn')]"
CONFIRM_ADD_OUTCOME_BUTTON = "//button[@class='btn btn-primary btn-sm ok-btn' and contains(text(),'Add outcome')]"
OUTCOME_ACTION = "//div[@class='custom-select outcome-action-selection']//li[@class='custom-select__label']"
SAVE_OUTCOME_BUTTON = "//button[contains(@data-testid,'event_builder_drawer_btn_add')]"
ADD_OUTCOME_ACTION_DROPDOWN = "//*[contains(@data-testid,'event_builder_outcome_action_select_action')]//*[@data-testid='btn_show_menu']"
CHECK_ICON_BY_DROPDOWN_OPTION = "//*[contains(text(),'{}')]/parent::div/parent::*//span[contains(@class,'icon-check2 ')]"
OUTCOME_ACTION_MESSAGE_TEXTAREA = "//*[contains(@data-testid,'event_builder_outcome_action_input_message')]//div[@contenteditable='true']"
SESSION_CANDIDATE_CAN_SCHEDULE_DROPDOWN = "//*[contains(@data-testid,'event_builder_outcome_action_select_interview_session')]"
SESSION_NAME_CHECKBOX = "//*[contains(text(),'{}')]//parent::div//parent::span//preceding-sibling::span[contains(@class,'checkbox')]"
SESSION_NAME_CHECKBOX_LAST = "(//*[contains(text(),'{}')]//parent::div//parent::span//preceding-sibling::span[contains(@class,'checkbox')])[last()]"
SESSION_TO_SCHEDULE_APPLY_BUTTON = "//button[contains(@class,'el-button--primary el-button--small')]"
ADD_REGISTRATION_OUTCOME_LABEL = "//*[@id='el-drawer__title']//span[contains(text(),'Add Registration Outcome')]"
EDIT_OUTCOME_NAME_ICON = "//*[contains(@data-testid,'event_builder_outcome_drawer_input_name_outcome')]//*[contains(@class,'icon-edit')]"
ADD_OUTCOME_AND_BUTTON = "//*[contains(@data-testid,'event_builder_outcome_drawer_btn_and')]"
ADD_OUTCOME_OR_BUTTON = "//*[contains(@data-testid,'event_builder_outcome_drawer_btn_or')]"
ADD_OUTCOME_DROPDOWN_OPTION = "(//*[contains(text(),'{}')])[last()]"
SEARCH_GROUP_TEXTBOX = "//input[@placeholder='Search Groups']"
SEARCH_LOCATION_TEXTBOX = "//input[@placeholder='Search for location']"
NUMERIC_INPUT_TEXTBOX = "//*[contains(@data-testid,'event_builder_outcome_drawer_select_outcome_condition_type')]//parent::div//following-sibling::div//input[@type='number']"
UNIT_INPUT_DROPDOWN = "//input[@type='number']//parent::div/parent::div//following-sibling::*//*[contains(@data-testid,'btn_show_menu')]"
INPUT_LOCATION_CHECKBOX_BY_NAME = "//*[contains(text(),'{}')]//ancestor::*//span[contains(@class,'checkbox__inner')]"
DELETE_CONDITION_ICON = "//i[contains(@class,'icon-delete')]"
OR_TEXT_DIVIDER = "//div[contains(@class,'divider')]//span[contains(text(),'or')]"
OUTCOME_MENU_BY_NAME = "//*[contains(text(),'{}')]/parent::div/parent::div//span[contains(@class,'icon-menu')]"
EDIT_OUTCOME_ICON = "(//*[contains(@data-testid,'event_builder_outcome_dropdown_item_edit_outcome')]//i)[last()]"
DUPLICATE_OUTCOME_ICON = "(//*[contains(@data-testid,'event_builder_outcome_dropdown_item_duplicate_outcome')]//i)[last()]"
DELETE_OUTCOME_ICON = "(//*[contains(@data-testid,'event_builder_outcome_dropdown_item_delete_outcome')]//i)[last()]"
ACTION_LANGUAGE_DROPDOWN = "//*[contains(@data-testid,'event_builder_outcome_action_select_language')]//input"
DIALOG_MESSAGE_CONTENT = "//*[contains(@class,'message-box__message')]"
CONFIRM_DIALOG_BUTTON = "(//*[contains(@class,'el-button--primary')]//span[contains(text(),'Confirm')])[last()]"
CANCEL_DIALOG_BUTTON = "(//button[contains(@class,'default')]//span[contains(text(),'Cancel')])[last()]"

# EVENT CREATOR PAGE - JOB
JOB_REQUISITIONS_WIDGET = "//div[@id='open-job-drawer']"
JOBS_STEP_LABEL = "//*[contains(@data-testid, 'event_builder_tab')]//span[contains(text(),'Jobs')]"
ADD_JOB_BUTTON = "//button[contains(@data-testid,'event_builder_job_btn_add')]"
EVENT_JOB_CHECKBOX = "//span[contains(text(),'{}')]//ancestor::tr//label//span[contains(@class,'checkbox__inner')]"
FIRST_JOB_CHECKBOX = "(//tr//span[contains(@class,'checkbox__input')])[2]"
CONFIRM_ADD_JOB_BUTTON = "//span[contains(text(),'Add Requisitions to Event')]//ancestor::button"
CANCEL_ADD_JOB_BUTTON = "(//button[contains(@class,'default')]//span[text()='Cancel'])[last()]"
EVENT_CREATOR_JOB_REMOVE_ICON = "//button[contains(@data-testid,'event_builder_job_btn_delete_job')]"
EVENT_JOB_SEARCH_JOB_TEXTBOX = "(//*[contains(@class, 'body')]//input[contains(@placeholder, 'Search')])[last()]"
MANAGE_ADD_JOB_BUTTON = "//button[contains(@data-testid,'event_builder_job_btn_manage_add')]"
JOB_REQUISITION_ITEM = "//td[contains(@class, 'el-table') and  not(contains(@class, 'is-hidden'))]//span[contains(text(),'{}')]"
ICON_DELETE_JOB_REQUISITION = "//span[contains(text(),'{}')]//ancestor::td[contains(@class, 'el-table') and (contains(@class, 'is-hidden'))]//following-sibling::td//i[contains(@class, 'icon-delete')]"
EVENT_JOB_IN_PROGRESS_LABEL = "//div[contains(text(), '{}')]/ancestor::div[contains(@class, 'el-card')]//span[contains(text(), 'In Progress')]"
EVENT_ITEM_JOB_MY_APPLICATION = "//div[contains(@data-testid, 'event_lbl_my_job')]//following-sibling::div[contains(@class, 'el-card')]//div[contains(text(), '{}')]"
EVENT_ITEM_JOB_ALL_JOB = "//div[contains(@data-testid, 'event_lbl_all_job')]//following-sibling::div[contains(@class, 'el-card')]//div[contains(text(), '{}')]"

# EVENT CREATOR PAGE - JOB / Add Open job requisitions
EVENT_ADD_JOB_REQ_WIDGET_SEARCH_TEXT_BOX = "//div[@class='job-list-container']//input[@placeholder='Search']"
EVENT_ADD_JOB_REQ_SHOW_TYPE_TEXT_BOX = "(//input[contains(@placeholder, 'Select')])[last()]"
EVENT_ADD_JOB_REQ_SHOW_TYPE_OPTION = "(//li[contains(@class, 'el-select-dropdown')]//span[contains(text(), '{}')])[last()]"

# EVENT CREATOR PAGE - JOB / Remove Job from Event popup
EVENT_CREATOR_JOB_REMOVE_POPUP = "//span[contains(text(), 'Remove Job from Event')]//ancestor::div[contains(@role, 'dialog')]"
EVENT_CREATOR_JOB_REMOVE_CANCEL_BUTTON = "//span[contains(text(), 'Remove Job from Event')]//ancestor::div[contains(@role, 'dialog')]//span[contains(text(), 'Cancel')]"
EVENT_CREATOR_JOB_REMOVE_CONFIRM_BUTTON = "(//span[contains(text(), 'Remove Job from Event')]//ancestor::div[contains(@role, 'dialog')]//span[.='Remove Job'])[last()]"

# EVENT CREATOR PAGE - Team Step
EVENT_CREATOR_TEAM_ROLE_DROPDOWN = "(//div[@data-testid='event_attendee_lbl_title' and contains(text(),'{}')]//parent::div/parent::div/parent::div/parent::div/parent::div//div[@data-testid='event_attendee_select_role'])[last()]"
EVENT_CREATOR_TEAM_ROLE_DROPDOWN_VALUE = "//li[contains(@class,'el-select-dropdown__item')]//div[contains(text(),'{}')]"
EVENT_CREATOR_TEAM_ROLE_REMOVE_ICON = "//*[contains(text(), '{}')]//parent::*//parent::*//parent::*//parent::*//i[@data-testid='event_attendee_btn_remove']"
EVENT_CREATOR_TEAM_ROLE_CONFIRM_REMOVE_BUTTON = "//button[contains(@class, 'el-button--danger')]//span[contains(text(), 'Remove')]"

# EVENT CREATOR PAGE - Tools Step
EVENT_RATINGS_CONFIGURED_NUMBER = "//*[contains(text(),'Event Ratings')]//parent::div//following-sibling::div[@data-testid='event_tool_card_configured']"

# EVENT CREATOR PAGE - Tools Step / Event Ratings
EVENT_RATINGS_TRIGGER_TITLE = "//div[contains(@class,'el-collapse')]//span[contains(text(),'{}')]"
EVENT_RATINGS_AUDIENCE_TAB = "//div[contains(@class,'el-tabs__item is-top') and text()='{}']"
EVENT_RATINGS_ADD_TRIGGER_TEXT = "//div[@class='el-tabs__content']//div[@role='tabpanel' and not(contains(@style,'display: none;'))]//div[@data-testid='event_rating_btn_add']"
EVENT_RATINGS_SAVE_BUTTON = "//button[@data-testid='event_tool_btn_save']"
EVENT_RATINGS_CANCEL_BUTTON = "//button[@data-testid='event_tool_btn_cancel']"
EVENT_RATINGS_TRIGGER_COLLAPSE_ACTIVE = "//*[contains(text(),'{}')]//ancestor::div[contains(@class,'el-collapse-item__header') and contains(@class,'is-active')]"
EVENT_RATINGS_TRIGGER_COLLAPSE_NOT_ACTIVE = "//*[contains(text(),'{}')]//ancestor::div[contains(@class,'el-collapse-item__header') and not(contains(@class,'is-active'))]"

# EVENT CREATOR PAGE - Tools Step / Event Ratings / Select Touchpoint popup
EVENT_RATINGS_TOUCHPOINT_SELECT_DROPDOWN = "//div[@data-testid='event_rating_select_touchpoint']"
EVENT_RATINGS_TOUCHPOINT_SELECT_VALUE = "//li[@data-testid='event_rating_option_touchpoint' and contains(text(),'{}')]"
EVENT_RATINGS_TOUCHPOINT_SELECT_SAVE_BUTTON = "(//button[@data-testid='event_rating_add_touchpoint'])[last()]"
EVENT_RATINGS_TOUCHPOINT_SELECT_CANCEL_BUTTON = "(//button[@data-testid='event_rating_cancel_touchpoint'])[last()]"

# EVENT CREATOR PAGE - Tools Step / Event Ratings / Trigger detail
EVENT_RATINGS_TRIGGER_DELIVERY_DROPDOWN = "//div[contains(@class,'el-collapse-item is-active')]//div[@data-testid='event_rating_select_delivery']"
EVENT_RATINGS_TRIGGER_RATING_DROPDOWN = "//div[contains(@class,'el-collapse-item is-active')]//div[@data-testid='event_rating_select_flow']"
EVENT_RATINGS_TRIGGER_DROPDOWN_VALUE = "(//div[not(contains(@style,'display: none'))]//li[contains(@class,'el-select-dropdown__item') and contains(text(),'{}')])[last()]"
EVENT_RATINGS_TRIGGER_SAVE_BUTTON = "(//button[@data-testid='event_rating_save_rating'])[last()]"
EVENT_RATINGS_TRIGGER_CANCEL_BUTTON = "(//button[@data-testid='event_rating_cancel_rating'])[last()]"
EVENT_RATINGS_TRIGGER_DELETE_BUTTON = "(//button[@data-testid='event_rating_delete_rating'])[last()]"
EVENT_RATINGS_VIEW_RATING_HYPERLINK = "//div[contains(@class,'el-collapse-item is-active')]//i[@class='icon icon-external-link1']"
ALERT_RECOMMEND_EVENT_LANDING_PAGE = "//*[contains(text(), 'We recommend customizing the event landing page')]"
EVENT_LANDING_PAGE_LINKS_SECTION = "//*[contains(text(), 'You can find your site here')]"

# EVENT CREATOR PAGE - Tools Step / Event Ratings / Trigger detail / Confirm Removal of Event Rating Trigger popup
EVENT_RATINGS_CONFIRM_REMOVE_TRIGGER_POPUP_CONFIRM_BUTTON = "//div[@aria-label='Confirm Removal of Event Rating Trigger']//button[@class='el-button el-button--default el-button--danger']"

# EVENT CREATOR PAGE - Tools Step / Orientation Prep Documents
EVENT_ORIENTATION_PREP_DOC = "//span[contains(text(), '{}')]//ancestor::div[contains(@class, 'itv-step-attendees')]//div[contains(text(), 'Select')]"
EVENT_ORIENTATION_PREP_DOC_CANDIDATE_INPUT = "//div[contains(@data-testid, 'event_prep_select_doc')]//*[contains(@placeholder, 'Select')]"
EVENT_ORIENTATION_PREP_DOC_USER_INPUT = "(//div[contains(@data-testid, 'event_prep_select_doc')]//*[contains(@placeholder, 'Select')])[2]"
EVENT_ORIENTATION_PREP_DOC_SAVE_BUTTON = "//div[contains(@class, 'tool-header-detail')]//button[contains(text(), 'Save')]"
EVENT_ORIENTATION_PREP_DOC_CANCEL_BUTTON = "//div[contains(@class, 'tool-header-detail')]//button[contains(text(), 'Cancel')]"
EVENT_SAVE_EVENT_BUTTON = "//div[contains(@class, 'navigation-btn')]//button[contains(text(), 'Save Event')]"
EVENT_CONFIRM_AND_SAVE_BUTTON = "//button[normalize-space(text())='Confirm and Save']"
EVENT_TOOL_CARD_TITLE = "//div[contains(@data-testid, 'event_tool_card_title') and contains(text(), '{}')]"

# GENERAL PAGE
SWITCH_USER_BTN = "//*[@data-testid='header_btn_switch_user']"
FULL_USER_ROLE = "//*[@data-testid='user_item_lbl_role' and contains(text(),'Full User')]"
TEAM_USER_NAME = "//*[@data-testid='user_item_lbl_name' and contains(text(),'{}')]"
LIST_USER_BY_ROLE = "//div[contains(@data-testid, 'user_item_lbl_role')]"

# EVENT DASHBOARD PAGE
DASH_BOARD_EVENT_NAME = "//div[@data-testid='event_card_lbl_name']//span[@aria-label]"
DASH_BOARD_NAVIGATION = "//*[contains(@class,'nav-text') and contains(text(),'Dashboard')]"
EVENT_DASH_BOARD_JOBS_NAVIGATION = "//*[contains(@class,'nav-text') and contains(text(),'Jobs')]"
VIRTUAL_CHAT_BOOTH_LABEL = "//div[contains(text(), 'Virtual Chat Booth')]"
RSVP_STATUS_BUTTON = "//div[@id='content-header']//i[contains(@class,'chevron-down')]"
GOING_STATUS_BUTTON = "//*[@class='icon-check2']"
NOT_GOING_STATUS_BUTTON = "//*[@class='icon-spam']"
DECLINE_INVITE_BUTTON = "//*[contains(@class,'el-button--danger')]"
EVENT_DASHBOARD_SETTING_ICON = "//i[contains(@class,'icon-settings')]"
EDIT_EVENT = "//i[contains(@class,'icon-edit')]"
CANCEL_EVENT_ICON = "//i[contains(@class,'icon-delete2')]"
CHECKIN_CANDIDATES_CARD = "//div[@data-testid='candidate_inbox_check_in_candidate']"
CLOSE_CHECKIN_BUTTON = "//button[@data-testid='check_in_btn_close']"
CONFIRM_CLOSE_CHECKIN_BUTTON = "//div[@aria-label='Close Candidate Check-In']//button[contains(@class,'primary')]"
CHECKIN_CANDIDATE_SEARCH_INPUT = "//div[contains(@data-testid, 'check_in_input_search')]//input"
CHECKIN_CANDIDATE_COUNT = "//div[contains(@data-testid, 'check_in_candidate_count')]"
CHECKIN_CANDIDATE_SHORTNAME_IN_LIST = "//div[@data-testid='check_in_info_name' and contains(text(), '{}')]//ancestor::tr//span[contains(@data-testid, 'check_in_name_short_name')]"
CHECKIN_CANDIDATE_SHORTNAME_PROFILE = "//div[@data-testid='candidateprofile_btn_avatar']//span[contains(text(), '{}')]"
CHECKIN_CANDIDATE_BY_USER_BUTTON = "//div[@data-testid='check_in_info_name' and contains(text(), '{}')]/ancestor::tr[contains(@class, 'el-table')]//span[contains(text(), 'Check-in')]"
CHECKIN_CANDIDATE_DONE_BY_USER_BUTTON = "//div[@data-testid='check_in_info_name' and contains(text(), '{}')]/ancestor::tr[contains(@class, 'el-table')]//i[contains(@class, 'icon-check2')]"
CHECKIN_CANDIDATE_CLOSE_PANEL_BUTTON = "//div[@data-testid='check_in_lbl_title']//following-sibling::button"
CHECKIN_CANDIDATE_CLOSE_BUTTON = "//button[@data-testid='check_in_btn_close']"
CHECKIN_CANDIDATE_CONFIRM_CLOSE_BUTTON = "//div[@aria-label='Close Candidate Check-In']//button[contains(@class,'primary')]"
CHECKIN_CANDIDATE_NAME_LIST = "//div[@data-testid='check_in_info_name' and contains(text(), '{}')]"
PROFILE_EVENT_TAB = "//div[@data-testid='cem_orientation_lbl_title' and contains(text(), '{}')]"
TAB_ORIENTATION_EVENT = "//div[contains(@id, 'tab-orientation')]//span[contains(text(), 'Orientation')]"
CEM_EVENT_CHECKIN_BUTTON = "(//button[contains(@data-testid, 'cem_event_btn_checkin')])[1]"
BACK_TO_CANDIDATE_BUTTON = "//div[contains(@id, 'candidate-detail-header')]//span[contains(@class, 'icon-arrow-left')]"
CEM_EVENT_COLLAPSE_ITEM_BUTTON = "//div[@data-testid='cem_event_btn_collapse_item']//div[contains(text(), '{}')]"
SCHEDULE_LABEL = "//div[contains(@class, 'nav-text') and text()='Schedule']"
EVENT_SCHEDULE_LABEL = "//div[contains(@class, 'nav-text') and text()='Event Schedule']"
EVENT_SCHEDULE_TABLE_VIEW_BUTTON = "//button[contains(@data-testid, 'event_schedule_btn_table_view')]"
EVENT_SCHEDULE_ADD_CANDIDATE_BUTTON = "//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_sechedule_btn_add_candidate']"
EVENT_SCHEDULE_ADD_INTERVIEWER_BUTTON = "//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_schedule_btn_add_interviewer']"
EVENT_SCHEDULE_INTERVIEWER_ADDED_1 = "(//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_schedule_btn_add_interviewer']//span)[1]"
EVENT_SCHEDULE_INTERVIEWER_ADDED_2 = "(//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_schedule_btn_add_interviewer']//span)[2]"
EVENT_SCHEDULE_INTERVIEWER_ADDED_3 = "(//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_schedule_btn_add_interviewer']//span)[3]"
EVENT_SCHEDULE_INTERVIEWER_COLUMN = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[4]//span"
EVENT_SCHEDULE_CHECK_IN_COLUMN = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[5]//span"
EVENT_SCHEDULE_EVENT_SESSION_NAME = "//div[contains(@class, 'fc-timegrid-event-harness')]//*[contains(text(), '{}')]"
EVENT_SCHEDULE_CHECK_IN_BUTTON = "//span[contains(text(), '{}')]//ancestor::tr//button[@data-testid='event_sechedule_btn_checkin']//span[contains(text(), 'Check-in')]"
EVENT_SCHEDULE_CHECK_IN_IS_CHECKED_BUTTON = "//span[contains(text(), '{}')]//ancestor::tr//button[contains(@data-testid, 'event_sechedule_btn_checkin')]//i[contains(@class, 'icon-check2')]"
EVENT_SCHEDULE_CALENDAR_VIEW_BUTTON = "//button[contains(@data-testid, 'event_schedule_btn_calendar_view')]"
EVENT_SCHEDULE_INTERVIEWER_ON_CARD = "//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'el-card__body')]//span[contains(text(), '{}')]"
EVENT_SCHEDULE_OPEN_INTERVIEW_TIME_ICON_MENU = "//div[contains(text(), '{}')]//parent::div//button//i[contains(@class, 'icon-menu')]"
EVENT_SCHEDULE_OPEN_INTERVIEW_TIME_DELETE_INTERVIEW_BUTTON = "//ul[contains(@x-placement, 'bottom-end')]//span[contains(text(), 'Delete Interview')]"
EVENT_SCHEDULE_OPEN_INTERVIEW_TIME_CONFIRM_DELETE_BUTTON = "//button[contains(@class, 'el-button--danger')]//span[contains(text(), 'Delete Interview')]"
EVENT_SCHEDULE_SEARCH_INPUT = "//div[contains(@data-testid, 'event_schedule_input_search')]//input"
EVENT_SCHEDULE_INTERVIEWER_NAME = "//button[@data-testid='event_schedule_btn_add_interviewer']//span[contains(text(), '{}')]"

MY_EVENT_SCHEDULE_INTERVIEWER_OPEN_SLOT = "//span[contains(@data-testid, 'event_interview_lbl_open_slot') and contains(text(), 'Open Interview Time')]"
MY_EVENT_SCHEDULE_LABEL = "//div[contains(@class, 'nav-text') and text()='My Event Schedule']"
MY_EVENT_SCHEDULE_INTERVIEW_SESSIONS = "//div[contains(text(), '{}')]//ancestor::div[contains(@data-testid, 'my_event_schedule_lbl_calendar_content')]"
MY_EVENT_SCHEDULE_CANDIDATE_NAME_ON_CARD = "//div[contains(@class, 'el-card__body')]//div[contains(text(), '{}')]"
MY_EVENT_SCHEDULE_SHORT_NAME_ON_CARD = "//div[contains(text(), '{}')]//preceding::span[@data-testid='event_interview_lbl_short_name']"
MY_EVENT_SCHEDULE_CHECK_IN_BUTTON_ON_CARD = "//div[contains(text(), '{}')]//following::button[@data-testid='event_interview_btn_check_in']"
MY_EVENT_SCHEDULE_ICON_MENU = "//*[contains(@data-testid, 'event_interview_lbl_title') and contains(text(), '{}')]//parent::div//button//i[contains(@class, 'icon icon-menu')]"
MY_EVENT_SCHEDULE_ADD_CANDIDATE = "//ul[not(contains(@style,'display: none;'))]//li[contains(@data-testid, 'event_interview_lbl_add_candidate')]//span[contains(text(), 'Add Candidate')]"
CANDIDATE_LABEL = "//div[contains(@class, 'nav-text') and text()='Candidates']"
CANDIDATE_TAB_INTERVIEWER_COLUMN = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[9]//span[contains(text(), '{}')]"
CANDIDATE_TAB_JOURNEY_STATUS = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[8]//span[contains(text(), '{}')]"
CANDIDATE_TAB_VIRTUAL_INTERVIEW_ICON = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[14]//i[contains(@class, 'icon-videocam')]"
CANDIDATE_TAB_INTERVIEW_TIME = "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[14]//span[contains(text(), '{}')]"
DASHBOARD_ASSIGN_INTERVIEWS_BUTTON = "//span[text()='Tasks']//ancestor::div//button//span[contains(text(), 'Assign Interviewers')]"
EVENT_SCHEDULE_DURATION_INFO = "(//div[contains(@data-testid, 'event_schedule_upcoming_session')]//div//span)[1]"
EVENT_DASHBOARD_ADD_JOB_BUTTON = "//button[contains(@data-testid,'header_btn_add_job')]"

# # EVENT DASHBOARD PAGE / Cancel event popup
CANCEL_EVENT_POPUP_CONFIRM_BUTTON = "//div[@class='el-message-box ol-confirm']//button[@class='el-button el-button--default el-button--danger']"
CANCEL_EVENT_POPUP_CANCEL_AND_SEND_BUTTON = "//*[contains(text(),'Cancel event')]//ancestor::div[@role='dialog']//button[contains(@class,'el-button--primary')]"


# EVENT DETAIL DASHBOARD PAGE
EVENT_LANDING_PAGE_URL = "//*[contains(text(), 'Event Landing Page')]//following-sibling::div//a"
EVENT_UPCOMING_SITE_URL = "//*[contains(text(), 'Upcoming Event Site')]//following-sibling::div//a"
EVENT_INTERVIEWS_CARD = "//*[@data-testid='feature_tile_lbl_title' and contains(text(),'Interviews')]"
VIRTUAL_TAG_PILL = "//*[@data-testid='event_card_lbl_tag']/div[contains(text(),'Virtual')]"
CHAT_TAG_PILL = "//*[@data-testid='event_card_lbl_tag']/div[contains(text(),'Chat')]"
VIEW_SCHEDULE_BTN = "//*[@class='el-button el-button--default']//span[text()='View Schedule']"
CANDIDATE_ENGAGEMENTS_CARD = "//*[contains(text(),'Candidate Engagements') and @data-testid='feature_tile_lbl_title']"
ENGAGEMENT_LANDING_CARD = "//*[contains(text(), '{}')]//ancestor::*[contains(@data-testid, 'engagement_landing')]"
ICON_EVENT_SOURCE = "//*[contains(text(), '{}')]//ancestor::*[contains(@data-testid, 'engagement_landing')]//i[contains(@class, 'icon-landing-page-source')]"
EVENT_COPY_LONG_LINKS_BUTTON = "//*[contains(text(), '{}')]//ancestor::*[contains(@data-testid, 'engagement_landing')]//button//*[text()='Copy']"

# EVENT DETAIL DASHBOARD PAGE / RATINGS CARD
EVENT_RATINGS_SENT_TEXT = "//p[@data-testid='event_rating_lbl_sent']"
EVENT_RATINGS_OVERALL_SLIDE_RIGHT_ICON = "//i[@class='icon icon-arrow-down-right']"
EVENT_RATINGS_OVERALL_SLIDE_LEFT_ICON = "//i[@class='icon icon-arrow-down-left']"

# EVENT DETAIL DASHBOARD PAGE / SCHEDULE CARD
EVENT_DASHBOARD_SCHEDULE_CARD_CONTENT = "//div[@data-testid='feature_tile_lbl_title' and contains(text(),'Schedule')]//ancestor::div[contains(@class,'el-card is-always-shadow')]//*[contains(text(),'{}')]"

# EVENT DASHBOARD PAGE / Add Candidate popup
CANDIDATE_MENU_LABEL = "//*[@class='menu']//*[text()='Candidates']"
EVENT_JOBS_MENU_LABEL = "//*[@class='menu']//*[text()='Jobs']"
ROSTER_MENU_LABEL = "//*[@class='menu']//*[text()='Roster']"
MY_CANDIDATES = "//*[contains(@class,'nav-text') and text()='My Candidates']"
ROSTER = "//*[contains(@class,'nav-text') and text()='Roster']"
ALL_REGISTER_CANDIDATES = "//*[contains(@class,'nav-text') and text()='All Registered Candidates']"
UNASSIGNED_CANDIDATES = "//*[contains(@class,'nav-text') and text()='Unassigned Candidates']"
ALL_CANDIDATES_MENU_LABEL = "//*[contains(@class,'nav-text') and text()='All Candidates']"
ADD_CANDIDATE_ICON_PLUS = "//*[@class='icon-plus']"
CEM_FIRSTNAME = "//*[@data-testid='cem_input_firstname']"
CEM_LASTNAME = "//*[@data-testid='cem_input_lastname']"
CEM_EMAIL = "//*[@data-testid='cem_input_email']"
EVENT_CEM_ADD_CANDIDATE_BUTTON = "//button[contains(@data-testid,'cem_btn_add_candidate')]"
SEARCH_INPUT = "(//*[@data-testid='candidate_btn_filter']/parent::div)/following-sibling::*[contains(@class,'el-input')]/input"
FILTER_BUTTON = "//*[contains(@class,'icon-filter pointer')]"
EXPORT_BUTTON = "//*[@data-test-id='export_dropdown_btn_choice']"
MY_CANDIDATES_NUMBER = "//*[contains(@class,'nav-text') and text()='My Candidates']//following-sibling::*"
UNASSIGNED_CANDIDATES_NUMBER = "//*[contains(@class,'nav-text') and text()='Unassigned Candidates']//following-sibling::*"
ADD_CANDIDATE_POPUP_CLOSE_BUTTON = "//span[text()= 'Add Candidate to Open Interview Time']//following-sibling::button//i[contains(@class, 'el-icon-close')]"
ADD_CANDIDATE_POPUP_CANCEL_BUTTON = "//button[contains(@data-testid, 'cem_btn_hide_candidate_form')]//span[text()='Cancel']"
EVENT_ORIENT_ROSTER_ICON_CIRCLES =  "(//span[contains(text(), '{}')]//ancestor::tr[contains(@class, 'el-table__row')]//td[contains(@class, 'column')])[6]//i[contains(@class, 'icon icon-check2')]"
EVENT_ORIENT_ROSTER_DATE_OF_EVENT =  "//div[contains(@role, 'tooltip') and contains(text(), '{}') and not(contains(@style,'display: none;'))]"
EVENT_ORIENT_PREP_USER_TAB = "//div[contains(@id, 'tab-user') and contains(text(), 'User')]"
EVENT_ORIENT_PREP_CANDIDATE_TAB = "//div[contains(@id, 'tab-candidate') and contains(text(), 'Candidate')]"
EVENT_ORIENT_ADD_ORIENTATION_PREP_CANDIDATE_BUTTON =  "//div[contains(@id, 'pane-candidate')]//span[contains(text(), 'Add Orientation Prep')]"
EVENT_ORIENT_ADD_ORIENTATION_PREP_USER_BUTTON =  "//div[contains(@id, 'pane-user')]//span[contains(text(), 'Add Orientation Prep')]"
EVENT_ORIENT_NO_DOC_TO_REVIEW_USER_TEXT =  "//div[contains(@id, 'pane-user')]//span[contains(text(), 'No Documents to Review')]"
EVENT_ORIENT_NO_DOC_TO_REVIEW_CANDIDATE_TEXT =  "//div[contains(@id, 'pane-candidate')]//span[contains(text(), 'No Documents to Review')]"
EVENT_ORIENT_DOC_PREP_CLOSE_BUTTON =  "//span[contains(@data-testid, 'prep_document_btn_close')]"
EVENT_ORIENT_EVENT_CARE_CLOSE_BUTTON =  "//header//span[contains(@data-testid, 'event_care_btn_show')]"
EVENT_ORIENT_VIEW_DOC_PREP_CANDIDATE_BUTTON =  "//div[contains(@id, 'pane-candidate')]//span[contains(text(), 'View Document')]"
EVENT_ORIENT_VIEW_DOC_PREP_USER_BUTTON =  "//div[contains(@id, 'pane-user')]//span[contains(text(), 'View Document')]"
EVENT_SAVE_BUTTON_ON_MODAL = "//button[contains(@class, 'btn btn-primary btn-save-msg')]"
EVENT_OK_BUTTON_ON_MODAL = "//*[contains(@class, 'v-modal-footer')]//*[@class='btn btn-primary btn-sm ok-btn']"


# EVENT DASHBOARD PAGE / All candidate page
ALL_CANDIDATES_ICON_PROFILE = "//span[contains(text(), '{}')]//ancestor::tr//div[contains(@class, 'icon-dropdown-profile')]"
ALL_CANDIDATES_JOB_TITLE_VALUE = "//span[contains(text(), '{}')]//ancestor::tr//td[4]//span"
ALL_CANDIDATES_JOB_TITLE_NEXT_LINE_VALUE = "(//span[contains(text(), '{}')]//ancestor::tr//following-sibling::tr)[1]//td[4]//span"
ALL_CANDIDATES_REQUISITION_ID_VALUE = "//span[contains(text(), '{}')]//ancestor::tr//td[5]//span"
ALL_CANDIDATES_REQUISITION_ID_NEXT_LINE_VALUE = "(//span[contains(text(), '{}')]//ancestor::tr//following-sibling::tr)[1]//td[5]//span"
ALL_CANDIDATES_APPLY_ON_VALUE = "//span[contains(text(), '{}')]//ancestor::tr//td[11]//span"
ALL_CANDIDATES_APPLY_ON_NEXT_LINE_VALUE = "(//span[contains(text(), '{}')]//ancestor::tr//following-sibling::tr)[1]//td[11]//span"

# EVENT DASHBOARD PAGE / Schedule tab / Event schedule
ADD_INTERVIEWS_ADD_TEAM_MEMBER_BUTTON = "//button//span[contains(text(), 'Add Team Members')]"
TOASTED_MESSAGE_ADD_INTERVIEWS = "//*[contains(@class, 'toasted-primary default') and contains(text(), '{} Added to Interview')]"
UNDO_BUTTON_ON_TOASTED_MESSAGE = "//*[contains(@class, 'toasted-primary default') and contains(text(), 'Added to Interview')]//a[contains(text(), 'Undo')]"
EVENT_INTERVIEWER_NAME = "//button[@data-testid='event_schedule_btn_add_interviewer']//span[contains(text(), '{}')]"

# EVENT DASHBOARD PAGE / Team tab
MY_EVENT_TEAM_TEXT = "//*[contains(@data-testid, 'event_attendee')]//div[contains(text(), 'My Event Team')]"

# EVENT DETAIL SCHEDULE PAGE
SESSION_DETAIL_TIME = "//*[@data-testid='session_detail_title_time']"
CANDIDATES_SCHEDULED = "//*[@class='icon icon-ic_person']"
CALENDAR_SESSION = "//*[contains(@class, 'fc-title')]"
SESSION_NAME_IN_CARD = "//*[@class='el-card__header']//*[contains(text(),'{}')]"
SESSION_CARD_BACK_BTN = "//*[@class='el-card__header']//*[@class='icon-arrow-left']"
SESSION_CARD_TITLE = "//*[@class='el-card__header']//*[@class='icon-arrow-left']//parent::*//following-sibling::*"
OPEN_INTERVIEW_TIME = "//*[@class='el-card__body']//*[contains(@class, 'el-dropdown-selfdefine')]"
ADD_CANDIDATE = "//*[@x-placement='bottom-end']//*[@class='icon icon-add-user']"
DELETE_CANDIDATE = "//*[@x-placement='bottom-end']//*[@class='icon icon-delete2']"
CHECKIN_BUTTON = "//*[@data-testid='interview_btn_check_in']"
FORWARD_DAY_BUTTON = "//*[contains(@class,'icon-chevron-right')]"
BACKWARD_DAY_BUTTON = "//*[contains(@class,'icon-chevron-left')]"
CANDIDATE_FIRST_NAME_TEXTBOX = "//*[@data-testid='schedule_input_first_name']"
CANDIDATE_LAST_NAME_TEXTBOX = "//*[@data-testid='schedule_input_last_name']"
CANDIDATE_EMAIL_TEXTBOX = "//*[@data-testid='schedule_input_email']"
CANDIDATE_PHONE_NUMBER_TEXTBOX = "//*[@data-testid='schedule_input_phone_number']"
ADD_CANDIDATE_BTN = "//*[@data-testid='schedule_btn_add_candidate']"
LAST_CANDIDATE_INTERVIEW = "(//*[@class='el-dropdown']/parent::*)[last()]"
EMPTY_SESSION = "//*[@data-testid='empty_lbl_title']"
SESSION_DURATION_AND_TYPE = "//*[@data-testid='session_detail_lbl_duration']"
VIRTUAL_SESSION_JOIN_BUTTON = "//*[@data-testid='session_detail_btn_join_session']"
VIRTUAL_SESSION_PASSWORD = "//*[@data-testid='session_detail_lbl_pass']"
MENU_ACTIVE = "//div[contains(@class, 'menu-active')]//div[contains(text(), '{}')]"

# EVENT DETAIL / JOBS PAGE
EVENT_DETAIL_JOB_REQ_CHECKBOX = "//*[contains(text(),'{}')]//ancestor::tr[@class='el-table__row']//td//span[@class='el-checkbox__inner']"
EVENT_DETAIL_JOB_REMOVE_POPUP = "//span[contains(text(),'Remove Job')]//ancestor::div[@role='dialog']"
EVENT_DETAIL_JOB_REMOVE_POPUP_INNER_TEXT = "//span[contains(text(),'Remove Job')]//ancestor::div[@role='dialog']//*[contains(text(),'{}')]"
EVENT_DETAIL_JOB_REMOVE_POPUP_CANCEL_BUTTON = "//span[contains(text(),'Remove Job')]//ancestor::div[@role='dialog']//button[@class='el-button el-button--default']"
EVENT_DETAIL_JOB_REMOVE_POPUP_REMOVE_BUTTON = "//span[contains(text(),'Remove Job')]//ancestor::div[@role='dialog']//button[contains(@class,'el-button el-button--primary')]"

# EVENT ROSTER PAGE
ROSTER_CANDIDATE_NUMBER = "//div[contains(@class,'menu-active')]//div[text()='Roster']//following-sibling::*"
BACK_TO_CANDIDATES_BUTTON = "//div[@id='candidate-detail-header']//span[@class='icon icon-arrow-left']"
ROSTER_SEARCH_CANDIDATES_INPUT = "//input[contains(@placeholder, 'Search Candidates')]"

# EVENT DETAIL CANDIDATES PAGE
ASSIGN_TEAM_MEMBER_CHECKBOX = "//*[@class='el-checkbox__original']//parent::*[@class='el-checkbox__input']"
ASSIGN_TEAM_MEMBER_BUTTON = "//*[contains(@class,'el-checkbox is-checked')]//following-sibling::button"
SHOW_MEMBER_BUTTON = "//*[@data-testid='btn_show_menu']"
SELECTED_TEAM_MEMBER = "//*[@data-testid='btn_show_menu']//*[contains(text(),'{}')]"
MEMBER_ASSIGN_TO_CANDIDATE = "//*[contains(@data-testid,'lbl_title')]//*[contains(text(),'{}')]"
ASSIGN_BUTTON = "//*[contains(@class,'el-button--primary')]//span[text()='Assign']"
ASSIGNED_MEMBER_NAME = "//*[@class='text-overflow' and text()='{}']"
CANDIDATE_CHECKBOX = "//*[contains(@class,'el-table__row')]//label[contains(@class,'el-checkbox')]"
CANCEL_BUTTON = "//*[@class='el-message-box__btns']//*[@class='el-button el-button--default']"
CONTINUE_BUTTON = "//*[@class='el-message-box__btns']//*[@class='el-button el-button--default el-button--primary']"
CANDIDATES_ALREADY_ASSIGNED_MESSAGE = "//*[@class='el-message-box__message']"
CANDIDATES_ALREADY_ASSIGNED_POPUP = "//*[@class='el-message-box ol-confirm candidate-assigned-confirm']"
SEARCH_BOX_DISABLED = "//*[@class='el-input__inner' and @disabled='disabled']"
EXPORT_BUTTON_DISABLED = "//*[@data-test-id='export_dropdown_btn_choice' and @disabled='disabled']"
CANDIDATE_ROW = "//*[@class='el-table__row']"
CANDIDATE_DETAIL = "//*[@id='candidate-detail-header']"
JOURNEY_STATUS_TEXT = "(//td[contains(@class, 'column')])[8]//span"
INTERVIEWER_COLUMN_TEXT = "(//td[contains(@class, 'column')])[9]//span"
INTERVIEWER_COLUMN_EMPTY_STATE = "(//td[contains(@class, 'column')])[9]//span[text()='-']"
SESSION_TIME_BY_SESSION_NAME = "//*[contains(text(), '{}')]//ancestor::*//tr//td//span[contains(text(),'{}')]"

# EVENT REGISTER PAGE
EVENT_NAME_IN_CARD = "//div[@class='el-card__body']//*[contains(text(),'{}')]"
EVENT_STATUS = "//*[@data-testid='event_lbl_action']"
EVENT_STATUS_DISABLED = "//*[@disabled='disabled' and @data-testid='event_btn_action']"
INPUT_TEXTBOX = "dom:document.querySelector(\"[vce-ready]\").shadowRoot.querySelector(\"[data-testid='widget_input_text']\")"
USER_SEND_REPLY_BUTTON = "dom:document.querySelector(\"[vce-ready]\").shadowRoot.querySelector(\"[class='icon icon-arrow-right']\")"
EVENT_CARD_TIME = "//div[@data-testid='event_lbl_event_time']"
EVENT_SCHEDULE_CARD_TIME = "//i[contains(@class,'icon icon-time')]//following-sibling::div"
JOIN_SESSION_BUTTON = "//button[@class='el-button el-button--primary']//span[text()='Join Session']"
JOB_CARD_TITLE = "//div[@class='el-card__body']//div[@data-testid='job_lbl_title']"
JOB_CARD_LOCATION = "//div[@class='el-card__body']//div[@data-testid='job_lbl_location']"
CONVERSATION_MESSAGE = "dom:document.querySelector(\"[vce-ready]\").shadowRoot.querySelectorAll(\"[class='msg-text']\")"
CHOOSE_INTERVIEW_TIME = "dom:document.querySelector(\"[vce-ready]\").shadowRoot.querySelector(\"[class='open-slot-picker']\")"
CALENDAR_TIME_PICKER = "//div[@id='sp-calendar-ctn']//div[@class='fc-time']"
ACTION_CANCEL_BUTTON = "//div[@class='modal-content printable']//button[contains(@class,'cancel-btn')]"
SESSION_CALENDAR_LINK = "//*[contains(text(),'Do any of these times work?')]//a"
SESSION_IN_CALENDAR = "//div[@class='fc-content']"
CONFIRM_CHOICE_BUTTON_EVENT = "//div[contains(@class,'o-list-select-btn')]"
EVENT_JOB_APPLY_BUTTON = "//*[@data-testid='job_lbl_apply']"
BACK_TO_EVENT_OVERVIEW_ICON = "//span[@data-testid='job_lbl_back']//parent::div//i[@class='icon-arrow-left']"
JOB_DESC_TEXT = "//*[@data-testid='job_lbl_desc']"
LANDING_PAGE_EVENT_DATE = "//*[@data-testid='event_lbl_event_day']"
LANDING_PAGE_EVENT_TIME = "//*[@data-testid='event_lbl_event_time']"
LANDING_PAGE_EVENT_LOCATION = "//*[@data-testid='event_lbl_event_location']"
BACK_TO_EVENT_LANDING_PAGE = "//div[contains(@class, 'header')]//i[contains(@class, 'icon-arrow-left')]"
EVENT_JOB_DETAIL_NAME = "(//div[@class='el-card__body']//div[@data-testid='job_lbl_title'])[last()]"
EVENT_JOB_DETAIL_LOCATION = "(//div[@class='el-card__body']//div[@data-testid='job_lbl_location'])[last()]"
EVENT_JOB_DETAIL_EMPLOYMENT_TYPE = "(//div[@class='el-card__body']//div[@data-testid='job_lbl_employment_type'])[last()]"
EVENT_SCHEDULE_INTERVIEW_CARD_TIME = "//div[contains(text(), 'Interviews')]//parent::div//i[contains(@class, 'icon-time')]//following-sibling::div"
EVENT_SCHEDULE_INTERVIEW_CARD_TYPE = "//div[contains(text(), 'Interviews')]//parent::div//i[contains(@class, 'icon-cal-neutral')]//following-sibling::div"
EVENT_SCHEDULE_TAB = "//div[@id='tab-schedule']"

# EVENT SCHEDULING PAGE
CONVERSATION_MESSAGE_2 = "//*[@class='landing-chat-ctn']//*[@class='msg ours']//*[@class='msg-text']"

# EVENT CALENDAR PAGE
BOOK_TIME_BUTTON = "//div[@class='fc-button-book']"
EVENT_CONVERSATION_TEXTAREA = "//textarea[@class='msg-input']"
OPEN_CALENDAR_BUTTON = "//a[@class='open-slot-picker']"

# ORIENTATION EVENT CALENDAR PAGE
SELECT_TIME_BUTTON = "//span[text()='{}']//following-sibling::button[contains(@class,'fc-button-book')]"
ORIENTATION_LANDING_CHAT = "//div[@class='landing-chat']"

# Event In Person
VENUE_LOCATION_FIELDS = "id:id-venue-location-selectized"
VENUE_NAME_FIELDS = "id:id-location-title"
HEADER_TYPE_BOX = "//div[contains(@class, 'header-type-box')]//span"
INTERNAL_EVENT_NAME_FIELDS = "//*[contains(text(), 'Internal Event Name is the same as Public Event Name')]"
HIRING_EVENT_TITLE_LEFT_HEADER = "//div[contains(@class, 'header-type-box')]//p[contains(text(), 'Hiring Event')]"
ORIENT_EVENT_TITLE_LEFT_HEADER = "//div[contains(@class, 'header-type-box')]//p[contains(text(), 'Orientation')]"
BACK_TO_EVENTS = "//div[@data-testid='event_builder_btn_back']"

# campus activity
CAMPUS_ACTIVITY = "//div[contains(@data-testid, 'event_selection_type_activity')]"
CREATE_ACTIVITY = "//span[contains(text(), 'Create Activity')]/ancestor::button"
ACTIVITY_DETAILS = "//ul[@role='tablist']//*[contains(text(),'Activity Details')]"
MY_ACTIVITY_TEAM = "//ul[@role='tablist']//*[contains(text(),'My Activity Team')]"
ACTIVITY_PLANNING = "//ul[@role='tablist']//*[contains(text(),'Activity Planning')]"
ACTIVITY_NAME = "id:id_name"
SCHOOL_DROPDOWN = "//div[@data-testid='event_builder_select_school_id']"

# Confirm dialog
CANCEL_BUTTON_EVENT_SESSION = "//div[contains(@id, 'add-session-modal')]//button[contains(text(), 'Cancel')]"
DISCARD_BUTTON = "//div[contains(@class, 'ai-modal modal fade confirm-modal warning-modal event-modal in')]//button[contains(text(), 'Discard')]"

# event session
DIALOG_SESSION = "//div[@id= 'add-session-modal']"
SESSION_TAB_SESSION_DETAILS = "//*[@id='tab-session_details']"
SESSION_TAB_INTERVIEW_DETAILS = "//*[@id='tab-interview_details']"
SESSION_TAB_INTERVIEWER = "//*[@id='tab-interviewer']"
SESSION_TAB_SETTING = "//*[@id='tab-settings']"
CREATE_A_SESSION_HEADER = "//div[contains(@class, 'ai-sidebar-header-title') and contains(text(), ' Create a Session')]"
CREATE_VIRTUAL_INTERVIEW_SESSION = "//div[contains(@class, 'ai-sidebar-header-title') and contains(text(), 'Create Virtual Interview Session')]"
DESCRIPTION_EVENT_SESSION = "//*[contains(@data-testid,'session_detail_text_area_description')]"
SESSION_EVENT_ROW = "//div[@data-testid='session_content_lbl_name']"
ICON_EDIT_SESSION_EVENT_ROW = "//div[@role='tooltip' and not(contains(@style,'display: none;'))]//span[@data-testid='session_popup_btn_edit']"
VIRTUAL_BOOTH_SESSION_DISABLE = "//div[contains(text(), 'Virtual Chat Booth')]/ancestor::div[contains(@class, 'interaction-type-item cursor disabled')]"
VT_INTERVIEW_SCHEDULE = "//div[contains(text(), 'Virtual Scheduled Interviews')]"
CANCEL_BUTTON_ON_SESSION_DIALOG = "//div[contains(@id, 'add-session-modal')]//button[contains(text(), 'Cancel')]"
CALENDAR_HEADER = "//div[contains(@class, 'calendar-header')]"
EVENT_ADD_INTERVIEWER_SEARCH_BOX = "//*[contains(@data-testid,'session_detail_input_staff')]//input"
EVENT_INTERVIEWER_CHECKBOX = "//*[@data-testid='event_builder_available_staff_title' and contains(text(),'{}')]"
EVENT_INTERVIEWER_UNAVAILABLE_CHECKBOX = "//*[@data-testid='event_builder_unavailable_staff_title' and contains(text(),'{}')]"
EVENT_INTERVIEWER_AVAILABLE_TIME_TEXT = "//*[@data-testid='event_builder_available_staff_title' and contains(text(),'{}')]//following-sibling::*//span"
EVENT_ADD_INTERVIEWER_CANCEL_BUTTON = "//button[@data-testid='event_staff_btn_cancel']"
EVENT_SESSION_STAFF_TAB = "//div[contains(@id, 'tab-session_staff')]"
EVENT_ADD_INTERVIEWER_SETTING_DROPDOWN = "//*[@data-tab='settings']//*[@data-testid='base_dropdown_selected']"
EVENT_ADD_SETTING_DROPDOWN = "//*[@data-testid='base_dropdown_selected']"
SESSION_DETAIL_POPUP_TITLE = "//*[contains(@data-testid,'session_popup_lbl_name') and contains(text(),'{}')]"
SESSION_DETAIL_POPUP_START_DATE = "//*[contains(@data-testid,'session_popup_lbl_start')]"
SESSION_DETAIL_POPUP_DATE = "//*[contains(@data-testid,'session_popup_lbl_date_time')]"
SESSION_DETAIL_POPUP_DESCRIPTION = "//*[contains(@data-testid,'session_popup_lbl_description')]"
SESSION_DETAIL_POPUP_STAFF = "//*[contains(@data-testid,'session_popup_lbl_staff')]"
SESSION_DETAIL_POPUP_ITV_TYPE = "//*[contains(@data-testid,'session_popup_lbl_itv')]"
SESSION_DETAIL_POPUP_VENUE_NAME = "//*[contains(@data-testid,'session_popup_lbl_itv_location_name')]"
SESSION_DETAIL_POPUP_VENUE_LOCATION = "//*[contains(@data-testid,'session_popup_lbl_itv_location_title')]"
EDIT_SESSION_BUTTON = "(//*[contains(@data-testid,'session_popup_btn_edit')])[last()]"
DUPLICATE_SESSION_BUTTON = "(//*[contains(@data-testid,'session_popup_btn_duplicate')])[last()]"
DELETE_SESSION_BUTTON = "(//*[contains(@data-testid,'session_popup_btn_delete')])[last()]"
HIDE_SESSION_BUTTON = "(//*[contains(@data-testid,'session_popup_btn_hide')])[last()]"
CONFIRM_DELETE_SESSION_BUTTON = "//button[contains(@class,'danger')]//*[contains(text(),'Delete Session')]"
CANCEL_DELETE_SESSION_BUTTON = "//div[contains(@class,'ol-confirm')]//*[contains(text(),'Cancel')]"
DELETE_SESSION_STAFF_ICON = "//*[contains(@data-testid, 'staff_title') and contains(text(),'{}')]//ancestor::*//i[contains(@class,'icon-delete')]"
SESSION_CANDIDATE_LOCATION_ADDRESS_TEXTBOX = "//input[contains(@data-testid,'session_detail_input_address')]"
SESSION_CANDIDATE_LOCATION_NAME_TEXTBOX = "//input[contains(@data-testid,'session_detail_input_location_name')]"
ADD_SESSION_CANCEL_BUTTON = "//button[contains(@data-testid, 'session_detail_btn_cancel')]"
ADD_INTERVIEWER_NAME_LABEL = "//*[@data-testid='staff_title' and contains(text(), '{}')]"
ADD_INTERVIEWER_ELLIPSE_BUTTON = "(//*[@data-testid='staff_title' and contains(text(), '{}')]//ancestor::*//button[contains(@data-testid, 'menu')])[last()]"
ADD_INTERVIEWER_VIEW_AVAILABLE_ICON = "(//*[contains(@class, 'icon-visibility')])[last()]"
ADD_INTERVIEWER_REMOVE_INTERVIEWER_ICON = "(//*[contains(@class, 'icon-delete')])[last()]"
ADD_INTERVIEWER_BACK_BUTTON = "(//*[contains(@class, 'icon-arrow-left')])[last()]"
ADD_INTERVIEWER_UNDO_BUTTON = "//*[contains(@class, 'undo') and contains(text(), 'Undo')]"
ADD_TO_SESSION_BUTTON = "//span[contains(text(), 'Add to Session')]//ancestor::button[contains(@class, 'button--primary')]"
ADD_INTERVIEW_AVAILABILITY_PILL_TIME = "//*[contains(text(),'{}')]//parent::*//parent::span"
ADD_INTERVIEWER_CONFIRM_REMOVE_INTERVIEWER_BUTTON = "//button[contains(@class, 'button--danger')]//span[contains(text(), 'Remove')]"
DELETE_SESSION_DETAIL_BUTTON = "//button[contains(@data-testid, 'session_detail_btn_delete')]"
EVENT_SESSION_POPUP_CLOSE_BUTTON = "//div[contains(@class, 'el-drawer__container el-drawer__open')]//i[contains(@class, 'el-dialog__close el-icon el-icon-close')]"

# live broadcast session
LIVE_VIDEO_BROADCAST = "//div[contains(text(), 'Live Video Broadcast')]"

# event home page
CANDIDATE_TAB = "//a[contains(@href, 'candidate')]//div[text()='Candidates']"
EMPTY_LIST_CANDIDATE = "//div[contains(@data-testid, 'empty_lbl_title')]"
ADD_CANDIDATE_BUTTON = "//span[contains(text(), 'Add Candidate')]"
INPUT_FULL_NAME_CANDIDATE = "//input[contains(@data-testid, 'cem_input_fullname')]"
INPUT_FIRST_NAME_CANDIDATE = "//input[@data-testid='cem_input_firstname']"
INPUT_LAST_NAME_CANDIDATE = "//input[@data-testid='cem_input_lastname']"
INPUT_EMAIL_CANDIDATE = "//input[contains(@data-testid, 'cem_input_email')]"
ADD_CANDIDATE_BUTTON_DIALOG_ADD = "//button[contains(@data-testid, 'cem_btn_add_candidate')]"
MY_CANDIDATES_LIST_VIEW = "//a[contains(@href, 'my-candidates')]//div[contains(text(), 'My Candidate')]"
UNASSIGNED_CANDIDATES_LIST_VIEW = "//a[contains(@href, 'unassigned-candidates')]//div[contains(text(), 'Unassigned Candidates')]"
ALL_REGISTERED_CANDIDATES_LIST_VIEW = "//a[contains(@href, 'registered-candidates')]//div[contains(text(), 'All Registered Candidates')]"
VIRTUAL_CHAT_BOOTH_RIGHT_HAND_SIDE = "//div[contains(@class,'el-card__header')]"
SCHEDULE_TAB_DETAILS = "//a[contains(@href, 'schedule')]//div[text()='Schedule']"
SESSION_DESCRIPTION_DETAIL_HOME_EVENT = "//span[contains(@data-testid, 'session_detail_desc_content')]"
SESSION_CALENDAR_SELECTED = "//a[contains(@class, 'fc-event-future is-event-session event-selected')]"
RIGHT_HAND_SIDE_SESSION_INFO = "(//div[contains(@class, 'el-card is-always-shadow _')]//span[contains(text(), '{}')])[2]"
RIGHT_HAND_SIDE_SESSION_DATE_TIME = "//div[contains(@data-testid, 'session_detail_title_time')]"

# event list page
OCCURRENCE_WITHIN_RECURRING_EVENT = "//tr[contains(@class, 'occurrence-')]"
RECURRING_EVENTS_TAB = "//div[contains(text(), 'Recurring Events')]/ancestor::a"
AN_RECURRING_EVENT_CARD = "//div[contains(@data-testid, 'event_lbl_recurring_name')]"
NAME_LIST = "//div[contains(@data-testid, 'event_lbl_recurring_name')]"
TOTAL_OCCURRENCE = "//*[contains(@data-testid, 'event_lbl_occurrence_total')]"
LIST_OCCURRENCE_ON_CARD = "(//div[contains(@data-testid, 'event_btn_recurring_item')])[1]//tr[contains(@class, 'occurrence-')]"
LIST_ITEM_EVENT = "//*[contains(@data-testid, 'event_btn_item')]"
MY_EVENT_ACTIVE_ICON = "//div[contains(text(), 'My Event')]/preceding-sibling::i"
MENU_ITEM_OCCURRENCE = "(//div[contains(@data-testid, 'event_btn_recurring_item')])[1]//tr[contains(@class, 'occurrence-')]//button"
EDIT_RECURRING_EVENT = "//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Edit Event Occurrence')]"
THE_NUMBER_OF_OCCURRENCES = TOTAL_OCCURRENCE
SEARCHING_INPUT = "//*[contains(@data-testid, 'event_input_search')]//input[contains(@placeholder, 'Search')]"
VIRTUAL_BOOT_CHAT_TAG = "//div[contains(@data-testid, 'event_btn_item')]//div[contains(text(), 'Chat')]"
VIRTUAL_TAG = "//div[contains(@data-testid, 'event_btn_item')]//div[contains(text(), 'Virtual')]"
INTERVIEW_TAG = "//div[contains(@data-testid, 'event_btn_item')]//div[contains(text(), 'Interviews')]"
UPCOMING_EVENT_NAME = "//div[contains(@data-testid, 'event_lbl_event_name')]"
UPCOMING_EVENT_DATE = "//div[contains(@data-testid, 'event_lbl_event_day')]"
UPCOMING_EVENT_LOCATION = "//div[contains(@data-testid, 'event_lbl_event_location')]"
UPCOMING_EVENT_TIME = "//div[contains(@data-testid, 'event_lbl_event_time')]"
UPCOMING_MENU_ITEM_EVENT = "//div[contains(@data-testid, 'event_btn_item')]//div[@class='el-dropdown']//button[contains(@role, 'button')]"
UPCOMING_MENU_ITEM_BY_NAME = "//div[contains(@data-testid, 'event_lbl_event_name') and contains(text(), '{}')]//ancestor::div[contains(@data-testid,'event_btn_item')]//*[contains(@class,'icon-menu')]"
RECURRING_MENU_ITEM_EVENT = "//div[contains(@data-testid, 'event_btn_menu')]//button"
RECURRING_MENU_ITEM_EVENT_SUB = "//tr[contains(@class, 'el-table__row occurrence')]//button"
SEARCH_EVENT_INPUT = "//*[@data-testid='event_input_search']//input"
RECURRING_MENU_ITEM_BY_NAME = "//div[contains(@data-testid, 'event_lbl_recurring_name') and contains(text(), '{}')]/ancestor::div[contains(@data-testid,'event_btn_recurring_item')]//i[contains(@class,'icon-menu')]"
UPCOMING_MENU_DELETE_EVENT = "//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Delete Event')]"
UPCOMING_MENU_DELETE_ACTIVITY = "//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Delete Activity')]"
UPCOMING_EVENT_HAS_NAME = "//div[contains(@data-testid, 'event_lbl_event_name') and contains(text(), '{}')]"
RECURRING_EVENT_HAS_NAME = "//div[contains(@data-testid, 'event_lbl_recurring_name') and contains(text(), '{}')]"
DELETE_POPUP = "//span[contains(text(), 'Delete event')]/ancestor::button"
DELETE_ACTIVITY_POPUP="//span[contains(text(), 'Delete activity')]/ancestor::button"
GRID_VIEW_BUTTON = "//button[contains(@data-testid, 'event_btn_layout_style') and contains(@class, 'icon-grid-view')]"
LIST_VIEW_BUTTON = "//button[contains(@data-testid, 'event_btn_layout_style') and contains(@class, 'icon-list-view')]"
BUTTON_GOING_EVENT_CARD = "//span[contains(text(), 'Going')]/ancestor::button"
EDIT_OCCURRENCE_SLIDE = "//div[contains(@class, 'list-occurrences')]"
EDIT_ICON = "(//i[contains(@class,'icon-edit')])[last()]"
DELETE_ICON = "(//i[contains(@class,'icon-delete2')])[last()]"
DELETE_ICON_RECURRING = "(//ul[contains(@x-placement, '-end')]//i[contains(@class, 'icon-delete2')])[last()]"
DUPLICATE_ICON = "(//i[contains(@class,'icon-copy')])[last()]"
DELETE_OCCURRENCE_BUTTON = "//span[contains(text(), 'Delete Occurrence')]/ancestor::button"
TITLE_DELETE_OCCURRENCE_POPUP = "//div[contains(@aria-label, 'Delete Event Occurrence')]//span[contains(text(), 'Delete Event Occurrence')]"
DESCRIPTION_DELETE_OCCURRENCE_POPUP = "//div[contains(@aria-label, 'Delete Event Occurrence')]//p[contains(text(), 'Deleting this event occurrence will remove it from the recurring event but will not delete the entire recurring event')]"
RECURRING_TAB_DESCRIPTION_DELETE_OCCURRENCE_POPUP = "//div[contains(@aria-label, 'Delete Recurring Event')]//p"
RECURRING_TAB_CANCEL_BUTTON_POPUP = "//div[contains(@aria-label, 'Delete Recurring Event')]//span[contains(text(), 'Cancel')]"
RECURRING_TAB_DELETE_BUTTON_POPUP = "//div[contains(@aria-label, 'Delete Recurring Event')]//span[contains(text(), 'Delete Recurring Event')]/ancestor::button"
CANCEL_ICON_RECURRING = "//ul[contains(@x-placement, '-end')]//i[contains(@class, 'icon-delete2')]/following-sibling::span"
REMOVE_ELLIPSES_ICON = "//ul[contains(@x-placement, '-end')]//i[contains(@class, 'icon-delete2')]"
DATE_OF_OCCURRENCE = "//div[contains(@class, 'cell') and contains(text(), 'Date of Event')]"
LOCATION_OCCURRENCE = "//div[contains(@class, 'cell') and contains(text(), 'Location')]"
FREQUENCY_OCCURRENCE = "//div[contains(@class, 'cell') and contains(text(), 'Frequency')]"
DELETE_RECURRING_EVENT = "//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Delete Event Occurrence')]"
REGISTER_EVENT = "//button[contains(@data-testid, 'event_btn_action')]"
REGISTER_EVENT_IN_PROGRESS = "//button[contains(@data-testid, 'event_btn_action')]//span[contains(text(), 'Registration In Progress')]"
FIRST_PAST_EVENT_MENU_ITEM = "(//div[contains(@data-testid,'event_btn_item')]//*[contains(@class,'icon-menu')])[2]"
EVENT_EDIT_ACTIVITY_BUTTON = "//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Edit Activity')]"
FIRST_PAST_EVENT = "(//div[contains(@data-testid, 'event_btn_item')])[1]"
LAST_RECURRING_EVENT_NAME = "(//*[contains(text(),'{}')]//ancestor::*[contains(@data-testid,'event_btn_recurring_item')]//*[contains(@class,'occurrence')])[last()]//td"
EVENT_RSVP_DROPDOWN = "//div[contains(@data-testid, 'event_btn_rsvp')]"
EVENT_RSVP_DROPDOWN_SELECTED_VALUE = "//*[contains(@data-testid,'event_btn_rsvp')]//button//span[contains(text(),'{}')]"
EDIT_INTERVIEW_SESSION_ICON_MENU = "//*[contains(@data-testid, 'staff_title') and contains(text(),'{}')]//ancestor::*//i[contains(@class,'icon-menu')]"

# Orient event header setting popup
ORIENT_EVENT_APPLY_SUBMIT_BUTTON = "//button[@data-testid='scheduling_orientation_btn_submit' and not(contains(@disabled, 'disabled'))]"
ORIENT_EVENT_APPLY_SUBMIT_DISABLED_BUTTON = "//button[@data-testid='scheduling_orientation_btn_submit' and (contains(@disabled, 'disabled'))]"
ORIENT_EVENT_HEADER_TOGGLE_SETTING_BUTTON = "//button[@data-testid='header_btn_toggle-setting']"
ORIENT_EVENT_REGISTRATION_BREAK_RULE_TOGGLE = "//div[@data-testid='scheduling_btn_rule_on']"
ORIENT_EVENT_SCHEDULING_TIME_LINE_TOGGLE = "//div[@data-testid='scheduling_btn_timeline']"
ORIENT_EVENT_SCHEDULING_TIME_LINE_MIN = "//div[@data-testid='scheduling_select_timeline_min']"
ORIENT_EVENT_SCHEDULING_TIME_LINE_MAX = "//div[@data-testid='scheduling_select_timeline_max']"
ORIENT_EVENT_ARROW_BACK_SETTING_ICON = "//i[@data-testid='header_btn_toggle-back-setting']"
SETTING_ORIENT_EVENT_CANCEL_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_cancel'])[last()]"
ORIENT_EVENT_CHECK_IN_INFO_CANDIDATE_NAME = "//*[contains(@data-testid, 'check_in_info_name') and contains(text(), '{}')]"
ORIENT_EVENT_CHECK_IN_INFO_DESC = "//*[contains(@data-testid, 'check_in_info_desc') and contains(text(), '{}')]"
ORIENT_EVENT_CHECK_IN_BUTTON = "//*[contains(@data-testid, 'check_in_btn_check_in')]"
ORIENT_EVENT_CLOSE_CHECK_IN_CANDIDATE_BUTTON = "//div[contains(@data-testid, 'candidate_inbox_check_in_candidate')]//i[contains(@class, 'el-icon-close')]"

# Orient event Schedule popup
ORIENT_EVENT_CANDIDATE_INFOR_SCHEDULING_POPUP = "//div[contains(@class, 'color-lighter text-overflow')]// div[contains(text(), '{}')]"
ORIENT_EVENT_GO_BACK_BUTTON = "//button[contains(@data-testid, 'scheduling_cancel')]//span[contains(text(), 'Go Back')]"
ORIENT_EVENT_REGISTRATION_IS_CLOSED_TEXT = "//span[contains(text(), 'Registration is closed')]"
ORIENT_EVENT_NEVER_MIND_BUTTON = "(//button//span[contains(text(), 'Nevermind')])[last()]"
SCHEDULING_SUMMARY_CANCEL_BUTTON = "//button[@data-testid='scheduling_summary_btn_cancel']"
SCHEDULING_CONFIRM_CANCEL_BUTTON = "//button[@data-testid='scheduling_cancel_btn_confirm']"
CANCEL_MESSAGE_TEXT_AREA = "//textarea[contains(@id, 'cancelMessage')]"
SCHEDULING_DETAIL_CLOSE_BUTTON = "//button[@data-testid='scheduling_detail_btn_close']"
SCHEDULING_ORIENT_EVENT_CANCEL_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_cancel'])[last()]"
SEND_TIMES_EVENT_CANCEL_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_cancel'])[last()]"
INPUT_SEARCH_ORIENT_EVENT = "//div[contains(@data-testid, 'input_search')]//input"
SCHEDULING_ORIENTATION_EVENT_LABEL = "//div[@data-testid='scheduling_lbl_type' and contains(text(),'Orientation Event')]"
SCHEDULING_ORIENT_EVENT_SUBMIT_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_submit'])[last()]"
SEND_TIMES_EVENT_SUBMIT_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_submit'])[last()]"
SCHEDULING_ORIENT_EVENT_SUBMIT_DISABLED_BUTTON = "(//button[@data-testid='scheduling_orientation_btn_submit' and contains(@disabled, 'disabled')])[last()]"
SCHEDULING_ORIENT_EVENT_CLOSE_BUTTON = "//button[@data-testid='scheduling_event_btn_close']"
ORIENT_EVENT_SCHEDULING_OPENED_PANEL = "//div[contains(@id, 'panel-scheduling-opened')]"
SCHEDULING_TIME_LINE_SELECTED_VALUE = "(//li[contains(@class, 'dropdown__item selected')]//span[contains(text(), '{}')])[last()]"
SCHEDULING_TIME_LINE_VALUE = "(//li[contains(@class, 'dropdown__item')]//span[contains(text(), '{}')])[last()]"
BORDER_ORIENT_EVENT_ON_SCHEDULING_POPUP = "//span[contains(text(), '{}')]//parent::div//parent::div//parent::div"
CHECKBOX_SELECT_ORIENT_EVENT_ON_SCHEDULING_POPUP = "//span[contains(text(), '{}')]//parent::div//label//span//span"
CHECKBOX_SELECT_ORIENT_IS_CHECKED = "//span[contains(text(), '{}')]//parent::div//label[contains(@class, 'is-checked')]"
ORIENT_SCHEDULING_ICON_COMPLETE = "//i[contains(@class, 'icon icon-interview-complete')]"
EXIT_SCHEDULING_EXIT_BUTTON = "//button[contains(@class, 'el-button--danger')]//span[contains(text(), 'Exit')]"
ORIENT_EVENT_CONFIRM_CANCEL_BUTTON = "//div[contains(@aria-modal, 'true') and contains(@aria-label,  'Cancel Interview')]"
CREATE_ORIENT_EVENT_SCHEDULING_BUTTON = "//button[contains(@data-testid,'scheduling_btn_create_event')]"

# EVENT - Create a session
EVENT_INTERACTION_TYPE_DESCRIPTION = "//div[contains(@data-testid, 'interaction_type_lbl_description')]"
EVENT_INTERACTION_TYPE_ITEM_DESCRIPTION_01 = "//div[contains(@data-testid, 'interaction_type_lbl_item_description_0')]"
EVENT_INTERACTION_TYPE_ITEM_DESCRIPTION_02 = "//div[contains(@data-testid, 'interaction_type_lbl_item_description_1')]"
EVENT_INTERACTION_TYPE_ITEM_DESCRIPTION_03 = "//div[contains(@data-testid, 'interaction_type_lbl_item_description_2')]"

# EVENT - Orientation Calendar
EVENT_CALENDAR_SELECT_EVENT = "//div[contains(@class, 'title') and contains(text(), '{}')]"
EVENT_CALENDAR_SELECT_EVENT_BUTTON = "//div[contains(@class, 'title') and contains(text(), '{}')]//ancestor::div[contains(@class, 'fc-content')]//button[contains(@class, 'btn-pick-time')]"

# EVENT - MY SCHEDULE
EVENT_MY_SCHEDULE_INTERVIEW_TIME = "//span[contains(text(), 'Interviews')]//ancestor::div[2]//div[@data-testid='event_lbl_interview_time']"
EVENT_MY_SCHEDULE_INTERVIEW_TYPE = "//span[contains(text(), 'Interviews')]//ancestor::div[2]//i[contains(@class, 'icon-interview')]//following-sibling::div"
EVENT_MY_SCHEDULE_INTERVIEW_LEFT_CARD_TIME = "//aside[contains(@class, 'el-aside')]//i[contains(@class, 'icon-time')]//following-sibling::div"
EVENT_MY_SCHEDULE_INTERVIEW_LEFT_CARD_TYPE = "//aside[contains(@class, 'el-aside')]//i[contains(@class, 'icon-interview')]//following-sibling::div"
EVENT_ACTIVITY_DASHBOARD_LOCATOR = "//*[@id='content-header']//div[contains(text(), 'Activity Dashboard')]"
EVENT_ACTIVITY_DASHBOARD_APPROVAL_STATUS_LABEL="//*[@data-testid='approval_status_lbl_status']"

# EVENT - CAMPUS PLAN
EVENT_CAMPUS_PLAN_FILTER_MODAL = "//div[@role='dialog']//span[contains(text(), 'Filter Your Campus Plans')]"
EVENT_CAMPUS_PLAN_FILTER_MODAL_TAB = "//div[@class='el-scrollbar__view']//*[text()='{}']"
EVENT_CAMPUS_PLAN_FILTER_MODAL_CHECKBOX = "//*[contains(@data-testid, 'filter_list_item_cbx')]//*[text()='{}']"
EVENT_CAMPUS_PLAN_REMOVE_FILTER_MODAL="//span[contains(@class, 'el-icon-close')]"
EVENT_CAMPUS_PLAN_FILTER_MODAL_APPLY_BUTTON = "//*[@data-testid='filter_dialog_apply']"
EVENT_CAMPUS_PLAN_FILTER_PILL_CLOSE_BUTTON = "(//*[contains(@class,'el-icon-close')])[last()]"
EVENT_CAMPUS_PLAN_FILTER_PILL = "//*[contains(@class,'el-icon-close')]//parent::span"
EVENT_CAMPUS_PLAN_FILTER_EVENT = "//*[@class='el-table__body']//*[normalize-space()='{}']"
EVENT_CAMPUS_PLAN_CHECKBOX = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_1')]//span[contains(@class, 'el-checkbox__input')]"
EVENT_CAMPUS_PLAN_EVENT_CHECKBOX = "//td[normalize-space()='{}']//preceding-sibling::td"
EVENT_CAMPUS_PLAN_AREA_NAME_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_13')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_CAMPUS_NAME_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_2')]//div[contains(@class, 'cell')]//span"
EVENT_CAMPUS_PLAN_APPROVAL_STATUS_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_3')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_APPROVAL_STATUS_TABLE_HEADER = "//*[contains(@class, 'scroll-wrapper')]//th[contains(@class, 'column_3')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_APPROVAL_STATUS="(//td[normalize-space()='{}']//preceding-sibling::td)[3]"
EVENT_CAMPUS_PLAN_EVENT_NAME_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_4')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_STATUS_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_5')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_TYPE_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_6')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_DATE_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_7')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_MANAGER_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_8')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_ENGAGEMENT_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_9')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_EVENT_INTERVIEW_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_10')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_PLANNED_EXPENSES_TABLE_DATA_USING_INDEX = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_11')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_ACTUAL_EXPENSES_TABLE_DATA = "//*[contains(@class, 'scroll-wrapper')]//tr[{}]//td[contains(@class, 'column_12')]//div[contains(@class, 'cell')]"
EVENT_CAMPUS_PLAN_SUB_HEADER = "//*[@id='__layout']//*[contains(@data-testid, 'campus_header_lbl_selected')]"
EVENT_CAMPUS_PLAN_SUB_HEADER_CHECKBOX = "//label[contains(@data-testid,'campus_header_cbx_check_all')]//span[contains(@class,'el-checkbox__inner')]"
EVENT_CAMPUS_PLAN_SUB_HEADER_TEXT = "//*[contains(@data-testid,'campus_header_lbl_events_activities')]"
EVENT_CAMPUS_PLAN_TABLE = "//*[contains(@class,'scroll-wrapper')]//table[contains(@class, 'el-table__body')]"
EVENT_CAMPUS_PLAN_TABLE_DATA_ROW ="//*[contains(@class,'scroll-wrapper')]//table[contains(@class, 'el-table__body')]//tbody/tr[{}]"
EVENT_CAMPUS_PLAN_ACTIVITY_DELETE_POPUP = "//span[contains(text(), 'Delete Activity')]"
EVENT_CAMPUS_PLAN_CONFIRM_DELETE_ACTIVITY_BUTTON = "//button[contains(@class, 'danger')]//span[contains(text(), 'Delete activity')]"
EVENT_CAMPUS_PLAN_FILTER_MODAL_CLEAR = "//*[text()='{}']//parent::div//*[normalize-space()='Clear']"
EVENT_CAMPUS_PLAN_FILTER_MODAL_EVENT_MATCH = "//*[@class='el-dialog__footer']//*[contains(text(), 'events match')]"
EVENT_CAMPUS_PLAN_FILTER_NUMBER_OF_OPTION = "//span[text()='{}']//following-sibling::span"
EVENT_CAMPUS_PLAN_METRIC_BUTTON = "//button[@data-testid='campus_header_btn_metric']"
EVENT_CAMPUS_TOTAL_SEGMENT_EVENTS="//div[contains(@class, 'nav-text') and contains(text(), '{}')]//following-sibling::span"
EVENT_CAMPUS_PLAN_METRICS_PLANNED_LABEL = "//*[@data-testid='selected_metrics']//div[@data-testid='selected_metrics_lbl_planned']"
EVENT_CAMPUS_PLAN_METRICS_ACTUAL_LABEL = "//*[@data-testid='selected_metrics']//div[@data-testid='selected_metrics_lbl_actual']"
EVENT_CAMPUS_PLAN_METRICS_UNDER_BUDGET_LABEL = "//*[@data-testid='selected_metrics']//div[@data-testid='selected_metrics_lbl_diff']"
EVENT_CAMPUS_PLAN_METRICS_APPROVAL_STATUSES = "//*[@data-testid='approval_status_metrics_lbl_title']"
REVIEW_NEEDED_LIST_ITEM_EVENT = "//div[@id='menuButton']//div[@class='el-dropdown']//button[contains(@role, 'button')]"
REVIEW_NEEDED_LIST_GO_TO_ACTIVITY_LABEL="//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Go to Activity')]"
EVENT_TAG = "//*[@data-testid='event_lbl_event_name'][text()='{}']"
EVENT_APPROVAL_STATUS_REMOVE_BUTTON = "//*[@data-testid='approval_status_btn_remove']"
EVENT_CAMPUS_PLAN_CONFIRM_METRIC_BUTTON = "//button[@data-testid='campus_header_btn_metric']"
REVIEW_NEEDED_LIST_DELETE_ACTIVITY_LABEL="//ul[contains(@class, 'el-dropdown-menu') and contains(@x-placement, '-end')]//span[contains(text(), 'Go to Activity')]"
EVENT_CAMPUS_PLAN_FILTER_SAVE_SEGMENT = "//*[@data-testid='filter_dialog_save_segment']"
EVENT_CAMPUS_PLAN_FILTER_NEW_SAVE_SEGMENT = "//div[@role='dialog']//div[contains(text(), 'New Segment')]"
EVENT_CAMPUS_PLAN_FILTER_SEGMENT_NAME_TEXTBOX = "//*[@data-testid='filter_save_segment_ipt_segment_name']"
EVENT_CAMPUS_PLAN_FILTER_SEGMENT_NAME_SAVE = "//*[@data-testid='filter_save_segment_save']"
EVENT_CAMPUS_PLAN_SAVED_SEGMENT = "//*[normalize-space()='Segments']//following-sibling::div//*[normalize-space()='{}']"
EVENT_CAMPUS_PLAN_SEGMENT_EXTEND = "//*[normalize-space()='{}']//ancestor::div[@class='menu']//*[contains(@class,'icon-menu')]"
EVENT_CAMPUS_PLAN_SEGMENT_DELETE_TAG = "(//li[normalize-space()='Delete Segment'])[last()]"
EVENT_CAMPUS_PLAN_SEGMENT_RENAME_TAG = "(//li[normalize-space()='Rename Segment'])[last()]"
EVENT_CAMPUS_PLAN_SEGMENT_REORDER_TAG = "(//li[normalize-space()='Reorder'])[last()]"
EVENT_CAMPUS_PLAN_SEGMENT_DELETE_MODAL = "//div[@role='dialog']//span[normalize-space()='Delete Segment']"
EVENT_CAMPUS_PLAN_SEGMENT_DELETE_BUTTON = "//div[@role='dialog']//span[normalize-space()='Delete']"
EVENT_CAMPUS_PLAN_SEGMENT_POPUP = "//*[contains(@class, 'ol-confirm')]//span[contains(text(), '{}')]"
EVENT_CAMPUS_PLAN_SEGMENT_REORDER_POPUP = "//*[contains(@class, 'el-dialog__title') and normalize-space()='Reorder Segments']"
EVENT_CAMPUS_PLAN_SEND_APPROVAL_BUTTON = "//*[@data-testid='campus_header_btn_send_approval']"
EVENT_CAMPUS_PLAN_APPROVE_EVENT_BUTTON = "//*[@data-testid='campus_header_btn_approve_event']"
EVENT_CAMPUS_PLAN_DENY_EVENT_BUTTON = "//*[@data-testid='campus_header_btn_deny']"
EVENT_CAMPUS_PLAN_DENY_EVENT_MODAL = "//div[@role='dialog']//span[text()='Deny Events & Activities']"
EVENT_CAMPUS_PLAN_CLOSE_MODAL_BUTTON = "//div[@role='dialog']//button[@aria-label='Close']"
EVENT_CAMPUS_PLAN_CONFIRM_MODAL_BUTTON = "//div[@role='dialog']//button[contains(@class,'primary')]//span[text()='Confirm']"
EVENT_CAMPUS_PLAN_SEND_APPROVAL_MODAL = "//div[@role='dialog']//span[text()='Send Event and Activities for Approval']"
EVENT_CAMPUS_PLAN_CONFIRM_AND_SEND_BUTTON = "//div[@role='dialog']//button[contains(@class,'primary')]//span[normalize-space()='Confirm and Send']"
EVENT_CAMPUS_PLAN_FILTER_LIST = "//*[@data-testid='filter_list_item_cbx_group']"
EVENT_CAMPUS_PLAN_FILTER_CHECKBOX = "//*[contains(@data-testid, 'filter_list_item_cbx')]//*[text()='{}']//ancestor-or-self::span//preceding-sibling::span//input"
EVENT_CAMPUS_PLAN_METRICS_TOTAL_PLANNED_PRICE_LABEL = "//*[@data-testid='total_metrics_lbl_planned']"
EVENT_CAMPUS_PLAN_PLANNED_EXPENSES_TABLE_DATA_USING_NAME = "(//td[normalize-space()='{}']//following-sibling::td)[last()-1]"
EVENT_CAMPUS_PLAN_APPROVAL_STATUS_METRIC = "//*[@data-testid='approval_status_metrics']//span[contains(text(), '{}')]//preceding-sibling::span"
EVENT_CAMPUS_PLAN_CAMPUS_PLAN_LABEL="//*[contains(@class, 'nav-text') and normalize-space(text())='{}']"
EVENT_CAMPUS_PLAN_TOTAL_STATUS_OF_EVENTS="//*[contains(@class, 'nav-text') and normalize-space(text())='{}']//following-sibling::div"
EVENT_APPROVAL_STATUS_CONFIRM_REMOVE_BUTTON = "//div[@aria-label='Remove event from approval process']//button[normalize-space()='Confirm']"
EVENT_CAMPUS_PLAN_DRAFT_CHECKBOX="//*[@data-testid='filter_list_item_cbx_selection1']//span[contains(@class, 'el-checkbox__inner')]"
EVENT_CAMPUS_PLAN_DENIED_CHECKBOX="//*[@data-testid='filter_list_item_cbx_selection4']//span[contains(@class, 'el-checkbox__inner')]"
EVENT_CAMPUS_PLAN_YOUR_REVIEW_CHECKBOX="//*[@data-testid='filter_list_item_cbx_selection5']//span[contains(@class, 'el-checkbox__inner')]"

