# FORM LIST
CANDIDATE_FORM_TAB = "//div[contains(text(),'Candidate Forms')]"
USER_FORM_TAB = "//div[contains(text(),'User Forms')]"
MENU_ICON_BY_FORM_NAME_TO_DELETE = "//div[contains(text(), '{}')]//ancestor::tr//div[contains(text(), '0 Jobs')]//ancestor::tr//i[contains(@class, 'icon-menu')]"
CANDIDATE_FORM_TITLE = "//div[contains(@class, 'content-title') and contains(text(),'Candidate Forms')]"
USER_FORM_TITLE = "//div[contains(@class, 'content-title') and contains(text(),'User Forms')]"
SEARCH_FORM_TEXTBOX = "//input[contains(@placeholder,'Search form')]"
FORM_BY_NAME = "//tbody//*[normalize-space(text())='{}']"
MENU_ICON_BY_FORM_NAME = "//*[contains(text(), '{}')]//ancestor::tr//i[contains(@class, 'icon-menu')]"
EDIT_FORM_ICON = "(//i[contains(@class, 'icon-edit')])[last()]"
DUPLICATE_FORM_ICON = "(//i[contains(@class, 'icon-duplicate-o')])[last()]"
PREVIEW_FORM_ICON = "(//i[contains(@class, 'icon-preview')])[last()]"
DELETE_FORM_ICON = "(//i[contains(@class, 'icon-delete')])[last()]"
CANCEL_DIALOG_BUTTON = "(//button[contains(@class, 'button--default')]//span[contains(text(), 'Cancel')])[last()]"
CONFIRM_DELETE_DIALOG_BUTTON = "(//button[contains(@class, 'button--danger')]//span[contains(text(), 'Delete')])[last()]"

# FORM CREATE
NEW_CANDIDATE_FORM_BUTTON = "//button[contains(@class,'button--primary')]//span[contains(text(),'New Candidate Form')]"
NEW_USER_FORM_BUTTON = "//button[contains(@class,'button--primary')]//span[contains(text(),'New User Form')]"
EDIT_FORM_NAME_ICON = "//*[contains(@data-testid, 'form_builder_input_name')]//i[contains(@class, 'icon-edit')]"
FORM_NAME_TEXTBOX = "//*[contains(@data-testid,'form_builder_input_name')]//input[contains(@data-testid, 'naming_input_base')]"
FORM_ADD_TASK_BUTTON = "//button[contains(@class,'button--text')]//span[contains(text(), 'Add Task')]"
FORM_ADD_TASK_OPTION = "//li[contains(@class,'dropdown-menu')]//span[contains(text(), '{}')]"
FORM_ADD_SECTION_BUTTON = "//button[contains(@class,'button--text')]//span[contains(text(), 'Add Section')]"
FORM_SECTION_TYPE = "//*[contains(@class, 'el-dropdown-menu__item')]//span[normalize-space(text())='{}']"
FORM_GO_TO_SECTION_DETAIL_ICON = "//div[(text() = '{}')]/parent::div/parent::div//i[contains(@class, 'icon-chevron')]"
FORM_ADD_SECTION_OPTION = "//li[contains(@class,'dropdown-menu')]//span[contains(text(), '{}')]"
FORM_HEADER_SECTION = "//*[@id='item-list-header']"
FORM_SECTION_EDIT_NAME_ICON = "//*[@data-testid='form_builder_input_section_name']//i[contains(@class, 'icon-edit')]"
FORM_SECTION_NAME_TEXTBOX = "//*[@data-testid='form_builder_input_section_name']//input[contains(@data-testid, 'naming_input_base')]"
FORM_UPLOAD_FILE = "//input[@type='file']"
FORM_DOCUMENT_NAME = "(//*[contains(@data-testid, 'form_builder_input_task_name')]//input[contains(@placeholder, 'Add a title')])[last()]"
FORM_TASK_NAME_TEXTBOX = "//input[contains(@placeholder, 'Name your task')]"
EDIT_TITLE_NAME_ICON = "(//*[contains(@data-testid, 'form_builder_input_task_name')])[last()]"
TITLE_NAME_TEXTBOX = "//*[contains(@data-testid, 'form_builder_input_task_name')]//input[contains(@data-testid, 'naming_input_base')]"
LAST_TITLE_NAME_TEXTBOX = "(//*[contains(@data-testid, 'form_builder_input_task_name')]//input[contains(@data-testid, 'naming_input_base')])[last()]"
FORM_CONTENT_SECTION_TEXTAREA = "//*[contains(@data-placeholder, 'Add body text')]"
FORM_CONTENT_SECTION_TEXTAREA_2 = "(//*[contains(@data-placeholder, 'Add body text')])[2]"
FORM_CONTENT_SECTION_TEXTAREA_3 = "(//*[contains(@data-placeholder, 'Add body text')])[3]"
FORM_CONTENT_SECTION_TEXTAREA_4 = "(//*[contains(@data-placeholder, 'Add body text')])[4]"
FORM_CONTENT_SECTION_TEXTAREA_LAST = "(//*[contains(@data-placeholder, 'Add body text')])[last()]"
FORM_SECTION_SAVE_BUTTON = "//*[contains(@to,'bottom-form-builder')]//button[contains(@class,'button--primary')]//span[contains(text(),'Save')]"
FORM_SECTION_CANCEL_BUTTON = "//*[contains(@to,'bottom-form-builder')]//button[contains(@class,'button--default')]//span[contains(text(),'Cancel')]"
QUESTION_NAME_TEXTBOX = "//*[contains(@data-testid, 'form_builder_input_task_name')]//*[@contenteditable='true']"
LAST_QUESTION_NAME_TEXTBOX = "(//*[contains(@data-testid, 'form_builder_input_task_name')]//*[@contenteditable='true'])[last()]"
QUESTION_NAME_TEXTBOX_BY_QUESTION_NAME = "//*[contains(@data-testid, 'form_builder_input_task_name')]//*[@contenteditable='true' and contains(text(),'{}')]"
QUESTION_RESPONSE_TYPE_DROPDOWN_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_select_response')]//input"
QUESTION_RESPONSE_TYPE_OPTION = "(//li[contains(@class,'select-dropdown')]//span[contains(text(), '{}')])[last()]"
FORM_TYPE_YOUR_QUESTION_INPUT = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//input[contains(@placeholder, 'Type your option')]"
FORM_LAST_TYPE_YOUR_QUESTION_INPUT = "(//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//input[contains(@placeholder, 'Type your option')])[last()]"
FORM_ADD_OPTION_YOUR_QUESTION_BUTTON = "//button[contains(@data-testid,  'form_builder_btn_add_option')]//span[contains(text(), 'Add Option')]"
FORM_REMOVE_TYPE_YOUR_QUESTION_ICON = "//i[contains(@class, 'icon icon-remove pointer')]"
REQUIRED_TOGGLE_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-test-id,'form_builder_required_toggle')]"
ELLIPSES_ICON_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//i[contains(@class,'icon-horizontal-menu')]"
ELLIPSES_ICON_DIGITAL_CONSENT = "//*[contains(text(),'Digital Consent')]//parent::div//i[contains(@class, 'icon-horizontal-menu')]"
ADD_VALIDATE_ICON = "(//i[contains(@class,'icon-validate')])[last()]"
FORM_ADD_DIGITAL_CONSENT_ICON = "(//i[contains(@class,'icon-reorder')])[last()]"
FIELD_MAPPING_ICON = "(//i[contains(@class,'icon-ats-map')])[last()]"
DUPLICATE_CUSTOM_QUESTION_ICON = "(//i[contains(@class,'icon-copy')])[last()]"
DELETE_CUSTOM_QUESTION_ICON = "(//i[contains(@class,'icon-delete2')])[last()]"
FIELD_MAPPING_ICON_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//..//..//..//..//following-sibling::div//i[contains(@class,'icon-ats-map')]"
CHECKBOX_SENSITIVE_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_checkbox_sensitive')]//span[contains(@class, 'el-checkbox__input')]"
CHECKBOX_HIDE_FROM_MANAGER_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_checkbox_hide-from-manager')]//span[contains(@class, 'el-checkbox__input')]"
CHECKBOX_ALLOW_MULTI_SELECT_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_checkbox_allow_multiple')]//span[contains(@class, 'el-checkbox__input')]"
CHECKBOX_ADD_CONFIRMATION_FIELD_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_checkbox_confirmation')]//span[contains(@class, 'el-checkbox__inner')]"
SEARCH_LOCATION_LOOKUP_INPUT = "//div[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//following-sibling::div//input[contains(@placeholder, 'Search Location')]"
SEARCH_NAME_LOOKUP_INPUT = "//div[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//following-sibling::div//input[contains(@placeholder, 'Search Name')]"
VALIDATION_DROPDOWN_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//*[contains(@data-testid,'form_builder_select_validation')]"
VALIDATION_DROPDOWN_OPTION = "(//li[contains(@class,'select-dropdown')]//span[contains(text(), '{}')])[last()]"
FORM_STATUS_BAR_BUTTON = "//button[@data-testid='form_status_bar_btn_publish_dropdown']"
FROM_STATUS_BAR_PUBLISHED_VIEW_BUTTON = "//*[@data-testid='form_status_bar_btn_published_view']"
FORM_PUBLISH_BUTTON = "//button[@data-testid='form_status_bar_btn_publish']"
FORM_PUBLISHED_STATUS = "//div[@id='form-version-control']//span[contains(text(), 'Published')]"
FORM_SETTING_ICON = "//*[contains(@data-testid,'btn_show_menu')]//i[contains(@class,'icon-settings')]"
FORM_DUPLICATE_ICON = "(//i[contains(@class, 'icon-copy')])[last()]"
FORM_PREVIEW_ICON = "(//*[contains(@data-testid, 'form_builder_drop_setting_preview')])[last()]"
FORM_ADD_TRACKING_PIXEL_ICON = "(//*[contains(@data-testid, 'form_builder_drop_tracking_pixel')])[last()]"
FORM_ADD_TRACKING_PIXEL_CONTENT_PRESENTATION = "//div[contains(@class, 'vue-codemirror')]//div//span[@role = 'presentation']"
FORM_ADD_TRACKING_PIXEL_CONTENT_TEXTAREA = "//div[contains(@class, 'vue-codemirror')]//pre[@role='presentation']"
FORM_ADD_TRACKING_PIXEL_CANCEL_BUTTON = "//div[contains(@data-testid, 'form_builder_drop_tracking_pixel')]//button//*[contains(text(), 'Cancel')]//parent::*//parent::button"
FORM_ADD_TRACKING_PIXEL_SAVE_BUTTON = "//div[contains(@data-testid, 'form_builder_drop_tracking_pixel')]//button//*[contains(text(), 'Save')]//parent::*//parent::button"
FORM_ADD_TRACKING_PIXEL_SCRIPT = "//script[contains(text(), '{}')]"
FORM_ADD_WIDGET_ON_FORM_TOGGLE = "(//*[contains(@data-testid, 'form_builder_setting_switch_add_widget')])[last()]"
FORM_DELETE_TASK_ICON = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//i[contains(@class, 'icon-delete')]"
FORM_SYSTEM_ATTRIBUTE_BY_NAME = "//*[contains(@class, 'mention-item')]//strong[contains(text(), '{}')]"

# MULTILINGUAL
FORM_MULTILINGUAL_ICON = "//button//*[contains(@class, 'icon-multilingual')]"
FORM_MULTILINGUAL_LANGUAGE = "//button//*[contains(@class, 'icon-multilingual')]//following-sibling::*//span[contains(text(), '{}')]"
FORM_MULTILINGUAL_SEARCH_LANGUAGES_INPUT = "//input[@placeholder='Search Languages']"
FORM_MULTILINGUAL_DEFAULT_LANGUAGE = "//li[contains(text(), '{}')]//*[contains(text(), 'default')]//following-sibling::*[contains(@class, 'icon-check')]"
FORM_MULTILINGUAL_LANGUAGE_LIST = "//div[contains(@class, 'el-select-dropdown')]//li[contains(text(), '{}')]"
FORM_MULTILINGUAL_CONFIG_LANGUAGES_BUTTON = "//button//span[contains(text(), 'Configure Languages')]"
FORM_MULTILINGUAL_SELECT_ALL_LANGUAGES_BUTTON = "//div[contains(@id, 'el-popover')]//span[contains(text(), 'Select all')]"
FORM_MULTILINGUAL_LANGUAGE_CHECKBOX = "//span[contains(text(), '{}')]//ancestor::label//*[contains(@class,'el-checkbox__input')]"
FORM_MULTILINGUAL_LANGUAGE_CANCEL_BUTTON = "//*[@data-testid='languagedropdown_btn_cancel']"
FORM_MULTILINGUAL_LANGUAGE_APPLY_BUTTON = "//*[@data-testid='languagedropdown_btn_apply']"
FORM_MULTILINGUAL_ADDING_LANGUAGE_NUMBER = "//div[contains(@class, 'el-message-box')]//*[contains(@class, 'icon-plus')]//following-sibling::*[contains(., 'Adding ({}) Language{}')]"
FORM_MULTILINGUAL_ADDED_LANGUAGES_TEXT = "//div[contains(@class, 'el-message-box__message')]//li[contains(text(), '{}')]"
FORM_MULTILINGUAL_REMOVING_LANGUAGE_NUMBER = "//div[contains(@class, 'el-message-box')]//*[contains(@class, 'icon-minus')]//following-sibling::*[contains(., 'Removing ({}) Language{}')]"
FORM_MULTILINGUAL_CONFIRM_ADD_LANGUAGE_BUTTON = "//div[contains(@class, 'el-message-box')]//*[contains(text(), 'Confirm')]"

# ADDRESS FORM TASK
CHECKBOX_SENSITIVE_ADDRESS_TASK_QUESTION = "//*[contains(text(),'{}')]//parent::div//*[contains(@data-testid,'address_item_check_box_is_sensitive')]//span[contains(@class, 'el-checkbox__inner')]"
CHECKBOX_HIDE_FROM_MANAGER_ADDRESS_TASK_QUESTION = "//*[contains(text(),'{}')]//parent::div//*[contains(@data-testid,'address_item_check_box_is_hidden')]//span[contains(@class, 'el-checkbox__inner')]"
ADDRESS_TASK_ICON_LOCK =  "//*[contains(text(),'{}')]//parent::div//*[contains(@class,'icon-locked')]"
ADDRESS_TASK_ICON_ATS_MAP =  "//*[contains(text(),'{}')]//parent::div//parent::div//button[contains(@class, 'icon-ats-map')]"
ADDRESS_TASK_ICON_DELETE =  "//*[contains(text(),'{}')]//parent::div//parent::div//button[contains(@class, 'icon-delete2')]"

# DATE SELECTION FORM TASK
REQUIRED_TOGGLE_BY_DATA_TEST_ID = "//*[contains(@data-test-id,'form_builder_required_toggle')]"

# FILLABLE FORM PDF
FORM_FILLABLE_PDF_SUBMIT_FORM_BUTTON = "(//button[@data-testid='fillable_pdf_item_user_form_cem_dialog_btn_submit'])[last()]"
FRAME_PDF_FILLABLE = "//*[contains(@id, 'webviewer')]"
FORM_FILLABLE_PDF_INPUT_NAME = "//input[contains(@title, 'Employee Name')]"
FORM_FILLABLE_PDF_INPUT_DATE = "//input[contains(@title, 'Date')]"
FORM_FILLABLE_PDF_INPUT_SS = "//input[contains(@title, 'SS')]"
FORM_FILLABLE_PDF_INPUT_SIGNATURE = "//div[contains(@id, 'Employee Signature')]//input"
FORM_UPLOAD_REMOVE_BUTTON = "//*[contains(@data-testid,'form_builder_upload_remove_btn')]"
FORM_FILLABLE_PDF_READY_SUBMIT_CHECKBOX = "(//*[@data-testid='ready_submit_fillable_pdf_item_user_form_cem_dialog_cbx'])[last()]"

# VERIFICATION CODE
CODE_INPUT = "(//input[contains(@inputmode, 'numeric')])[{}]"

#  Form Experience screen
FORM_EXPERIENCE_YOUR_ANSWER_INPUT = "//input[contains(@data-testid, 'single_line_user_form_cem_input')]"
FORM_EXPERIENCE_YOUR_ANSWER_SINGLE_LINE_INPUT = "(//input[contains(@data-testid, 'single_line_user_form_cem_input')])[last()]"
FORM_EXPERIENCE_YOUR_ANSWER_SINGLE_LINE_CONFIRMATION_INPUT = "(//input[contains(@data-testid, 'single_line_confirmation_input')])[last()]"
FORM_EXPERIENCE_STATUS_SEND_FORM = "//label[contains(@data-testid, 'status_user_form_cem_select')]//span[contains(text(), 'Send Form')]"
FORM_EXPERIENCE_NEXT_BUTTON = "//button[contains(@data-testid, 'drawer_user_form_cem_btn_next')]//span[contains(text(), 'Next')]"
FORM_EXPERIENCE_SAVE_AND_CONFIRM_BUTTON = "//button[contains(@data-testid, 'drawer_user_form_cem_btn_save')]//span[contains(text(), 'Save & confirm')]"
FORM_SHOW_MENU_BUTTON = "//div[contains(@data-testid, 'btn_show_menu')]//i[contains(@class , 'icon-chevron-down')]"
FORM_OPTION_CHECK_BOX = "//input[contains(@value, '{}')]//ancestor::label[contains(@data-testid, 'multiselect_item_user_form_cem_cbx')]"
FORM_MULTI_SELECT_ITEM_APPLY_BUTTON = "//*[contains(@data-testid, 'multiselect_item_user_form_cem_filter_dialog_apply_btn')]//span[contains(text(), 'Apply')]"
FORM_SEARCH_FOR_ITEM_INPUT = "//div[contains(@data-testid, 'input_search')]//input[contains(@placeholder, 'Search for Drop-Down Answers')]"
FORM_ITEM_TASK_DROP_DOWN = "//div[contains(@data-testid, 'lbl_title') and (contains(text(), '{}'))]"
FORM_ITEM_RADIO_MULTI_CHOSE =  "//label[contains(@data-testid, 'single_select_user_form_cem_radio')]//input[contains(@value, '{}')]"
FORM_INPUT_TEXT_PARAGRAPH_TEXTAREA = "//textarea[contains(@data-testid,'multiple_line_user_form_cem_input')]"
FORM_CEM_EXPERIENCE_NEXT_BUTTON = "//button[contains(@data-testid, 'drawer_user_form_cem_btn_next')]"
FORM_EXPERIENCE_DRAWER_FORM_CEM_SAVE_BUTTON = "//button[contains(@data-testid, 'drawer_user_form_cem_btn_save')]"

# Candidate Experience form
FORM_DIGITAL_CONSENT_BUTTON_CANCEL = "(//button[contains(@class, 'button--default')]//span[contains(text(), 'Cancel')])[last()]"
FORM_DIGITAL_CONSENT_BUTTON_AGREE = "(//button[contains(@class, 'button--primary')]//span[contains(text(), 'I Agree')])[last()]"
FORM_DIGITAL_CONSENT_BUTTON_EXIT_FORM = "//button[contains(@class, 'button--default')]//span[contains(text(), 'Exit Form')]"
FORM_DIGITAL_CONSENT_BUTTON_REVIEW_CONSENT = "//button[contains(@class, 'button--primary')]//span[contains(text(), 'Review Consent')]"
FORM_DIGITAL_CONSENT_ICON_CLOSE = "(//*[contains(@class, 'ol-confirm')]//*[contains(@class, 'icon-close')])[last()]"
FORM_ITEM_LABEL = "//*[contains(@class, 'form-experience-item__question') and contains(text(), '{}')]"
FORM_QUESTION_LABEL = "//*[@data-testid='item_title_user_form_cem_lbl' and contains(text(), '{}')]"
FORM_ITEM_FIELD = "//*[@data-testid='item_title_user_form_cem_lbl' and contains(text(), '{}')]"
FORM_ITEM_LABEL_ERROR = "//*[@data-testid='item_title_user_form_cem_lbl' and contains(text(), '{}')]/parent::div//span[contains(@data-testid, 'item_validate_message_user_form_cem_lbl')]"
FORM_GET_STARTED_LINK = "//*[@data-testid='fillable_pdf_item_user_form_cem_btn_open_preview_dialog']//*[contains(text(), 'Get started')]"
FORM_FILLABLE_PDF_FILE_NAME = "//*[@data-testid='fillable_pdf_item_user_form_cem_btn_open_preview_dialog']//span[contains(text(), '{}')]"
FORM_FILLABLE_PDF_DIGITAL_CONSENT_CHECKBOX = "//*[contains(@data-testid, 'consent_fillable_pdf_item_user_form_cem_cbx')]//input[@type='checkbox']"
FORM_FILLABLE_PDF_ICON_CHECK = "//*[contains(@data-testid, 'fillable_pdf_item_user_form_cem_link')]//i[contains(@class,'icon-check')]"
FORM_DOCUMENT_REVIEW_FILE_NAME = "//*[@data-testid='file_name_document_review_user_form_cem_lbl' and contains(text(), '{}')]"
FORM_DOCUMENT_REVIEW_DIGITAL_CONSENT_CHECKBOX = "//*[contains(@data-testid, 'consent_document_review_user_form_cem_cbx')]//input[@type='checkbox']"
FORM_DOCUMENT_REVIEW_VIEW_LINK = "//*[@data-testid='document_review_user_form_cem_link']//*[contains(text(), 'View')]"
FORM_I9_FORM_NAME_CANDIDATE_EXPERIENCE_FORM = "//*[contains(@data-testid, 'i9_form_name_candidate_experience_form') and contains(text(), '{}')]"
FORM_I9_FORM_NAME_GET_STARTED_BUTTON = "//*[contains(@data-testid, 'i9_candidate_experience_form_link')]//*[contains(text(), 'Get started')]"
FORM_I9_FORM_NAME_BUTTON = "//*[contains(@data-testid, 'i9_candidate_experience_form_link')]"
FORM_I9_FORM_NAME_CHECK_ICON = "//*[contains(@data-testid, 'i9_candidate_experience_form_link')]//div//*[contains(@class, 'icon-check')]"
FORM_FIRST_NAME_TEXTBOX = "//input[@placeholder='First name']"
FORM_ITEM_ANSWER_FIRST_NAME_TEXTBOX = "(//div[contains(@class, 'form-experience-item')]//input[@placeholder='First name'])[last()]"
FORM_MIDDLE_NAME_TEXTBOX = "//input[@placeholder='MI']"
FORM_LAST_NAME_TEXTBOX = "//input[@placeholder='Last name']"
FORM_ITEM_ANSWER_LAST_NAME_TEXTBOX = "(//div[contains(@class, 'form-experience-item')]//input[@placeholder='Last name'])[last()]"
FORM_PHONE_NUMBER_TEXTBOX = "//*[contains(text(), 'Phone number')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_EMAIL_ADDRESS_TEXTBOX = "//*[contains(text(), 'Email address')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_STREET_ADDRESS_LINE_1_TEXTBOX = "//*[contains(text(), 'Street address (Line 1)')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_STREET_ADDRESS_LINE_2_TEXTBOX = "//*[contains(text(), 'Street address (Line 2)')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_CITY_TEXTBOX = "//*[contains(text(), 'City')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_STATE_TEXTBOX = "//*[contains(text(), 'State')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_ZIPCODE_TEXTBOX = "//*[contains(text(), 'ZIP code')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_EXPERIENCE_INPUT = "//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_PHONE_NUMBER_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'Phone number')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_EMAIL_ADDRESS_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'Email address')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_STREET_ADDRESS_LINE_1_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'Street address (Line 1)')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_CITY_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'City')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_STATE_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'State')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_ZIPCODE_CONFIRMATION_TEXTBOX = "//*[contains(text(), 'ZIP code')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"
FORM_NEXT_SECTION_BUTTON = "//button[contains(@class, 'button--primary')]//span[contains(text(), 'Next Section')]"
FORM_SUBMIT_BUTTON = "//button[contains(@class, 'button--primary')]//span[contains(text(), 'Submit')]"
FORM_REVIEW_BUTTON = "//button[contains(@class, 'button--primary')]//span[contains(text(), 'Review')]"
FORM_VALIDATE_MESSAGE = "//*[@data-testid='item_validate_message_user_form_cem_lbl' and contains(text(), '{}')]"
FORM_ICON_CHECK_BY_TASK_NAME = "//*[contains(text(), '{}')]//parent::*//*[contains(@class, 'icon-check')]"
FORM_DATE_PICKER = "(//input[@placeholder = 'Select Date'])[last()]"
FORM_DOCUMENT_REVIEW_TITLE = "//*[contains(@class, 'form-experience-item') and contains(text(), '{}')]"
FORM_EXPERIENCE_SELECT_DATE = "//div[contains(@data-testid, 'date_picker_user_form_cem')]"
FORM_EXPERIENCE_START_DATE_SELECT = "//*[contains(text(), 'Date started')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//div[@data-testid='date_picker_user_form_cem']"
FORM_EXPERIENCE_START_DATE_INPUT = "//*[contains(text(), 'Date started')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='date_picker_user_form_cem']//following-sibling::input"
FORM_EXPERIENCE_END_DATE_SELECT = "//*[contains(text(), 'Date ended')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//div[@data-testid='date_picker_user_form_cem']"
FORM_EXPERIENCE_END_DATE_INPUT = "//*[contains(text(), 'Date ended')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='date_picker_user_form_cem']//following-sibling::input"
FORM_EXPERIENCE_DATE_CONFIRMATION_SELECT = "//div[contains(@data-testid, 'date_picker_confirmation_input')]"
FORM_EXPERIENCE_DATE_TO_SELECT = "(//span[contains(@aria-label, '{}')])[1]"
FORM_EXPERIENCE_DATE_CONFIRM_TO_SELECT = "(//span[contains(@aria-label, '{}')])[last()]"
FORM_EXPERIENCE_OPTION_SELECT = "//label[contains(text(), '{}')]//parent::div[contains(@class, 'form-experience-item')]//following-sibling::div[contains(@class, 'answer')]"
FORM_EXPERIENCE_ADD_ANOTHER_WORKPLACE_BUTTON = "//button[contains(@class, 'el-button')]//span[contains(text(), 'Add another workplace')]"
FORM_EXPERIENCE_REMOVE_WORKPLACE_BUTTON = "//*[contains(text(), '{}')]//parent::div//span[contains(text(), 'Remove')]"
FORM_EXPERIENCE_REMOVE_RESPONSE_BUTTON = "//button//*[contains(text(), 'Remove Response')]"
FORM_EXPERIENCE_BANK_ACCOUNT_SELECT = "//span[contains(@data-testid, 'dropdown_user_form_cem')]//div[contains(@data-testid, 'btn_show_menu')]"
FORM_EXPERIENCE_JOB_TITLE_ANSWER = "//h5[contains(text(), '{}')]//parent::div//following-sibling::div//*[contains(text(), 'Your Job title')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_EXPERIENCE_COMPANY_NAME_ANSWER = "//h5[contains(text(), '{}')]//parent::div//following-sibling::div//*[contains(text(), 'Company name')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_EXPERIENCE_JOB_LOCATION_ANSWER = "//h5[contains(text(), '{}')]//parent::div//following-sibling::div//*[contains(text(), 'Location')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_EXPERIENCE_JOB_DATE_SELECT = "//h5[contains(text(), '{}')]//parent::div//following-sibling::div//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//div[@data-testid='date_picker_user_form_cem']"
FORM_EXPERIENCE_JOB_DATE_INPUT = "//h5[contains(text(), '{}')]//parent::div//following-sibling::div//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//div[@data-testid='date_picker_user_form_cem']//following-sibling::input"
FORM_EXPERIENCE_EDIT_SECTION_BUTTON = "//span[contains(text(), '{}')]//parent::div//parent::div//span[contains(text(), 'Edit Section')]"
FORM_DIVERSITY_SECTION_DROPDOWN_BY_QUESTION_NAME = "//*[contains(text(), '{}')]//parent::div//parent::*[contains(@class, 'form-experience-item')]//*[@data-testid='single_select_user_form_cem_dropdown']"
FORM_DIVERSITY_SECTION_RADIO_ANSWER_BY_NAME = "//label[@role='radio']//*[contains(text(), '{}')]"
FORM_DIVERSITY_SECTION_APPLY_BUTTON = "(//button[contains(@class, 'button--primary')]//*[contains(text(), 'Apply')])[last()]"
FORM_DIVERSITY_SECTION_RADIO_BUTTON_BY_NAME = "//*[@data-testid='single_select_user_form_cem_radio']//*[contains(text(), '{}')]"
FORM_ANSWER_TEXTBOX_BY_QUESTION_NAME = "//*[contains(text(), '{}')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_user_form_cem_input']"
FORM_CONFIRMATION_ANSWER_TEXTBOX_BY_QUESTION_NAME = "//*[contains(text(), 'Confirmation_question')]//ancestor::*[contains(@class, 'question')]//following-sibling::*//input[@data-testid='single_line_confirmation_input']"

# Field mapping modal
FORM_MAPPING_FIELD_MODAL = "(//div[contains(@class, 'el-dialog__wrapper') and contains(@data-testid, 'mapping_field_modal')])[last()]"
FORM_MAPPING_MODAL_SOURCE_FIELD = "(//*[@data-testid = 'mapping_modal_source_field'])[last()]"
FORM_MAPPING_MODAL_ATS_SOURCE_FIELD = "(//*[@data-testid = 'form_builder_ats_source_select'])[last()]"
FORM_MAPPING_MODAL_ATS_SOURCE_FIELD_OPTION = "(//*[contains(@data-testid, 'form_builder_ats') and contains(text(), '{}')])[last()]"
FORM_MAPPING_MODAL_ATS_SOURCE_FIELD_SELECT_OPTION = "(//*[contains(@data-testid, 'ats_source_option')])[last()]"
FORM_MAPPING_MODAL_ATS_DESTINATION_FIELD = "(//*[contains(@placeholder, 'Enter a field mapping')])[last()]"
FORM_MAPPING_MODAL_SYSTEM_ATTRIBUTE = "(//*[@data-testid = 'mapping_modal_sys_attr'])[last()]"
FORM_MAPPING_MODAL_DESTINATION_FIELD = "(//*[@data-testid = 'mapping_modal_destination_field'])[last()]"
FORM_MAPPING_MODAL_SOURCE_FIELD_INPUT = "(//*[@data-testid = 'mapping_modal_source_field']//input)[last()]"
FORM_MAPPING_MODAL_ATS_SOURCE_FIELD_INPUT = "(//*[contains(@data-testid, 'form_builder_ats_source_select')]//input)[last()]"
FORM_MAPPING_MODAL_SYSTEM_ATTRIBUTE_INPUT = "(//*[@data-testid = 'mapping_modal_sys_attr']//input)[last()]"
FORM_MAPPING_MODAL_SOURCE_FIELD_OPTION = "(//*[contains(@data-testid, 'mapping_modal_source_field_option')]//*[contains(text(), '{}')])[last()]"
FORM_MAPPING_MODAL_SOURCE_FIELD_OPTION_SELECTED = "(//*[contains(@data-testid, 'mapping_modal_source_field_option') and contains(@class, 'selected')]//*[contains(text(), '{}')])[last()]"
FORM_MAPPING_MODAL_SYSTEM_ATTRIBUTE_OPTION = "//*[contains(@data-testid, 'mapping_modal_sys_attr_option')]//*[contains(text(), '{}')]"
FORM_MAPPING_MODAL_SYSTEM_ATTRIBUTE_OPTION_SELECTED = "(//*[contains(@data-testid, 'mapping_modal_sys_attr_option') and contains(@class, 'selected')]//*[contains(text(), '{}')])[last()]"
FORM_MAPPING_MODAL_SAVE_BUTTON = "(//div[contains(@class, 'dialog-footer')]//*[contains(text(), 'Save')])[last()]"
FORM_MAPPING_FIELD_ATS_MODAL_SAVE_BUTTON = "(//div[contains(@data-testid, 'form_builder_ats_dialog')]//button//span[contains(text(), 'Save')])[{}]"
FORM_MAPPING_FIELD_ATS_MODAL_CANCEL_BUTTON = "(//div[contains(@data-testid, 'form_builder_ats_dialog')]//button//span[contains(text(), 'Cancel')])[{}]"
FORM_MAPPING_MODAL_CANCEL_BUTTON = "(//div[contains(@class, 'dialog-footer')]//*[contains(text(), 'Cancel')])[last()]"
FORM_MAPPING_MODAL_REMOVE_BUTTON = "(//div[contains(@class, 'dialog-footer')]//*[contains(text(), 'Remove')])[last()]"
FORM_MAPPING_ELLIPSES_ICON_BY_QUESTION_NAME = "//*[contains(text(),'{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//i[contains(@class,'icon-horizontal-menu')]"
FORM_MAPPING_ICON_ATS_MAP =  "//*[contains(text(), '{}')]//parent::div//parent::div//parent::div//parent::div//parent::div//button//*[contains(@class, 'icon-ats-map')]"
FORM_MAPPING_MODAL_STORE_ATTRIBUTE = "//*[contains(text(), 'Store Attribute')]//following-sibling::div//input"
FORM_MAPPING_MODAL_STORE_ATTRIBUTE_OPTION = "//*[contains(@data-testid, 'store-attribute_option')]//parent::ul//child::*//*[contains(text(), '{}')]//parent::li"

# Form Candidate Experience
# Federal tax forms
FORM_TAX_REQUIRED_FIELD = "//*[contains(@data-testid, 'fillable_pdf_item_user_form_cem_btn_open_preview_dialog') and contains(., '{}')]//following-sibling::span[contains(text(), 'This Field is Required')]"
FORM_TAX_READY_SUBMIT_CHECKBOX = "(//label[contains(@data-testid, 'ready_submit_fillable_pdf_item_user_form_cem_dialog_cbx')]//span[contains(text(), 'By checking this box, I agree to digitally sign this document.')])[last()]"
FORM_TAX_GET_START_LINK = "//*[contains(@data-testid, 'fillable_pdf_item_user_form_cem_btn_open_preview_dialog') and contains(., '{}')]//*[contains(text(), 'Get started')]"
FORM_TAX_VIEW_LINK = "//*[contains(@data-testid, 'fillable_pdf_item_user_form_cem_link') and contains(., '{}')]//*[contains(text(), 'View')]"
FORM_FILLABLE_PDF_ICON_CHECK_BY_FORM_NAME = "//*[contains(@data-testid, 'fillable_pdf_item_user_form_cem_link') and contains(., '{}')]//*[contains(@class, 'icon-check')]"
FORM_TAX_FIRST_NAME_AND_MIDDLE_INITIAL_INPUT = "//input[contains(@title, 'First name and middle initial')]"
FORM_TAX_LAST_NAME_INPUT = "//input[contains(@title, 'Last name')]"
FORM_TAX_SOCIAL_SECURITY_NUMBER_INPUT = "//input[contains(@title, 'Social security number')]"
FORM_TAX_ADDRESS_INPUT = "//input[contains(@title, 'Address')]"
FORM_TAX_CITY_STATE_ZIP_CODE_INPUT = "//input[contains(@title, 'City, State, and Zip Code')]"
FORM_TAX_MARITAL_STATUS_HEAD_OF_HOUSEHOLD_RADIO = "(//div[contains(@id, 'marital_status')])[last()]"
FORM_TAX_DATE_INPUT = "//input[contains(@title, 'Date')]"
FORM_TAX_EXTRA_WITHHOLDING_INPUT = "//input[contains(@title, 'Extra Withholding')]"
FORM_TAX_EMPLOYEE_SIGNATURE_BUTTON = "//div[contains(@title, 'Employee’s signature')]//div[(text() = 'Sign here')]"
FORM_TAX_EMPLOYEE_SIGNATURE_INPUT = "//canvas[contains(@class, 'ink-signature-canvas')]"
FORM_TAX_SIGNATURE_CREATE_BUTTON = "//div[contains(@data-element, 'inkSignaturePanel')]//button[@class='signature-create']"

# State tax forms
FORM_TAX_EMPLOYER_NAME_AND_ADDRESS_TEXTAREA = '//*[contains(@title, "Enter employer\'s name and address")]'

# View
FORM_VIEW_TAX_TITLE = """dom:document.querySelector("pdf-viewer").shadowRoot.querySelector("viewer-toolbar").shadowRoot.querySelector("span[id*='title']")"""
FORM_VIEW_DOCUMENT_REVIEW_LINK = "//*[contains(@data-testid, 'document_review_link')]//*[contains(text(), '{}')]//following-sibling::*[contains(text(), 'View')]"

# Task
TASK_MAPPING_FIELD_MODAL = "//div[@data-testid= 'form_builder_ats_list_dialog']//div[@aria-label='Field Mapping']"
