# BASE PAGE
NEW_GROUP_BUTTON = "//button[@class='btn btn-primary']"
GROUP_IN_LIST_ECLIPSE_ICON = "//i[@class='icon-menu']"
ECLIPSE_DELETE_GROUP_BUTTON = "//i[@class='icon icon-delete2']"
ECLIPSE_CONFIRM_DELETE_GROUP_BUTTON = "//button[@class='btn btn-primary btn-sm ok-btn btn-red']"
GROUP_MANAGEMENT_SEARCH_TEXT_BOX = "//input[@class='search-group-managements']"
GROUP_NAME_IN_LIST = "//div[contains(@class, 'list-container-scroll')]//div[contains(@class, 'row') and contains(., '{}')]"
GROUP_IN_LINE_ELIPSIS = "//*[normalize-space()='{}']//ancestor::*[@class='row']//*[contains(@class,'icon-menu')]"
GROUP_SCROLL_VIEW = "//div[@id='container']"
ALL_GROUP_NAME = "//div[contains(@class,'list-container-scroll')]//div[contains(@class,'row')]//div[contains(@class,'text text-overflow')]"

# NEW GROUP PAGE / Group Details Section
GROUP_NAME_TITLE = "//span[@placeholder='Name Your Group']"
SAVE_GROUP_DETAILS_BUTTON = "//button[@class='btn btn-primary']"
EXTERNAL_ID_TEXT_BOX = "//input[@id='id_group_ex_id']"
GROUP_DETAILS_LANGUAGE_DROPDOWN = "//*[contains(@class,'selected-languages-label') and contains(text(),'{}')]"
GROUP_DETAILS_LANGUAGE_OPTIONS_DROPDOWN = "//input[contains(@type,'checkbox')]//following-sibling::div[contains(text(),'{}')]"
GROUP_DETAILS_LANGUAGE_LIST = "//*[@id='multilingual-box']//input[contains(@type,'checkbox')]"
GROUP_DETAILS_CONFIGURE_LANGUAGES_BUTTON = "//button[contains(@class,'btn btn-default btn-sm') and contains(text(),'Configure Languages')]"
GROUP_DETAILS_DEFAULT_LANGUAGE_TEXT = "//*[@id='multilingual-box']//*[contains(text(),'English (en) (default)')]"
GROUP_DETAILS_TAB = "//span[text()='Group Details']"
GROUP_CANDIDATE_JOURNEY_TAB = "//span[text()='Candidate Journey']"

# NEW GROUP PAGE / Candidate Journey Section
JOURNEY_SELECTION_DROPDOWN = "//div[@class='attendees-name text-overflow']"
JOURNEY_SELECT_VALUE = "//div[@class='dropdown__item' and text()='{}']"
GROUP_SCHEDULING_INTERVIEW_TYPE_DROPDOWN = "//div[@class='stage-name' and contains(text(),'Scheduling')]//following-sibling::div//div[@class='attendees-name text-overflow']"
MANUALLY_SCHEDULE_TYPE = "//div[contains(@id,'dropdown_journey-schedule-stage')]//div[@class='dropdown__option']//div[@value='3']"
CONVERSATION_SELECTION_SEARCH_TEXT_BOX = "//input[@placeholder='Select a Conversation']"
CONVERSATION_SELECTION_DROPDOWN = "//div[@class='stage-name' and contains(text(),'Conversation')]//following-sibling::div//div[@class='attendees-name text-overflow']"
SAVE_NEW_GROUP_BUTTON = "//button[@class='btn btn-primary btn-save']"
GROUP_ADD_ATTENDEE = "//div[contains(@id,'dropdown_interviewer')]"
GROUP_INPUT_SEARCH_ATTENDEE = "//input[contains(@id,'id_interviewers')]"
GROUP_ATTENDEE_INTERVIEW = "//div[contains(@id, 'suggestion-placeholder')]//div[contains(text(), '{}')]"
GROUP_SAVE_CANDIDATE_JOURNEY = "//*[contains(@class, 'group-journey-header')]//button[contains(text(), 'Save')]"

# NEW GROUP PAGE / Multilingual
GROUP_MULTILINGUAL_DROPDOWN = "//*[contains(@class,'dropdown multilingual-language')]"
GROUP_MULTILINGUAL_CONFIGURE_BUTTON = "//button[contains(text(),'Configure Languages')]"
GROUP_MULTILINGUAL_CONFIGURE_INPUT_SEARCH_TEXTBOX = "//input[@placeholder='Search Languages']"
GROUP_MULTILINGUAL_CONFIGURE_APPLY_BUTTON = "//button[contains(text(), 'Apply')]"
GROUP_MULTILINGUAL_CONFIGURE_CANCEL_BUTTON = "//div[@class='btn-footer']//button[contains(text(),'Cancel')]"
GROUP_MULTILINGUAL_UPDATE_LANGUAGE_CANCEL_BUTTON = "//button[contains(text(), 'Confirm')]//preceding-sibling::button"
GROUP_MULTILINGUAL_CONFIGURE_LANGUAGE_SELECT_CHECKBOX = "//label[contains(normalize-space(),'{}')]//span"
GROUP_MULTILINGUAL_DROPDOWN_LANGUAGE_SELECT = "//span[contains(normalize-space(),'{}')]"
GROUP_MULTILINGUAL_DROPDOWN_SELECTED_LANGUAGE = "//*[@class='selected-languages-label']"
GROUP_MULTILINGUAL_CONFIRM_BUTTON = "//button[contains(text(),'Confirm')]"
GROUP_MULTILINGUAL_CHOSEN_LANGUAGE_BUTTON = "//*[contains(@class,'fa fa-angle-down')]//preceding-sibling::span[contains(text(),'{}')]"
GROUP_MULTILINGUAL_CHECK_ICON = "//*[contains(@class,'icon-check2')]//preceding-sibling::span[contains(text(),'{}')]"
GROUP_MULTILINGUAL_UPDATE_LANGUAGE_POPUP = "//*[contains(@class,'dialog-multilingual on')]//div[contains(@class,'content')]"
