# LIST DATA PACKAGES
MENU_JOB_DATA_PACKAGES = "//*[contains(@data-testid,'breadcrumb_lbl_current') and contains (text(),'Job Data Packages')]"
INPUT_SEARCH_JOB_DATA = "//*[contains(@data-testid,'jdp_input_search')]//input"
BUTTON_CREATE_PACKAGE = "//*[contains(@data-testid,'jdp_btn_create_packages')]"
ECLIPSE_BUTTON_JOB_PACKAGE = "//span[contains(text(),'{}')]/ancestor::tr//button"
INPUT_SEARCH_JOB_PACKAGE_NAME = "(//*[contains(@placeholder,'Search')])[last()]"
BUTTON_DELETE_JOB_PACKAGE = "(//*[contains(text(),'Delete')])[last()]"
BUTTON_EDIT_JOB_PACKAGE = "(//*[contains(text(),'Edit')])[last()]"
JOB_DATA_PACKAGE_NAME = "//*[contains(@data-testid,'jdp_lbl_package_name') and contains(text(),'{}')]"

# MODAL CREATE PACKAGE
BUTTON_ADD_JOB_DATA = "(//*[contains(@data-testid,'jdp_btn_add_job_data')])[last()]"
BUTTON_APPLY_ADD_JOB_DATA = "//*[contains(@data-testid,'multidropdown_btn_apply')]"
BUTTON_CREATE_PACKAGE_ON_MODAL = "//button[contains(@class,'el-button el-button--primary') ]//span[contains(text(),'Create Package')]"
BUTTON_CANCEL_ON_MODAL = "//*[contains(@data-testid,'jdp_btn_cancel_drawer')]"
BUTTON_CREATE_ON_MODAL = "//*[contains(@data-testid,'jdp_btn_save_drawer')]"
INPUT_SEARCH_JOB_DATA_MODAL = "//*[contains(@data-testid,'multidropdown_input_search')]//input"
INPUT_ENTER_VALUE_DATA_MODAL = "(//span[contains(text(),'{}')]/ancestor::div[contains(@class,'el-form-item__content')]//input)[last()]"
INPUT_PACKAGE_NAME_MODAL = "//*[contains(@data-testid,'jdp_input_package_name')]"
ECLIPSE_BUTTON_EDIT_JOB_PACKAGE_MODAL = "//span[contains(text(),'{}')]/ancestor::div[contains(@class,'el-form-item__content')]//*[contains(@data-testid,'jdp_job_data_item_btn_ellipses')]"
ICON_LOCKED_MODAL = "//*[contains(@class,'icon-locked')]"
BUTTON_SAVE_MODAL = "(//*[contains(text(),'Save')])[2]/parent::button"
ATTRIBUTE_TYPE = "//span[contains(@title,'{}')]"
CHECKBOX_ATTRIBUTE_TYPE = "//span[contains(@title,'{}')]/ancestor::div[contains(@role,'group')]//input[contains(@class,'el-checkbox__original')]"
BUTTON_OVERWRITE_ALL = "//span[contains(text(),'Overwrite All')]/ancestor::button"
BUTTON_CANCEL_OVERRIDE_ATTRIBUTE = "//*[contains(@data-testid,'jdp_btn_hide_dialog_confirm')]"
BUTTON_CONFIRM_OVERRIDE_ATTRIBUTE = "(//*[contains(@data-testid,'jdp_btn_save')])[last()]"
LOCATION_USED_ON_MODAL = "(//i[contains(@class,'icon icon-location')]/following-sibling::span[contains(text(),'{}')])[last()]"
EDIT_DATA_PACKAGES_VALUE = "//input[@placeholder='Enter value']"

NEW_JOB_SELECT_DATA_JOB_PACKAGE = "//div[contains(text(), 'Select job data package')]/following-sibling::div//i[contains(@class, 'icon-chevron-down')]"
NEW_JOB_SELECT_DATA_JOB_PACKAGE_ITEM = "//div[contains(@data-testid, 'lbl_title')]"
NEW_JOB_SELECT_DATA_JOB_PACKAGE_LIST_HAS_NAME = "//div[contains(@data-testid, 'lbl_title')]//div[contains(text(),'{}')]"
ATTRIBUTE_NAME_ADDED = "//span[contains(@class,'font-medium font-weight-primary') and contains(text(),'{}') ]"

# NEW JOB / DATA JOB PACKAGE
NEW_JOB_SELECT_DATA_JOB_PACKAGE_HEADER_LOCATION = "//h4[contains(@data-testid, 'job_additional_details_location_remain_header')]"
NEW_JOB_SELECT_DATA_JOB_PACKAGE_CLOSE_ICON = "//div[contains(@class, 'el-drawer__container el-drawer__open')]//i[contains(@class, 'el-dialog__close el-icon el-icon-close')]"
NEW_JOB_LOCATION_ADDED = "//span[contains(@data-testid, 'job_available_location')]"
NEW_JOB_MESS_ERROR_NOT_ASSIGNED_LOCATION = "//span[contains(@data-testid, 'job_location_error_message')]"
NEW_JOB_DATA_PACKAGE_ADD_LOCATION = "(//span[contains(@class, 'plus1')])[last()]"
NEW_JOB_DATA_PACKAGE_LOCATION_CHECKBOX = "(//span[contains(text(),'{}')])[last()]/../../preceding-sibling::label"
NEW_JOB_DATA_PACKAGE_LOCATION_APPLY = "(//span[contains(text(), 'Apply')])[last()]"
NEW_JOB_DATA_PACKAGE_SAVE = "//button[contains(@data-testid, 'job_additional_details_btn_save_package')]"
NEW_JOB_DATA_PACKAGE_DONE_BTN = "//*[contains(text(),'Done')]"
NEW_JOB_DATA_PACKAGE_ADD_MORE = "//button[contains(@data-testid, 'job_additional_details_btn_add_details')]"
NEW_JOB_DATA_PACKAGE_VIEW_MORE = "//i[contains(@class, 'el-icon-arrow-down')]"
NEW_JOB_DATA_PACKAGE_INPUT_SEARCH = "//input[contains(@placeholder, 'e.g. ')]"
NEW_JOB_DATA_PACKAGE_ATTRIBUTE_AGE = "//span[contains(@title, 'Minimum Age')]"
NEW_JOB_DATA_PACKAGE_BTN_APPLY = "//button[contains(@data-testid, 'multidropdown_btn_apply')]"
NEW_JOB_DATA_PACKAGE_BTN_CREATE = "//span[contains(text(), 'Create')]/parent::button"
NEW_JOB_DATA_PACKAGE_INPUT_ATTRIBUTE_DEAFUT_VALUE = "//input[contains(@placeholder, 'Enter value')]"
NEW_JOB_DATA_PACKAGE_LOCATION_LIST = "//span[contains(text(),'{}') and contains(@data-testid, 'job_location_name')]"
NEW_JOB_DATA_PACKAGE_LOCATION_ITEM = "//i[contains(@class, 'icon-location')]/following-sibling::div"
NEW_JOB_DATA_PACKAGE_LOCATION_ITEM_NAME = "//i[contains(@class, 'icon-location')]/following-sibling::div[contains(text(), '{}')]"

# LIST JOB DATA PACKAGE
JOB_DATA_PACKAGE_INPUT_SEARCH = "//*[contains(@data-testid,'jdp_input_search')]//input"
JOB_DATA_PACKAGE_CREATE_PACKAGE = "//*[contains(@data-testid,'jdp_btn_create_packages')]"
JOB_DATA_PACKAGE_MENU_DELETE = "//ul[contains(@x-placement, 'bottom-end')]//span[contains(text(), 'Delete')]"
JOB_DATA_PACKAGE_MENU_DUPLICATE = "//ul[contains(@x-placement, 'bottom-end')]//span[contains(text(), 'Duplicate')]"
JOB_DATA_PACKAGE_MENU_EDIT = "//ul[contains(@x-placement, 'bottom-end')]//span[contains(text(), 'Edit')]"
JOB_DATA_PACKAGE_DELETE_CONFIRM = "//span[contains(text(), 'Delete')]/ancestor::button"
JOB_DATA_PACKAGE_ITEM_FOUND = "//span[contains(text(),'{}')]//ancestor::tr[contains(@class,'el-table__row')]//i[contains(@class,'icon icon-menu')]"
JOB_DATA_PACKAGE_JOB_DATA_LABEL = "//div[text()='Job Data']"

# SELECT VALUE PAY FREQUENCY
JOB_DATA_PACKAGE_SELECT_CURRENCY_AND_TIME_FOR_ATTRIBUTE_OPTION = "(//*[normalize-space()='{}']//ancestor::div[contains(@class, 'el-row--flex')]//i[contains(@class, 'icon-triangle-down2')])[{}]"
JOB_DATA_PACKAGE_VALUE_DISPLAY_BY_CURRENCY_AND_TIME_OPTION = "(//*[normalize-space()='{}']//ancestor::div[contains(@class, 'el-row--flex')]//span[contains(text(),'{}')])[{}]"
JOB_DATA_PACKAGE_SEARCH_CURRENCY_TEXTBOX = "(//*[contains(@placeholder, 'Search Currency')])[last()]"
JOB_DATA_PACKAGE_SEARCH_CURRENCY_RESULT = "(//*[contains(@class, 'el-dropdown-menu__item')]//span[normalize-space()='{}'])[last()]"
JOB_DATA_PACKAGE_SELECT_CURRENCY_AND_HOUR_VALUE = "(//li[contains(@class, 'el-dropdown-menu__item')]//span[normalize-space()='{}'])[last()]"
JOB_DATA_PACKAGE_CURRENCY_NUMBER_VALUE = "//*[normalize-space()='{}']//ancestor::div[contains(@class, 'el-row--flex')]//following-sibling::div[contains(@class, 'el-input')]//input[contains(@class, 'el-input__inner') and (not (contains(@placeholder, 'Search Currency')))]"
JOB_DATA_PACKAGE_CURRENCY_AND_TIME_VALUE_DEFAULT = "//*[normalize-space()='{}']//ancestor::div[contains(@class, 'el-row--flex')]//span[normalize-space()='{}']"
JOB_DATA_PACKAGE_CURRENCY_VALUE = "(//*[normalize-space()='{}']//ancestor::div[contains(@class, 'el-row--flex')]//input)[last()]"
