# BASE PAGE
SEARCH_JOB_TEXT_BOX = "//input[@placeholder='Search Jobs']"
SEARCH_JOB_TEMPLATE_TEXT_BOX = "//input[@placeholder='Search Job Templates']"
JOB_FAMILY_CHEVRON_DOWN_ICON = "//span[text()='{}']//parent::div//i[contains(@class,'icon-chevron-down')]"
JOB_ECLIPSE_ICON = "(//span[contains(text(), '{}')]//ancestor::a//parent::div//following-sibling::div[@class])[last()]//i[@class='icon icon-menu']"
JOB_TEMPLATE_ECLIPSE_ICON = "//span[contains(text(), '{}')]//ancestor::a//parent::div//following-sibling::div[@class]//i[@class='icon icon-menu']"
BLANK_JOB = "//span[text()='Blank Job']"
JOBS_TAB = "//div[contains(@class, 'menu')]//div[contains(text(), 'Jobs')]"
JOBS_TAB_CONTENT_TITLE = "//div[contains(@class, 'content-title') and (text() = '{}')]"
JOB_FAMILY_ECLIPSE_ICON = "(//span[text()='{}']//parent::div//following-sibling::div)[last()]//div[@data-testid='job_buider_action_job_family']"
JOB_STATUS_ON_JOB_PAGE = "//*[@data-testid='job_buider_job_item']//span[contains(text(),'{}')]"
INPUT_JOB_FAMILY_ON_POPUP = "//input[@placeholder = 'Enter Family Name']"
JOB_FAMILY_NAME_AT_MAIN = "//div[contains(@data-testid, 'job_buider_page_main_job_family')]//span[text()='{}']"
JOB_FAMILY_INFO_AT_MAIN = "//*[text()='{}']//ancestor::*[@data-testid='job_buider_page_main_job_family']"
JOB_BASIC_INFO_DISPLAY_AT_MAIN = "//*[@data-testid='job_buider_job_item']//*[contains(text(),'{}')]"
JOB_FILTER_SELECTED_NUMBER = "//*[contains(text(),'Jobs Selected')]"
JOB_FILTER_CLEAR_BUTTON = "//main//*[contains(@class,'el-icon-close')]"
JOB_FAMILY_CREATE_BUTTON_POPUP = "//*[@data-testid='job_buider_page_main_create_confirm_btn']//span[contains(text(),'Create')]"
JOB_FAMILY_CANCE_BUTTON_POPUP = "//*[@data-testid='job_buider_page_main_create_cancel_btn']//span[contains(text(),'Cancel')]"
INPUT_EDIT_FAMILY_POPUP = "//input[contains(@placeholder, 'Field Name')]"
CANCEL_EDIT_FAMILY_BUTTON_POPUP = "//*[contains(@data-testid, 'job_buider_page_main_edit_cancel_btn')]"
CONFIRM_EDIT_FAMILY_BUTTON_POPUP = "//*[contains(@data-testid, 'job_buider_page_main_edit_confirm_btn')]"
TITLE_EDIT_FAMILY_TEXT_POPUP = "//span[contains(@class, 'el-dialog__title') and (text()='Edit Job Family')]"
LABEL_EDIT_FAMILY_POPUP = "//div[contains(@aria-label, 'Edit Job Family')]//span[contains(text(),'Job Family Name')]"
PUBLISHED_STATUS_ON_LIST_JOB_PAGE = "//span[contains(text(),'{}')]/ancestor::*[contains(@data-testid,'job_buider_job_item')]//span[contains(text(),'Published')]"
JOB_ECLIPSE_ICON_INDEX = "(//i[@class='icon icon-menu'])"
JOB_FAMILY_SEARCH_RESULT = "//div[contains(@data-testid, 'job_buider_page_main_job_family')]"
JOBS_FIRST_JOB_ECLIPSE_MENU = "//*[@data-testid='job_buider_action_job_item']"
ALL_JOB_TITLE = "//label[contains(@data-testid,'my_job_item_toggle_switch')]//parent::div//preceding-sibling::div//span"
JOBS_FILTERING_LABEL = "//*[contains(text(),'{}')]/../..//*[contains(text(), '{}')]"
JOB_PAGE_FILTER_SEARCH_JOB_TEXTBOX = "//*[contains(@data-testid, 'job_buider_page_main_search_input') and not(contains(@style, 'display: none;'))]//input[@placeholder='Search Jobs']"
JOBS_PAGE_JOB_CHECK_BY_INDEX_SPAN = "//*[contains(@data-testid, 'job_buider_job_item')][{}]//span[text()='{}']" # FIRST PARA IS INDEX, SECOND IS STATUS
JOBS_PAGE_JOB_CHECK_BY_INDEX_DIV = "//*[contains(@data-testid, 'job_buider_job_item')][{}]//div[contains(text(),'{}')]" # FIRST PARA IS INDEX, SECOND IS STATUS
JOBS_PAGE_TOTAL_JOBS_TEXT = "//*[normalize-space()='{}']/ancestor::*[@data-testid='job_buider_page_main_job_family']//*[contains(text(),'Jobs')]/.."

# BASE PAGE / Eclipse popup
JOB_ECLIPSE_POPUP_DELETE_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-delete2']/parent::li[contains(text(),'Delete Job')]"
JOB_ECLIPSE_POPUP_EDIT_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-edit']"
JOB_ECLIPSE_POPUP_DUPLICATE_JOB_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-copy']"
JOB_ECLIPSE_POPUP_MOVE_JOB_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-cal-pending']"
JOB_ECLIPSE_POPUP_ARCHIVE_JOB_BUTTON = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-archived']"
JOB_ECLIPSE_POPUP_EDIT_FAMILY_TEXT = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-edit']//following-sibling::span[text()='Edit Job Family']"
JOB_ECLIPSE_POPUP_DELETE_FAMILY_TEXT = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//i[@class='icon-delete2']//following-sibling::span[text()='Delete Job Family']"
INPUT_MOVE_JOB_POPUP = "//div[contains(@data-testid, 'job_buider_page_main_move_job_select')]//input"
INPUT_SEARCH_MOVE_JOB_POPUP = "//div[contains(@data-testid, 'job_buider_page_main_move_job_input')]//input"
RESULT_SEARCH_MOVE_JOB_POPUP = "//li[contains(@data-testid, 'job_buider_page_main_move_job_item')]//div[text()='{}']"
CONFIRM_MOVE_JOB_BUTTON_POPUP = "//button[contains(@data-testid, 'job_buider_page_main_move_job_move_btn')]"
CONFIRM_CANCEL_JOB_BUTTON_POPUP = "//button[contains(@data-testid, 'job_buider_page_main_move_job_cancel_btn')]"
CONFIRM_ARCHIVE_JOB_BUTTON_POPUP = "//button//span[contains(text(),'Archive')]"
HEADER_ARCHIVE_JOB_TEXT_POPUP = "//span[contains(text(),'Archive Job')]"

# BASE PAGE / Eclipse popup / Confirm delete job popup
JOB_ECLIPSE_CONFIRM_POPUP_DELETE_BUTTON = "//div[@class='el-message-box ol-confirm archive-modal-confirm']//button[@class='el-button el-button--default el-button--danger']"

# BASE PAGE / Create New Job popup
CREATE_NEW_JOB_TYPE_TEXT = "//div[@aria-label='Create New Job']//*[contains(text(),'{}')]"

# BASE PAGE / Left Menu
JOBS_PAGE_LEFT_MENU_NAV_TEXT = "//*[contains(@class,'left-menu-ribbon')]//*[contains(@class,'nav-text') and normalize-space(text())='{}']"

# BASE PAGE / Job Advertising / Eclipse menu
JOBS_PAGE_JOB_ADVERTISING_ITEM_ECLIPSE_ICON = "//tr//*[normalize-space(text())='{}']//ancestor::*[contains(@class,'el-table__row')]//*[contains(@class,'icon-menu')]"
JOBS_PAGE_JOB_ADVERTISING_ITEM_ECLIPSE_MENU_VIEW_HISTORY_OPTION = "(//*[@data-testid='job_advertising_view_history_btn'])[last()]"

# BASE PAGE / Job Advertising / Overview
JOBS_PAGE_MAIN_CONTENT_TITLE = "//*[contains(@class,'right-flexible-content')]//*[contains(@class,'content-title') and normalize-space(text())='{}']"
JOBS_PAGE_JOB_ADVERTISING_OVERVIEW_FILTER_BY_DATE_DROPDOWN = "//*[@data-testid='job_advertising_date_time_txt']"
JOBS_PAGE_JOB_ADVERTISING_OVERVIEW_FILTER_BY_DATE_MONTH_VALUE = "//*[contains(@class,'monthSelect-months')]//*[contains(@class,'month') and not(contains(@class,'selected')) and contains(text(),'{}')]"
JOBS_PAGE_JOB_ADVERTISING_OVERVIEW_ITEM_TITLE = "//*[contains(@class,'el-row')]//*[contains(@class,'el-col')]//*[contains(@data-testid,'overview_item_title') and normalize-space(text())='{}']"

# BASE PAGE / Job Advertising / In Progress
JOBS_PAGE_JOB_ADVERTISING_IN_PROGRESS_COLUMN_TITLE = "//*[contains(@class,'table__header')]//tr//*[normalize-space(text())='{}']"

# BASE PAGE / Job Advertising / In Progress|Completed / View History widget
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_DIALOG = "//*[contains(@data-testid,'job_advertising_job_name')]//ancestor::*[@role='dialog']"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_STATUS = "//*[contains(@data-testid,'job_advertising_status')]"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_BUDGET = "//*[contains(@data-testid,'job_advertising_budget')]"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_SPENT = "//*[contains(@data-testid,'job_advertising_spent')]"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_CANDIDATE_APPLIED = "//*[contains(@data-testid,'job_advertising_cand_applied')]"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_STARTED = "//*[contains(@data-testid,'job_advertising_time_start')]"
JOBS_PAGE_JOB_ADVERTISING_VIEW_HISTORY_ADVERTISING_CANCEL_BUTTON = "//*[contains(@data-testid,'job_advertising_cancel_btn')]"

# Common
ICON_EDIT = "//span[contains(@class, 'icon icon-edit')]"
ICON_ARROW_DOWN = "//i[contains(@class, 'el-icon-arrow-down')]"
SAVE_JOB_BUTTON = "//button[contains(@data-testid, 'job_builder_next_btn')]//span[contains(text(), 'Save')]"
JOB_SAVE_BUTTON_ON_MODAL = "//div[contains(@aria-modal, 'true')]//button//span[contains(text(), 'Save')]"
UNSAVED_CHANGES_CONFIRM_SAVE_BUTTON = "//button[@class='el-button el-button--default el-button--primary']"
PUBLISH_JOB_BUTTON = "//button[contains(@data-testid, 'job-builder_publish_btn')]"
APPLY_BUTTON = "//div[contains(@role,'tooltip') and contains(@x-placement, 'end')]//button//span[contains(text(), 'Apply')]"
LOCATION_IN_JOB = "//*[contains(text(),'{}')]//ancestor::div[contains(@class, 'el-tree-node__content')]//label//span"
ANGLE_DOWN_ON_MY_JOB = "//span[contains(@class, 'fa-angle-down pick-store')]/parent::div"
ECLIPSE_CONFIRM_DELETE_JOB_TEMPLATE = "//button[contains(@class, 'el-button--danger')]"

# Job Template
SELECT_JOB_TEMPLATE = "//select[contains(@id, 'job_template')]"
SELECT_JOBS_FAMILY = "//div[contains(text(), '{}')]"
FAMILY_NAME = "//*[contains(@data-testid,'job_buider_page_main_job_family')]//span[contains(text(),'{}')]"
JOBS_TEMPLATE_NAME_ON_MODAL = "//div[contains(text(),'{}')]"
SAVE_JOB_TEMPLATE_ON_MODAL = "(//span[contains(@class, 'dialog-footer')]//button//span[contains(text(), 'Save')])[1]"
NEW_JOB_TEMPLATE_BUTTON = "//li[contains(@class, 'el-dropdown-menu__item')]//span[text()= 'New Job Template']"
ICON_CHEVRON_DOWN = "//span[contains(@class, 'icon-chevron-down')]"
ENTER_DESCRIPTION_QUESTION = "//div[contains(@class, 'ql-editor')]//p"
JOB_TEMPLATES_TAB = "//div[contains(@class, 'menu')]//div[contains(text(), 'Job Templates')]"
JOB_TEMPLATES_NAME = "(//span[contains(text(), '{}')])[1]"
CANCEL_BUTTON_ON_MODAL = "//button[contains(@data-testid, 'job_modal_cancel_btn')]"
CREATE_NEW_TEMPLATE_BUTTON = "//button[contains(@data-testid,  'job_buider_page_main_create_btn')]//span[text()='Create New']"

# Job
NEXT_BUTTON_ON_MODAL = "//*[contains(@data-testid,'job_modal_next_btn')]"
TYPE_MULTI_LOCATION = "//*[contains(@data-testid,'job_modal_type_2')]"
TYPE_STANDARD_LOCATION = "//*[contains(@data-testid,'job_modal_type_3')]"
TYPE_BASIC_MULTI_LOCATION = "//*[contains(@data-testid,'job_modal_type_1')]"
INPUT_JOB_FAMILY = "//span[contains(text(), 'Job Family Name')]//parent::div//following-sibling::div//input"
SAVE_JOB_ON_MODAL = "(//button//span[contains(text(), 'Save')])[2]"
NEW_JOB_BUTTON = "//li[contains(@class, 'el-dropdown-menu__item')]//span[text()= 'New Job']"
AUTO_JOBS_TEMPLATE_NAME = "(//span[contains(text(), 'Auto jobs template')])[1]"
INPUT_JOB_NAME = "//input[@placeholder='Enter Job Name']"
INPUT_JOB_DESCRIPTION = "//*[contains(@data-placeholder,'Enter Description')]"
INPUT_JOB_CODE = "//input[contains(@data-testid,'job_code_input')]"
JOB_POSTING_DROPDOWN = "//*[contains(@data-testid,'job_posting_type_select')]"
ADD_DETAIL_BUTTON = "//button[contains(@data-testid,'job_addittional_detail_btn')]//*[contains(@class,'icon-plus')]"
ECLIPSE_JOB_BUTTON = "(//span//button[contains(@class, 'el-button--default')]//i[contains(@class, 'icon-menu')])"
SUGGEST_LOCATION_ATTRIBUTE = "//div[contains(@class, 'suggest-item') and contains(text(), '{}')]"
SUGGEST_LOCATION_ATTRIBUTE_ON_DESCRIPTION = "//li[contains(@id, 'quill-mention-item-') and (@data-value = '{}')]"
SCREENING_TAB = "//span[text()='Screening']"
JOBS_NAME = "//div[contains(@data-testid, 'job_buider_job_item')]//span[normalize-space(text())='{}']"
JOB_ON_MODEL = "//div[contains(@aria-modal, 'true')]//div[contains(@data-testid, 'job_detail_item_lbl_title') and contains(text(), '{}')]"
NEW_JOB_PUBLISH_BUTTON = "//button[@data-testid='job-builder_publish_btn']"
EDIT_ICON_JOB_NAME = "//span[contains(@class, 'icon icon-edit _')]"
INPUT_ICON_JOB_NAME = "//input[contains(@placeholder, 'Enter Job Name')]"
INPUT_EDIT_JOB_NAME = "//input[contains(@placeholder,'{}')]"
DROPDOWN_JOB_NEW = "//span[text()='New Job']"
JOB_COUNT_SEARCH = "//div[contains(@data-testid, 'job_buider_page_main_job_family')]//span[contains(text(), 'Job')]/parent::div"
AVAILABLE_LOCATION_BY_NAME = "//*[@data-testid='job_available_location' and contains(text(),'{}')]"
JOB_NAME_ON_HEADER = "//*[@data-testid= 'breadcrumb_lbl_current' and (text()='{}')]"
JOB_NAME_EDIT_ABLE_LABEL = "//span[contains(@class,'editable-label') and contains(text(), '{}')]"
JOB_BRAND_NAME_SELECT = "//input[@placeholder='Select Brand Name']"
JOB_BRAND_NAME_OPTION = "//li[contains(@data-testid,'company_brand_id_option_')]//span[text()='{}']"

# OVERVIEW STEP
# ADD DETAILS
INPUT_SEARCH_JOB_PACKAGE_NAME = "(//*[contains(@data-testid,'input_search')])[last()]"
DROPDOWN_SELECT_JOB_DATA_PACKAGE = "//*[contains(@data-testid,'btn_show_menu')][last()]//div[contains(text(),'None')]"
SEARCH_DATA_PACKAGE_DETAILS = "(//*[contains(@data-testid,'input_search')]//input)[last()]"
BUTTON_SAVE_SELECT_DATA_PACKAGE = "(//button[contains(@class,'el-button el-button--primary')]//span[contains(text(),'Save')])[last()]"
BUTTON_EDIT_DETAILS = "//*[contains(@data-testid,'job_addittional_detail_btn_show_drawer')]"
LOCATION_REMAINING_DETAILS = "//*[contains(@data-testid,'job_additional_details_location_remain_header')]"
DROPDOWN_SELECT_JOB_DATA_PACKAGE_DETAILS = "(//*[contains(@data-testid,'btn_show_menu')])[last()]"
ADDITIONAL_DETAILS_USE_IN = "//*[contains(@data-testid,'job_additional_detail_use_in') and contains(text(),'{}')]"
SEARCH_ADDITIONAL_DETAILS = "//*[contains(@data-testid,'job_additional_details_input_search')]//input"
MESS_ERROR_NOT_ASSIGNED_LOCATION = "//*[contains(@data-testid, 'job_location_error_message') and contains[text(),'You must have locations assigned']"
ICON_LOCKED = "//*[contains(@class,'el-tooltip icon icon-locked')]"
BASE_PAY_MAXIMUM_DETAILS = "(//*[contains(text(),'Base Pay Maximum')])[last()]"
ADD_LOCATION_BTN_DETAILS = "(//*[contains(text(),'Add Locations')])[last()]"
APPLY_BTN_DETAILS = "(//span[contains(text(), 'Apply')])[last()]"
DONE_BTN_DETAILS = "(//*[contains(text(), 'Done')])[last()]"
SELECT_JOB_DATA_NAME_DETAILS = "//div[contains(@data-testid, 'lbl_title')]//div[contains(text(),'{}')]"
SELECT_LOCATION_BY_NAME_DETAILS = "(//span[contains(text(), '{}')])[last()]/ancestor::div/preceding-sibling::label"
MESS_ERROR_MUST_ASSIGN_ALL_LOCATIONS = "//*[contains(@data-testid, 'job_location_error_message') and contains[text(),'You must assign details to all locations']"
JOB_DATA_PACKAGE_ON_MODAL_EDIT = "(//div[contains(text(),'{}')])[last()]"
ICON_DELETE_LOCATION_ON_MODAL_EDIT = "//div[contains(text(),'{}')]/parent::div/parent::div//i[contains(@class,'icon-delete2')]"
ICON_DELETE_JOB_DATA_ON_MODAL_EDIT = "//div[contains(text(),'{}')]/parent::div/parent::div//i[contains(@class,'icon-delete2')]"
BUTTON_DELETE_JOB_PACKAGE_CONFIRM_MODAL = "(//*[contains(text(),'Delete')])[last()]"
NUMBER_OF_LOCATION_REMAINING_DETAILS = "//*[contains(@data-testid,'job_additional_details_location_remain_header') and contains (text(),'{}')]"
JOB_DATA_PACKAGE_NAME_DETAILS = "(//div[contains(text(),'{}')])[last()]"
INPUT_VALUE_ATTRIBUTE_DETAILS = "(//input[contains(@class,'el-input__inner')])[last()]"
ICON_ARROW_DOWN_LOCATION_DETAILS = "((//*[contains(text(),'{}')])[last()]/ancestor::div[contains(@class,'el-scrollbar__view')]//i[contains(@class,'icon-chevron-down')])[last()]"
ICON_LOCKED_DETAILS = "//span[contains(text(),'Base Pay Maximum')]/parent::div//i"
ICON_ARROW_DOWN_JOB_DATA_DETAILS = "(//*[contains(text(),'{}')])[last()]/ancestor::div[contains(@class,'el-scrollbar__view')]//i[contains(@class,'el-icon-arrow-down')]"
LOCATION_ASSIGNED_ON_JOB_DATA_PACKAGE = "//*[contains(text(),'{}')]/following-sibling::div"
ICON_CLOSE_MODAL_DETAILS = "//span[contains(text(),'Additional Details')]/preceding-sibling::i"
OVERVIEW_STEP_OVERVIEW_LABEL = "//*[normalize-space()='1']/following::*[normalize-space()='Overview']"
OVERVIEW_STEP_HIRING_TEAM_LABEL = "//*[normalize-space()='2']/following::*[normalize-space()='Hiring Team']"
OVERVIEW_STEP_CANDIDATE_JOURNEY_LABEL = "//*[normalize-space()='3']/following::*[normalize-space()='Candidate Journey']"
OVERVIEW_STEP_SCREENING_LABEL = "//*[normalize-space()='4']/following::*[normalize-space()='Screening']"
OVERVIEW_STEP_SELECT_LANGUAGE_BUTTON = "//*[@data-testid = 'job_builder_multilingual_btn_select_lang']"
OVERVIEW_STEP_JOB_DESCRIPTION_TEXTBOX = "//*[@data-testid = 'job_description_editor']//*[@data-placeholder='Enter Description']"
OVERVIEW_STEP_SELECT_TEXT_FORMAT_DROPDOWN = "//*[@data-testid = 'job_description_editor']//*[contains(@aria-controls,'picker-options-0')]"
OVERVIEW_STEP_SELECT_TEXT_FONT_DROPDOWN = "//*[@data-testid = 'job_description_editor']//*[contains(@aria-controls,'picker-options-1')]"
OVERVIEW_STEP_BOLD_BUTTON = "//*[@class = 'ql-bold']"
OVERVIEW_STEP_ITALIC_BUTTON = "//*[@class = 'ql-italic']"
OVERVIEW_STEP_UNDERLINE_BUTTON = "//*[@class = 'ql-underline']"
OVERVIEW_STEP_LINK_BUTTON = "//*[@class = 'ql-link']"
OVERVIEW_STEP_LIST_BUTTON = "//*[@class = 'ql-list']"
OVERVIEW_STEP_JOB_CODE_TEXTBOX = "//*[@data-testid = 'job_code_input']"
OVERVIEW_STEP_JOB_POSTING_TYPE_DROPDOWN = "//*[@data-testid = 'job_posting_type_select']"
OVERVIEW_STEP_ADD_SHIFTS_BUTTON = "//*[@data-testid = 'job_shift_btn_show_drawer']"
OVERVIEW_STEP_ADD_DETAILS_BUTTON = "//*[@data-testid = 'job_addittional_detail_btn_show_drawer']"
OVERVIEW_STEP_BRAND_NAME_DROPDOWN = "//div[contains(@data-testid,'company_brand_id_select')]"
OVERVIEW_STEP_PATTERN_BRAND_NAME_VALUE = "//li[contains(@data-testid,'company_brand_id_option')]//*[contains(text(),'{}')]"

# ADD NEW JOB / Overview step / Add location
ADD_JOB_LOCATION_SEARCH_TEXT_BOX = "//input[@placeholder='Search for locations']"


# JOB TEMPLATE
INPUT_SEARCH_JOB_TEMPLATE = "//*[@data-testid='job_buider_page_main_search_input']//input"
BUTTON_SATE_SELECT_TEMPLATE = "//*[contains(@data-testid,'job_modal_save_btn_1')]"


# ADD QUESTION
QUESTION_NAME = "//*[contains(@data-testid, 'job_buider_screening_question_item')]//*[contains(text(), '{}')]"
INPUT_QUESTION_NAME = "//input[contains(@data-testid, 'job_buider_question_drawer_name')]"
INPUT_QUESTION_CONTENT = "//div[contains(@placeholder,  'Enter Message')]"
INPUT_QUESTION_CONTENT_1 = "(//div[contains(@placeholder,  'Enter Message')])[2]"
REPLY_TYPE_QUESTION = "//*[contains(@data-testid,'job_buider_question_drawer_select_reply_type')]"
INPUT_LIST_SELECT_ITEM_1 = "//*[contains(@data-testid,'job_buider_question_drawer_item_name_0')]"
ADD_QUESTION_REPLY_TYPE_ITEM = "//*[contains(@class,'el-select-dropdown__item')]//*[contains(text(),'{}')]"
ADD_QUESTION_SCREEN_QUESTION_ADDED_LABEL = "//*[contains(@data-testid,'job_buider_screening_question_item_0')]//*[contains(text(), '{}')]"
ADD_QUESTION_ADD_LIST_ITEM_BUTTON = "//*[contains(@data-testid,'job_buider_question_drawer_add_item_btn')]"
ADD_QUESTION_ADD_LIST_ITEM_VALUE_TEXTBOX = "//*[contains(@data-testid,'job_buider_question_drawer_item_value')]"

# STATUS JOB
STATUS_PUBLISHED = "//button[contains(@data-testid,'job_btn_publish')]//*[contains(text(),'Published')]"
STATUS_UNPUBLISHED = "//button[contains(@data-testid,'job_btn_publish')]//*[contains(text(),'Unpublished')]"
JOB_TEMPLATES_NAME_IN_JOB = "//*[@class='icon-job']//ancestor::*//div[contains(text(),'{}')]"

# ADD HIRING TEAM
HIRING_TEAM_ROLE_USER = "(//*[contains(@data-testid,'hiring_team_checkbox')]//*[contains(text(),'Hiring Manager')])[2]"
HIRING_TEAM_USER = "(//*[normalize-space()='{}']/ancestor::label[contains(@data-testid,'hiring_team_checkbox')]//span[contains(@class,'el-checkbox__input')])[last()]"
INPUT_SEARCH_USER_BASIC_MULTI_LOCATION_TYPE = "//*[contains(@data-testid,'input_search')]//input"
INPUT_SEARCH_USER = "(//*[contains(@data-testid,'input_search')]//input)[2]"
NUMBER_USER_IN_HIRING_TEAM_ROLE= "//div[contains(text(), '{}' )]//following-sibling::div[contains(text(), '1')]"
ADD_HIRING_TEAM_USER_LABEL = "//*[contains(@data-testid, 'hiring_team_role_item')]//*[contains(text(), '{}')]"
ADD_HIRING_TEAM_CAN_MANAGE_CHECKBOX = "//*[normalize-space()='{}']/ancestor::div[contains(@data-testid, 'hiring_team_role_item')]//*[contains(@data-testid, 'hiring_team_item_checkbox')]"

# ADD NEW JOB / Candidate Journey step
NEW_JOB_SELECT_JOURNEY_DROPDOWN = "//div[@data-testid='candidate_journey_select_cj']"
NEW_JOB_SELECT_JOURNEY_SEARCH_TEXT_BOX = "//input[@placeholder='Search for journey']"
NEW_JOB_SELECT_OFFER_DROPDOWN = "//div[contains(text(),'Select Offer(s)')]//parent::div//*[contains(@class,'icon-arrow-up')]"
NEW_JOB_SELECT_OFFER_SEARCH_TEXT_BOX = "//input[@placeholder='Search Offers']"
NEW_JOB_SELECT_VIRTUAL_INTERVIEW = "//i[contains(@class,'icon icon-videocam')]/parent::span"
NEW_JOB_DROPDOWN_ATTENDEE = "(//input[contains(@id,'attendees')])[1]"
NEW_JOB_DROPDOWN_ATTENDEE_2ND = "(//input[contains(@id,'attendees')])[2]"
NEW_JOB_INPUT_SEARCH_ATTENDEE = "(//*[contains(@data-testid,'assistant_scheduling_input_search')]//input)[last()]"
LOCATION_CALENDAR_LABEL = "//div[contains(@class,'el-collapse-item__header') and contains (text(),'Location Calendars')]"
ATTENDEE_INTERVIEW = "//div[contains(@data-testid, 'assistant_scheduling_lbl_attendee_name') and contains(text(),'{}')]"
CANDIDATE_JOURNEY_TAB = "//li/span/span[contains(text(), 'Candidate Journey')]"
INPUT_CANDIDATE_JOURNEY = "//div[@data-testid='candidate_journey_select_cj']//input"
CANDIDATE_JOURNEY_IS_SELECTED = "//li[contains(@class, 'selected')]//span[contains(text(), '{}')]"
CANDIDATE_JOURNEY_FORM = "//form[contains(@class, 'assist-timeline-form')]"
CANDIDATE_JOURNEY_SEND_FORM_STAGE = "//*[text()='{}']//ancestor::*[@data-testid='candidate_journey_stage']//input[@placeholder='Select']"
CANDIDATE_JOURNEY_SEND_FORM_NEXT_STEPS = "//div[contains(@data-testid, 'next_step_select')]"
CANDIDATE_JOURNEY_FORM_NAME = "//div[contains(@class, 'el-select-dropdown el-popper') and contains(@x-placement, 'start')]//span"
CANDIDATE_JOURNEY_SEARCH_FORM_TEXTBOX = "//input[contains(@placeholder, 'Search for Form')]"
CANDIDATE_JOURNEY_FORM_NAME_OPTION = "(//li[contains(@class, 'select-dropdown')]//span[contains(text(), '{}')])[last()]"
CANDIDATE_JOURNEY_SELECT_ATTENDEE = "//div[contains(@data-testid, 'assistant_scheduling_select_attendee')]"
CANDIDATE_JOURNEY_SELECT_INTERVIEW_TYPE_INPUT = "//*[contains(text(), 'Select Interview Type')]//ancestor::div[contains(@data-testid, 'candidate_journey_stage')]//input[@placeholder='Select']"
NEW_JOB_ADD_CONVERSATION_DROPDOWN = "//*[contains(text(),'Conversation to send')]//following-sibling::*//i"
NEW_JOB_ADD_FORM_DROPDOWN = "//*[normalize-space(text())='Form']//ancestor::*[@data-testid='candidate_journey_stage']//*[contains(text(),'Form to send')]//following-sibling::*//i"
NEW_JOB_ADD_APPLICATION_DROPDOWN = "//*[normalize-space(text())='Application']//ancestor::*[@data-testid='candidate_journey_stage']//*[contains(text(),'Form to send')]//following-sibling::*//i"
NEW_JOB_ADD_ONBOARDING_DROPDOWN = "//*[normalize-space(text())='Onboarding']//ancestor::*[@data-testid='candidate_journey_stage']//*[contains(text(),'Form to send')]//following-sibling::*//i"
NEW_JOB_ADD_ASSESSMENT_DROPDOWN = "//*[normalize-space(text())='Assessment']//parent::*//following-sibling::*//i"
NEW_JOB_ADD_DATA_TEST_FIRST_DROPDOWN_VALUE = "(//*[contains(@class,'dropdown__list')])[last()]//li[contains(@class,'dropdown__item')]"

# ADD NEW JOB / Candidate Journey step / Select Offer popup
NEW_JOB_OFFER_APPLY_BUTTON = "//button[@data-testid='filter_dialog_apply']"

# ADD NEW JOB / Hiring Team step / Add user popup
NEW_JOB_HIRING_TEAM_TEXT = "//div[@data-testid='hiring_team_users_dropdown']//*[contains(text(), '{}')]"
NEW_JOB_HIRING_TEAM_TEXT_2 = "(//div[@data-testid='hiring_team_users_dropdown']//*[contains(text(), '{}')])[2]"
NEW_JOB_ADD_USER = "//*[@data-testid='hiring_team_checkbox_9']//*[contains(text(),'{}')]"

# Add location
ADD_LOCATION_BUTTON = "//button//span[contains(text(), 'Add Location')]"
EDIT_LOCATION_BUTTON = "(//button[contains(@data-testid, 'job_location_btn_show_drawer')])[last()]"
ADD_LOCATION_BUTTON_ON_MODAL = "//div[contains(@class, 'el-scrollbar__view')]//button//span[contains(text(), 'Add Location')]"
TOGGLE_REMOTE_LOCATION = "//span[contains(text(),'Remote Position')]/ancestor::Div[contains(@class,'el-scrollbar__view')]//span[contains(@class,' icon-remove')]"
SELECT_ALL_LOCATION = "//div//span[contains(@class, 'expanded')]//following-sibling::label//span"
SAVE_BUTTON_LOCATION = "//div[contains(@aria-modal,'true')]//button//span[contains(text(), 'Save')]"
LOCATION_NAME_AT_MY_JOB = "//label//span[contains(text(), '{}')]"
INPUT_SEARCH_LOCATIONS = "//input[contains(@placeholder,'Search for locations')]"
SINGLE_LOCATION_BY_NAME = "//*[contains(@data-testid,'job_ol_location_tree')]//*[contains(text(),'{}')]"
TOGGLE_REMOTE_POSITION = "//span[contains(@class, 'icon-remove')]"
LOCATION_DELETE_ICON = "//i[contains(@data-testid, 'job_delete_location_')]"
LOCATION_DELETE_BUTTON_ON_ALERT = "//span[contains(text(), 'Delete')]/ancestor::button"
ADD_LOCATION_POPUP = "(//span[contains(text(), 'Add Locations')])[last()]"
LOCATION_SELECT_ALL_CHECKBOX = "(//span[contains(text(), 'Select all')])[last()]/ancestor::div/preceding-sibling::label"
ICON_DELETE_LOCATION = "//*[contains(@data-testid,'job_location_name')  and contains(text(),'{}')]/parent::div/following-sibling::i"
LOCATION_ON_ADD_LOCATION_POPUP = "//em[text()='{}']/ancestor::div/preceding-sibling::label//span[contains(@class, 'el-checkbox__inner')]"
AREA_FOLDER_ON_ADD_LOCATION_POPUP = "//i[contains(@class,'icon icon-folder-open')]/ancestor::div[contains(@class,'el-select-tree__item')]//em[text()='{}']/ancestor::div[contains(@class,'el-select-tree__item')]/preceding-sibling::label"
ADD_LOCATION_FIRST_ITEM_ON_MODAL= "//label[contains(@class,'el-checkbox') and not(contains(@aria-label,'Select all'))]//child::span[contains(@class,'input')]"
ADD_LOCATION_SEARCH_RESULT_BOX_ICON_CLOSE= "//i[contains(@class,'icon-remove')]"

# Add user
JOB_ADD_USER_BUTTON = "//span[contains(text(), 'Add User')]"
JOB_ADD_ROLE_BUTTON = "//span[contains(text(), 'Add Role')]"
SELECT_ALL_USER = "//span[contains(text(), 'Select all')]"

# OUTCOME
OUTCOMES_NAME = "//*[contains(@data-testid, 'job_buider_job_buider_screening_out_item')]//*[contains(text(), '{}')]"
JOB_ADD_OUTCOME_BUTTON = "//*[contains(@data-testid,'job_buider_screening_outcome_btn')]"
JOB_ADD_OUTCOME_BUTTON_ON_MODAL = "//*[contains(@class,'el-button el-button--primary')]//span[contains(text(),'Add Outcome')]"
JOB_ADD_OUTCOME_NAME_INPUT_LABEL = "//*[contains(@data-testid,'job_buider_screening_outcome_text_field')]"
JOB_ADD_OUTCOME_NAME_INPUT = "//*[contains(@data-testid,'job_buider_screening_outcome_text_field')]//input"
SELECT_QUESTION = "(//*[contains(@data-testid,'job_buider_screening_outcome_condition')]//input)[1]"
SELECT_MATCH = "(//*[contains(@data-testid,'job_buider_screening_outcome_condition')]//input)[2]"
INPUT_VALUE = "(//*[contains(@data-testid,'job_buider_screening_outcome_condition')]//input)[3]"
TEXT_AREA_MSG = "(//*[contains(@data-testid,'job_buider_screening_outcome_editor')]//div[contains(@placeholder,'Enter Message')])[2]"
MOVE_TO_STATUS = "(//*[contains(@data-testid,'job_buider_screening_outcome_status_select')])[2]"
STATUS_INVITE_TO_INTERVIEW = "(//li[contains(@class,'el-select-dropdown__item')]//span[contains (text(),'Scheduling: Invite to Interview')])[2]"
SELECT_STATUS_VALUE = "(//li[contains(@class,'el-select-dropdown__item')]//span[contains (text(),'{}')])[2]"
SAVE_OUTCOME_BUTTON = "//*[contains(@data-testid,'job_buider_screening_outcome_save_btn')]"
JOB_CANCEL_SAVE_OUTCOME_BUTTON = "//section[contains(@class, 'el-drawer')]//button[contains(@class, 'el-button')]//span[contains(text(), 'Cancel')]"
SAVE_ALL_OUTCOME_BUTTON = "(//*[contains(@class,'el-button el-button--primary')]//span[contains (text(),'Save')])[2]"
ICON_ARROW_DOWN_MY_JOB = "//div[contains(text(),'{}')]/ancestor::div[contains(@class,'block-head')]//i[contains(@class,'icon job-collapse-btn icon-chevron-down collapsed')]"
LINK_INTERNAL_JOB = "//div[contains(@class,'text-job-name') and contains(text(),'{}')]/ancestor::div[contains(@class,'block-container block-job')]//div[contains(@class,'btnCopyJobLink')]"
OUTCOMES_LABEL = "//*[contains(@data-testid,'job_buider_job_buider_screening_out_item')]//*[contains(text(), '{}')]"
OUTCOMES_MATCHES_ITEM = "(//*[contains(@class,'el-select-dropdown__item')]//*[text()='{}'])[last()]"
JOB_SAVE_OUTCOME_BUTTON = "//section[contains(@class, 'el-drawer')]//button[contains(@class, 'el-button')]//span[contains(text(), 'Save')]"
MOVE_TO_STATUS_VALUE = "//div[contains(@class,'el-select-dropdown el-popper') and not(contains(@style,'display: none'))]//span[contains(text(), '{}')]"

# My job page
TOGGLE_ON_JOB = "//div[contains(text(), '{}')]//parent::div//following-sibling::div//label"
INPUT_SEARCH_LOCATION_MY_JOB = "//input[@id='filter-input']"
INPUT_SEARCH_JOB_MY_JOB = "//input[@id='search-job-title']"

# Add Shift
SHIFT_CHECKBOX_BY_NAME = "//*[@data-testid='job_shift_label' and contains(text(),'{}')]"
SHIFT_ECLIPSE_BUTTON = "//*[@data-testid='job_shift_label' and contains(text(),'{}')]//following-sibling::*//button[@data-testid='job_shift_action_btn']"
SHIFT_NAME_TEXTBOX = "//input[@data-testid='job_shift_input']"
DELETE_SHIFT_BUTTON = "(//span[contains(text(),'Delete Shift')])[last()]"
SAVE_SHIFT_BUTTON = "(//button[contains(@class,'el-button el-button--primary')]//span[contains(text(),'Save')])[last()]"
ADD_SHIFT_BUTTON = "//button[contains(@data-testid,'job_shift_btn')]"
EDIT_SHIFT_BUTTON = "//*[contains(@class,'icon-edit')]/parent::button[contains(@data-testid,'job_shift_btn')]"
SHIFT_IN_USED_BY_NAME = "//*[@data-testid='job_shift_in_used' and contains(text(),'{}')]"
ADD_SHIFTS_AVAILABLE_SHIFT_LABEL = "//*[@data-testid = 'job_shift_label' and contains(text(),'{}')]"
ADD_SHIFTS_CONFIRM_SHIFT_NAME_BUTTON = "//*[@data-testid = 'job_change_shift_name_btn']"

# BASE PAGE > Search job result >  Archive job thresholds popup
CANNOT_ARCHIVE_JOB_MODAL = "//div[contains(@aria-label,'Cannot Archive This Job') and not(contains(@style, 'display: none;'))]"
ARCHIVE_JOB_MODAL = "//div[contains(@aria-label,'Archive Job') and not(contains(@style, 'display: none;'))]"
ARCHIVE_JOB_MODAL_GO_TO_MY_JOBS_BUTTON = "(//button[contains(@class, 'button--default')]//*[contains(text(),'Go to My Jobs')])[last()]"
ARCHIVE_JOB_MODAL_CLOSE_BUTTON = "//*[contains(text(), '{}')]/parent::div/following-sibling::button/*[contains(@class, 'el-icon-close')]"
ARCHIVE_JOB_MODAL_OPTION = "(//button[contains(@class, 'button--default')]//*[contains(text(),'{}')])[last()]"
ARCHIVE_JOB_MODAL_TITLE = "//*[not(self::script) and contains(normalize-space(text()),'Archive Job')]/parent::*[contains(@class, 'el-message-box__title')]"

# BASE PAGE / Fitering dialog
JOB_PAGE_FILTER_BUTTON = "//*[contains(@data-testid, 'filter_badge')]"
JOB_PAGE_FILTER_ITEMS_LABEL = "//span[text()='{}']/parent::div"
JOB_PAGE_FILTER_ITEMS_STATUS = "//div[contains(@data-testid, 'filter_list_item_cbx_group')]//div[text()='{}']"
JOB_PAGE_FILTER_ITEMS_LOCATION = "//span[contains(text(), '{}')]//ancestor::div[contains(@class, 'el-select-tree__item')]//preceding-sibling::label"
JOB_PAGE_FILTER_CLOSE_BUTTON = "//*[contains(text(), '{}')]//span[contains(@class, 'el-icon-close')]"
JOB_PAGE_FILTER_AREA_VALUE_CHECKBOX = "//*[normalize-space()='{}']/ancestor::label[contains(@data-testid, 'filter_list')]//span[contains(@class, 'checkbox__inner')]"
JOB_PAGE_FILTER_LOCATION_FIELD_CHECKBOX = "//*[normalize-space()='{}']/ancestor::*[contains(@role, 'item')]//span[contains(@class, 'checkbox__inner')]"
JOB_PAGE_FILTER_APPLY_BUTTON = "//*[contains(@data-testid, 'filter_dialog_apply')]"
JOB_PAGE_FILTER_CANCEL_BUTTON = "//*[contains(@data-testid, 'filter_dialog_cancel')]"
JOB_PAGE_FILTER_X_BUTTON = "(//*[@aria-label='Close'])[last()]"
JOB_PAGE_FILTER_SEARCH_TEXTBOX = "(//input[@type='text'])[last()]"
JOB_PAGE_FILTER_NO_LOCATION_FOUND_LABEL = "//*[contains(@data-testid, 'empty_lbl_title')]"
JOB_PAGE_FILTER_LOADING_FILTER_LABEL = "//*[normalize-space()='You can filter your job by what you know about them. Select an attribute on the left to get started.']"
JOB_PAGE_FILTER_VALUE_TEXTBOX = "//*[contains(@data-testid,'filter_list_item_cbx_selection')]//*[normalize-space(text())='{}']"
JOB_PAGE_FILTER_TYPE_FIELD_CHECKBOX="//*[normalize-space()='{}']/ancestor::label[contains(@class,'el-checkbox')]//span[contains(@class, 'checkbox__inner')]"
# BASE PAGE > Search job result >  ECLIPSE
JOB_PAGE_ECLIPSE_OPTION = "//ul[contains(@id,'dropdown-menu') and not(contains(@style,'display: none;'))]//parent::li[contains(text(),'{}')]"

# BASE PAGE > Search job result >  ECLIPSE > Move to another Family popup
MOVE_FAMILY_MODAL_TITLE = "//*[contains(@class, 'icon-cal-pending')]//following-sibling::span[contains(text(),'Move to another Family')]"
MOVE_FAMILY_MODAL_CONTENT = "//*[contains(@class, 'el-dialog__body')]//strong/parent::span"
MOVE_FAMILY_MODAL_LABEL = "//div[contains(@class, 'el-dialog__body')]//*[contains(normalize-space(text()),'')]"
MOVE_FAMILY_MODAL_FAMILY_DROPDOWN = "//*[contains(@placeholder, 'Select family')]"
MOVE_FAMILY_MODAL_JOB_FAMILY_ITEMS_LABEL = "//*[contains(text(), '{}')]//parent::*[contains(@data-testid, 'job_buider_page_main_move_job_item')]"
MOVE_FAMILY_MODAL_JOB_FAMILY_ITEMS_DISABLE_LABEL = "//*[contains(text(), '{}')]//parent::*[contains(@data-testid, 'job_buider_page_main_move_job_item') and contains(@class, 'is-disabled')]"
MOVE_FAMILY_MODAL_JOB_FAMILY_ITEMS_ENABLE_LABEL = "//*[contains(text(), '{}')]//parent::*[contains(@data-testid, 'job_buider_page_main_move_job_item')]"
MOVE_FAMILY_MODAL_JOB_FAMILY_CLOSE_ICON = "//*[contains(text(), 'Move to another Family')]/parent::span/following-sibling::button/*[contains(@class, 'el-icon-close')]"

# BASE PAGE > Search job result >  ECLIPSE > DELETE POPUP
CANNOT_DELETE_JOB_MODAL = "//div[contains(@aria-label,'Cannot Delete This Job') and not(contains(@style, 'display: none;'))]"
DELETE_JOB_MODAL = "//div[contains(@aria-label,'Delete Job') and not(contains(@style, 'display: none;'))]"
DELETE_JOB_MODAL_TITLE = "//div[contains(@class, 'el-message-box__title')]//span[contains(text(), '{}')]"
DELETE_JOB_MODAL_CLOSE_BUTTON = "//*[contains(text(), '{}')]/parent::div/following-sibling::button/*[contains(@class, 'el-icon-close')]"
DELETE_JOB_MODAL_CANCEL_BUTTON = "//div[contains(@class, 'el-message-box__btns')]//span[contains(text(),'Cancel')]//parent::button[contains(@class, 'el-button el-button--default')]"
DELETE_JOB_MODAL_GO_TO_MY_JOBS_BUTTON = "(//button[contains(@class, 'button--default')]//*[contains(text(),'Go to My Jobs')])[last()]"
DELETE_JOB_MODAL_BOX_MESSAGE = "//*[contains(@class, 'el-message-box__message')]"

# BASE PAGE / OVERVIEW / ADDITIONAL DETAILS
ADDITIONAL_DETAILS_ARROW_MOVE_BUTTON_ICON = "//*[contains(@class, 'is-circle')]/following-sibling::i[contains(@class, 'el-icon-arrow-down')]"
ADDITIONAL_DETAILS_ARROW_MOVE_BUTTON_LOCATION_ICON = "//*[contains(@class, 'is-circle')]/following-sibling::i[contains(@class, 'icon-chevron-down')]"
ADDITIONAL_DETAILS_CURRENCY_AND_TIME_OPTION = "(//*[normalize-space()='{}']/ancestor::div[contains(@class, 'el-row')]//*[contains(@class,' el-dropdown-selfdefine')])[{}]"
ADDITIONAL_DETAILS_CURRENCY_VALUE_DISPLAY = "(//*[normalize-space()='{}']/ancestor::div[contains(@class, 'el-row')]//input)[last()]"
ADDITIONAL_DETAILS_CURRENCY_AND_TIME_VALUE = "(//*[normalize-space()='{}']/ancestor::div[contains(@class, 'el-row')]//*[normalize-space()='{}'])[{}]"
ADDITIONAL_DETAILS_TIME_VALUE = "//*[normalize-space()='{}']/ancestor::div[contains(@class, 'el-row')]//*[normalize-space()='{}']"
ADDITIONAL_DETAILS_SEARCH_CURRENCY_TEXTBOX = "(//*[contains(@placeholder, 'Search Currency')])[last()]"
ADDITIONAL_DETAILS_TIME_OPTION = "(//*[contains(@class, 'el-popper')]//span[normalize-space()='{}'])[last()]"
ADDITIONAL_DETAILS_CURRENCY_VALUE = "(//*[normalize-space()='{}'])[last()]"
ADDITIONAL_DETAILS_MINIMUM_AND_MAXIMUM_PAY_VALUE = "(//*[normalize-space()='{}']//ancestor::div//following-sibling::div//div[normalize-space()='{}'])[last()]"
ADDITIONAL_DETAILS_SAVE_BUTTON = "//*[contains(@data-testid, 'job_additional_details_btn_save_package')]"
ADDITIONAL_DETAILS_DONE_BUTTON = "(//*[contains(@class, 'config-drawer__footer')]//*[normalize-space()='Done'])[last()]"
ADDITIONAL_DETAILS_CANCEL_BUTTON = "(//*[contains(@class, 'config-drawer__footer')]//*[normalize-space()='Cancel'])[last()]"

