# BASE PAGE
RATINGS_PAGE_AUDIENCE_TAB = "//div[@class='audience-type v-center']//span[contains(text(),'{}')]"
CREATE_NEW_RATING_BUTTON = "//button[@class='btn btn-primary']"
SEARCH_FOR_RATINGS_TEXT_BOX = "//input[@placeholder='Search for ratings']"
RATING_IN_ROW_ECLIPSE_ICON = "//*[contains(text(),'{}')]//parent::div//following-sibling::em"
RATING_IN_ROW_TO_DELETE = "//*[contains(text(),'{}')]//ancestor::a//span[contains(@class, 'trigger-type-label') and not(contains(text(), 'User Feedback Campaign'))]//parent::div//following-sibling::em"
RATING_DELETE_ICON = "(//span[contains(@class, 'icon-delete')])[last()]"
CHOOSE_RATINGS_NAME = "//div[contains(@class,'list-container-scroll')]//span[contains(text(),'{}')]"
RATING_TAB = "//*[@id='rating-list']//span[contains(text(),'{}')]"
RATING_NAME = "//*[contains(@class,'text-overflow') and contains(text(),'{}')]"

# BASE PAGE / Delete a rating confirm popup
DELETE_A_RATING_POPUP_YES_BUTTON = "//div[@style='display: block;']//button[contains(@class,'btn-sm') and text()='Yes']"
RATING_DELETE_CONFIRM_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Yes')]"

# ADD RATING PAGE
ADD_RATING_NEXT_STEP_BUTTON = "//button[@class='btn btn-primary']"
RATING_ITEM_TAB_CHOOSE = "//span[contains(text(),'{}')]//parent::li[contains(@class,'menu-item')]"

# ADD RATING PAGE / Title & Audience step
EDIT_RATING_TITLE_ICON = "//span[@class='icon-edit']"
RATING_AUDIENCE_DROPDOWN = "//div[@class='form-control ai-input cursor-pt audience-item']"
RATING_AUDIENCE_DROPDOWN_VALUE = "//div[@class='container-audience open']//span[contains(text(),'{}')]"

# ADD RATING PAGE / Content step
QUESTION_TEXT_BOX = "//span[@placeholder='Insert Question']"
RATING_QUESTION_SAVE_BUTTON = "//button[@class='btn btn-primary btn-submit']"
RATING_ANSWER_TEXT_BOX = "(//input[@placeholder='Answer'])"
RATING_THEME_DROPDOWN_TOGGLE = "//div[contains(@class,'theme-selector')]//div[contains(@class,'dropdown-toggle')]"
RATING_THEME_NAME_SELECT = "//span[contains(text(),'{}')]//ancestor::div[contains(@class,'dropdown-item')]"
RATING_QUESTION_DROPDOWN = "//div[contains(@class,'ratings-question-list')]//div[contains(@class,'container-ratings-inner')]"
RATING_THEME_NAME_CHECK_DISPLAY = "//div[contains(@class,'selected-theme ') and (text()='{}')]"
RATING_ANSWER_CHECK = "//div[contains(@class,'question-info')]//label[contains(@class,'answer-count')]"
RATING_ANSWER_THEME_CHECK = "//div[contains(@class,'question-info')]//label[contains(@class,'answer-theme')]"
RATING_QUESTION_SETTING_SELECT = "//div[contains(@class,'settings-group')]//span[contains(text(),'{}')]"
RATING_QUESTION_SETTING_ICON = "//div[@id='dropdown_settings']"
RATING_FEEDBACK_TOGGLE = "//label[contains(@for, 'toggle_additional_feedback_0')]"
RATING_FEEDBACK_ANSWER_CHECKBOX = "//label[contains(@for,'ask_feedback_{}_0')]//span"
RATING_FEEDBACK_ADD_QUESTION = "//div[contains(@class,'container-ratings')]//span[contains(text(),'{}')]"
RATING_OVERALL_FEEDBACK_TOGGLE = "//label[contains(@for, 'toggle_overall_feedback')]"
RATING_MULTILINGUAL_ICON = "//*[contains(@class,'dropdown-menu')]//preceding::*//*[contains(@class,'icon icon-multilingual')]"
RATING_MULTILINGUAL_SEARCH_BUTTON = "//*[contains(@placeholder,'Search Languages')]"
RATING_MULTILINGUAL_LANGUAGE_CHECKBOX = "//label[contains(normalize-space(),'{}')]//span"
RATING_MULTILINGUAL_PLEASE_NOTE_CONFIRM_BUTTON = "//button[contains(text(),'{}')]"
RATING_CONTENT_STEP_BACK_ICON = "//*[contains(text(),'Back to Ratings')]//preceding-sibling::*[contains(@class,'icon icon-arrow-left')]"

# ADD RATING PAGE / Confirmation step
ADD_RATING_CONFIRM_YES_BUTTON = "//div[@class='cfbox-content']//button[@class='btn btn-primary btn-sm ok-btn']"
RATING_PREVIEW_ANSWERS_LABEL = "//span[text()='Preview']//parent::div[contains(@class,'container-ratings-inner')]//div[contains(@class,'answers-list')]//label"
RATING_PREVIEW_ANSWERS_THEME = "(//span[text()='Preview']//parent::div[contains(@class,'container-ratings-inner')]//div[contains(@class,'answers-list')])//*[i[contains(@class,'icon')] or img]"
RATING_PREVIEW_QUESTION = "//span[text()='Preview']//parent::div[contains(@class,'container-ratings-inner')]//div[contains(@class,'question')]//p"

# CHECK CONTENT EMAIL RATING STAR
RATING_EMAIL_PREVIEW_ANSWERS_STAR = "//div[contains(@class,'answer-list flex-center rating_star')]//div[contains(@class,'answer')]//div[contains(@class,'theme')]//i[contains(@class,'icon-star-2-border')]"
RATING_EMAIL_PREVIEW_ANSWERS = "(//div[contains(@class,'answer-list flex-center rating_star')]//div[contains(@class,'theme')]//parent::div[contains(@class,'answer')])[2]"
RATING_EMAIL_PREVIEW_ANSWERS_LABEL = "//div[contains(@class,'answer-list flex-center rating_star')]//div[contains(@class,'answer-text')]"
RATING_EMAIL_PREVIEW_BUTTON_SUBMIT = "//div[contains(@class,'rating-footer')]//button[contains(@class,'btn-submit') and contains(text(),'{}')]"
RATING_EMAIL_PREVIEW_THANK_YOU = "//div[contains(@class,'confetti-inner flex-center')]//*[contains(text(),'{}')]"

# CHECK CONTENT EMAIL RATING TEXT
RATING_EMAIL_PREVIEW_ANSWERS_TEXT = "//div[contains(@class,'answer')]//div [contains(@class,'answer-text') and contains(text(),'{}')]"
RATING_EMAIL_PREVIEW_ANSWERS_TEXT_HOVER = "(//div[contains(@class,'answer-list')]//descendant::div[contains(@class,'answer-text')]//parent::div)[1]"
RATING_EMAIL_PREVIEW_ADD_FEEDBACK_TEXT = "//div[contains(@class,'feedback')]//div[contains(text(),'{}') and contains(@class,'feedback_text')]"
RATING_EMAIL_PREVIEW_TEXTAREA = "//div[contains(@class,'input-feedback form-group ')]//textarea[contains(@placeholder,'{}')]"
RATING_EMAIL_PREVIEW_OVERALL_FEEDBACK_TEXT = "//div[contains(@class,'question')]//div[contains(@class,'question-text') and contains(text(),'{}')]"
RATING_EMAIL_PREVIEW_OVERALL_FEEDBACK_TEXTAREA = "//div[contains(@class,'feedback')]//*[contains(@class,'ai-input form-control') and contains(@placeholder,'{}')]"

# ADD RATING PAGE / CHECK CONTENT EMAIL RATING
RATING_EMAIL_ANSWERS_THEME = "//div[contains(@class,'answer-list flex-center {}')]//div[contains(@class,'answer')]//div[contains(@class,'answer-text')]"
RATING_EMAIL_ANSWERS_THEME_TEXT = "(//div[contains(@class,'answer-list flex-center {}')]//div[contains(@class,'theme')]//parent::div[contains(@class,'answer')])[2]"
RATING_EMAIL_ANSWERS_THEME_ICON = "//div[contains(@class,'answer-list flex-center {}')]//div[contains(@class,'answer')]//div[contains(@class,'theme')]"

#RATING PAGE / WIDGET SITE
RATING_WIDGET_STAR_ICON = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item .el-rate__item >i")[{}]"""
RATING_WIDGET_STAR_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item .el-rate__item >span")[{}]"""
RATING_WIDGET_PREVIEW_STAR_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item .el-rate__item")[{}]"""
RATING_WIDGET_ICON = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [data-testid='widget_rating_btn_answer'] img")[{}]"""
RATING_WIDGET_TEXT_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [data-testid='widget_rating_btn_answer'] span")[{}]"""
RATING_WIDGET_PREVIEW_NOT_STAR_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [data-testid='widget_rating_btn_answer']")[{}]"""
RATING_WIDGET_CLOSE_STAR_ICON = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher .el-rate__item >i")[{}]"""
RATING_WIDGET_CLOSE_STAR_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher .el-rate__item >span")[{}]"""
RATING_WIDGET_CLOSE_PREVIEW_STAR_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher .el-rate__item")[{}]"""
RATING_WIDGET_CLOSE_ICON = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [data-testid='widget_rating_btn_answer'] img")[{}]"""
RATING_WIDGET_CLOSE_TEXT_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [data-testid='widget_rating_btn_answer'] span")[{}]"""
RATING_WIDGET_CLOSE_PREVIEW_NOT_STAR_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [data-testid='widget_rating_btn_answer']")[{}]"""
SHADOW_DOM_SELECTED_JOB =  """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".el-dialog span > div .job-item")"""
SHADOW_DOM_SELECTED_SEE_ALL = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("[data-testid='message_lbl_job_results'] button span")"""
RATING_WIDGET_RATING_QUESTION_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item [data-testid='widget_rating_lbl_question']")"""
RATING_WIDGET_RATING_SUCCESS_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item [data-testid='widget_rating_lbl_thanks'] span")"""
RATING_WIDGET_RATING_SUCCESS_IMG = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item [data-testid='widget_rating_lbl_thanks'] img")"""
RATING_WIDGET_RATING_THEME_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [class='rating-text']")"""
RATING_WIDGET_RATING_THEME_TEXT_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [class='rating-text'] span")[{}]"""
RATING_WIDGET_PREVIEW_TEXT_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".me-messages__item [class='rating-text']")[{}]"""
RATING_WIDGET_FEEDBACK_TEXTAREA = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("textarea[data-testid='widget_rating_input_feedback']")"""
RATING_WIDGET_FEEDBACK_BUTTON = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("button[data-testid='widget_rating_btn_feedback_submit']")"""
RATING_WIDGET_OPEN_ENDED_INPUT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item textarea[data-testid='widget_rating_input_open_ended']")"""
RATING_WIDGET_CLOSE_OPEN_ENDED_INPUT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".apply-messenger-launcher textarea[data-testid='widget_rating_input_open_ended']")"""
RATING_WIDGET_OPEN_ENDED_BUTTON = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item button[data-testid='widget_rating_btn_open_ended_submit']")"""
RATING_WIDGET_CLOSE_OPEN_ENDED_BUTTON = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".apply-messenger-launcher button[data-testid='widget_rating_btn_open_ended_submit']")"""
RATING_WIDGET_CLOSE_BUTTON = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("[data-testid='widget_chatbox_popover'] button i[class*='el-icon-close']")"""
RATING_WIDGET_CLOSE_RATING_QUESTION_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".apply-messenger-launcher [data-testid='widget_rating_lbl_question']")"""
RATING_WIDGET_CLOSE_RATING_SUCCESS_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".apply-messenger-launcher [data-testid='widget_rating_lbl_thanks'] span")"""
RATING_WIDGET_CLOSE_RATING_SUCCESS_IMG = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".apply-messenger-launcher [data-testid='widget_rating_lbl_thanks'] img")"""
RATING_WIDGET_CLOSE_RATING_THEME_TEXT = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [class='rating-text']")"""
RATING_WIDGET_CLOSE_RATING_THEME_TEXT_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [class='rating-text'] span")[{}]"""
RATING_WIDGET_CLOSE_PREVIEW_TEXT_ANSWERS = """dom:document.querySelector("apply-widget").shadowRoot.querySelectorAll(".apply-messenger-launcher [class='rating-text']")[{}]"""
RATING_WIDGET_CLOSE_FEEDBACK_TEXTAREA = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("textarea[data-testid='widget_rating_input_feedback']")"""
RATING_WIDGET_CLOSE_FEEDBACK_BUTTON = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("button[data-testid='widget_rating_btn_feedback_submit']")"""
RATING_WIDGET_CHAT_BOX_PROMPT = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("[data-testid='chatbox_lbl_prompt_text']")"""
RATING_WIDGET_FEEDBACK_MESSAGE_LABEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelector(".me-messages__item [data-testid='widget_rating_lbl_feedback_message']")"""
RATING_WIDGET_MODEL = """dom:document.querySelector("apply-widget").shadowRoot.querySelector("div[data-testid='widget_chatbox_popover']")"""

#RATING PAGE/ LANDING SITE
RATING_LANDING_SITE_STAR_LABEL = "//div[contains(@class,'el-rate')]//div[contains(@class,'el-rate__item')]//span"
RATING_LANDING_SITE_STAR_ICON = "//div[contains(@class,'el-rate')]//div[contains(@class,'el-rate__item')]//i[contains(@class,'el-rate__icon')]"
RATING_LANDING_SITE_PREVIEW_STAR_ANSWERS = "(//div[contains(@class,'el-rate')]//div[contains(@class,'el-rate__item')])[{}]"
RATING_LANDING_SITE_STAR_ICON_INDEX = "(//div[contains(@class,'el-rate')]//div[contains(@class,'el-rate__item')]//i[contains(@class,'el-rate__icon')])[{}]"
RATING_LANDING_SITE_RATING_SUCCESS_TEXT = "//div[@data-testid='widget_rating_lbl_thanks']//span"
RATING_LANDING_SITE_RATING_SUCCESS_IMG = "//div[@data-testid='widget_rating_lbl_thanks']//img"
RATING_LANDING_SITE_FEEDBACK_TEXTAREA = "//div[contains(@class,'me-messages__item')]//textarea[@data-testid='widget_rating_input_feedback']"
RATING_LANDING_SITE_FEEDBACK_BUTTON = "//div[contains(@class,'me-messages__item')]//button[@data-testid='widget_rating_btn_feedback_submit']"
RATING_LANDING_SITE_RATING_THUMB_TEXT = "//div[contains(@class,'me-messages__item')]//div[contains(@class,'rating-text')]"
RATING_LANDING_SITE_RATING_THUMB_TEXT_LABEL = "//div[contains(@class,'me-messages__item')]//div[contains(@class,'rating-text')]//span"
RATING_LANDING_SITE_PREVIEW_TEXT_ANSWERS = "(//div[contains(@class,'me-messages__item')]//div[contains(@class,'rating-text')])[{}]"
RATING_LANDING_SITE_NOT_STAR_LABEL = "//div[contains(@class,'me-messages__item')]//div[@data-testid='widget_rating_btn_answer']//span"
RATING_LANDING_SITE_NOT_STAR_ICON = "//div[contains(@class,'me-messages__item')]//div[@data-testid='widget_rating_btn_answer']//img"
RATING_LANDING_SITE_PREVIEW_NOT_STAR_ANSWERS = "(//div[contains(@class,'me-messages__item')]//div[@data-testid='widget_rating_btn_answer'])[{}]"
RATING_LANDING_SITE_RATING_QUESTION_TEXT = "//span[@data-testid='widget_rating_lbl_question']"
RATING_LANDING_SITE_OPEN_ENDED_INPUT = "//textarea[@data-testid='widget_rating_input_open_ended']"
RATING_LANDING_SITE_OPEN_ENDED_BUTTON = "//button[@data-testid='widget_rating_btn_open_ended_submit']"
