# BASE PAGE
SCHOOL_FETCHED_ON_LIST = "//div[@id = 'loc-hierarchy']//span[text()={}]"
EVENT_PLANING_APPROVAL_TOGGLE = "//label[contains(@for, 'event_planning_approval_on')]"
INPUT_SELECT_APPROVAL_FLOW = "//select[contains(@id, 'approval-flow-selector')]"
OPTION_APPROVAL_FLOW = "//option[contains(text(), '{}')]"
SAVE_APPROVAL_FLOW_BUTTON = "(//button[contains(text(), 'Save')])[3]"
SCHOOL_MANAGEMENT_ADD_NEW_ICON = "//*[contains(text(), 'All Schools')]//parent::*//i[contains(@class, 'icon-plus')]"
SCHOOL_MANAGEMENT_ADD_A_SCHOOL_BUTTON = "//*[contains(@class, 'popover-content')]//span[contains(text(), '{}')]"
SCHOOL_MANAGEMENT_FIND_A_SCHOOL_TEXTBOX = "//*[@id='school-search']"
SCHOOL_MANAGEMENT_CLEAR_SEARCH_BUTTON = "//*[@id='erase-icon']"
SCHOOL_MANAGEMENT_ADD_CUSTOM_SCHOOL_LOCATOR = "//div[contains(text(),'Add Custom School')]"
SCHOOL_MANAGEMENT_SEARCH_FOR_A_SCHOOL_TEXTBOX = "//input[contains(@id, 'filter-input')]"
SCHOOL_MANAGEMENT_SCHOOL_NAME_LABEL = "//*[contains(@class, 'icon school')]//*[contains(text(),'{}')]"
SCHOOL_MANAGEMENT_AREA_NAME_LABEL = "//*[contains(@class, 'icon area')]//*[contains(text(),'{}')]"
SCHOOL_MANAGEMENT_ADD_AN_AREA_BUTTON = "(//*[contains(@class, 'add-area')])[last()]"
SCHOOL_MANAGEMENT_FIND_A_SCHOOL_DROPDOWN = "//*[@id='school-search'][@placeholder='Search by school name or address']"
SCHOOL_MANAGEMENT_ADD_A_SCHOOL_TO_AN_AREA_BUTTON="//span[contains(text(), '{}')]//following-sibling::i[contains(@class, 'icon-plus')]"

# BASE PAGE / ADD NEW SCHOOL
ADD_NEW_SCHOOL_NAME_TEXTBOX = "//input[contains(@id , 'id_name')]"
ADD_NEW_SCHOOL_STREET_ADDRESS_TEXTBOX = "//input[contains(@placeholder , 'Street address')]"
ADD_NEW_SCHOOL_CITY_TEXTBOX = "//input[contains(@id , 'id_city')]"
ADD_NEW_SCHOOL_STATE_DROPDOWN = "//*[contains(@id , 'div_id_admin1_code')]//select"
ADD_NEW_SCHOOL_STATE_DROPDOWN_OPTIONS = "//div[contains(@id, 'div_id_admin1_code')]//option[contains(text(), '{}')]"
ADD_NEW_SCHOOL_USERS_TEXTBOX = "(//input[@id='school_users'])[last()]"
ADD_NEW_SCHOOL_USER_SUGGESTION_NAME = "(//div[contains(@class,'suggestions')]//*[contains(text(),'{}')])[last()]"
ADD_NEW_SCHOOL_SAVE_BUTTON = "//div[contains(@id, 'remove_school')]//following::div//button[contains(@class, 'btn-save pull-right')]"
ADD_NEW_SCHOOL_DELETE_SCHOOL_BUTTON = "//*[contains(@id , 'remove_school')]//button[contains(@id , 'btnRemove')]"
ADD_NEW_SCHOOL_YES_BUTTON = "//button[contains(@class, 'ok-btn') and contains(text(), 'Yes')]"
ADD_NEW_SCHOOL_ENTER_A_NAME_TO_ADD_TEXTBOX = "//label[contains(text(), 'candidates within this school')]//following::input[contains(@id, 'school_users')]"
ADD_NEW_SCHOOL_ADD_LOGO_UPLOAD = "//span[contains(@class,'glyphicon ')]//following-sibling::p"
ADD_NEW_SCHOOL_CAMPUS_ADDRESS_DROPDOWN = "//div[@id='div_id_country_cd']//select"
ADD_NEW_SCHOOL_AREA_NAME_LABEL = "//div[contains(@class,'col-detail clearfix card-content')]//label[contains(text(),'Area name')]"
ADD_NEW_SCHOOL_ACRONYM_INPUT = "//input[@id='id_acronym']"
ADD_NEW_SCHOOL_MASCOT_INPUT = "//input[@id='id_mascot']"
ADD_NEW_SCHOOL_WARNING_MESSAGE = "//*[@id='div_id_name']//*[contains(text(), 'This field is required')]"
ADD_NEW_SCHOOL_EVENT_PLANNING_APPROVAL_TOGGLE = "//*[@id='school_form']//label[@for='event_planning_approval_on']"
ADD_NEW_SCHOOL_APPROVAL_FLOW_DROPDOWN = "//div[@id='main_content']//*[@id='approval-flow-selector']"
ADD_NEW_SCHOOL_APPROVAL_FLOW_DROPDOWN_OPTIONS = "//div[@id='main_content']//*[@id='approval-flow-selector']//option[contains(text(), '{}')]"
ADD_NEW_SCHOOL_CONFIRM_UPLOAD_PHOTO_BUTTON = "//div[contains(@class, 'modal-footer')]//button[contains(text(), 'Confirm')]"
ADD_NEW_SCHOOL_UPLOAD_IMAGE = "//*[@id='id_logo_dropzone']"
ADD_NEW_SCHOOL_APPROVAL_FLOW_VIEW_BUTTON = "//*[@id='school_form']//*[contains(text(), 'View')]"
ADD_NEW_SCHOOL_APPROVAL_FLOW_VIEW_CLOSE_BUTTON = "//*[@id='approval-flow-modal']//*[contains(@class, 'icon-remove')]"
ADD_NEW_SCHOOL_VIEW_APPROVAL_FLOW_TITLE = "//*[@id='approval-flow-modal']//*[@class='ai-sidebar-header-title']"
ADD_NEW_SCHOOL_VIEW_APPROVAL_FLOW_USER_NAME = "//*[@id='flows']//*[contains(text(),'{}')]"
ADD_NEW_SCHOOL_VIEW_APPROVAL_VIEW_SLIDE = "//*[@id = 'approval-flow-modal']"
ADD_NEW_SCHOOL_USER_TAG = "//div[contains(@class, 'results')]//*[contains(text(), '{}')]"
ADD_NEW_SCHOOL_REMOVE_USER_BUTTON = "//div[contains(text(), '{}')]//parent::div[contains(@class, 'info')]//following-sibling::div[contains(@class, 'menu')]//*[contains(@class, 'remove-item')]"
ADD_NEW_SCHOOL_HEADER = "//*[@id='toolbar-action']//*[contains(text(),'School Management')]"
ADD_NEW_SCHOOL_LIST_NAME_SCHOOL_TEXT = "//*[contains(@class,'icon school fetched')]//span[contains(text(),'{}')]"

# BASE PAGE / SEARCH SCHOOL
SEARCH_SCHOOL_DELETE_SCHOOL_BUTTON = "//div[contains(@class,'card-content')]//*[@id='btnRemove']"

# BASE PAGE / ADD NEW AN AREA
ADD_NEW_AN_AREA_NAME_TEXTBOX = "(//input[contains(@id, 'id_area_name')])[last()]"
ADD_NEW_AN_AREA_ENTER_A_NAME_TO_ADD_TEXTBOX = "(//label[contains(text(), 'candidates within this area')]//following::input[contains(@id, 'school_users')])[last()]"
ADD_NEW_AN_AREA_ENTER_A_NAME_TO_ADD_USER = "(//div[contains(@class, 'item')]//div[contains(text(), '{}')])[last()]"
ADD_NEW_AN_AREA_SAVE_BUTTON = "(//button[contains(@class, 'btn-save')])[last()]"
ADD_NEW_AN_AREA_REMOVE_BUTTON = "(//button[contains(@class, 'btn-remove')])[last()]"
ADD_NEW_AN_AREA_REMOVE_USER_BUTTON = "//div[contains(text(), '{}')]//parent::div[contains(@class, 'info')]//following-sibling::div[contains(@class, 'menu')]//*[contains(@class, 'remove-item')]"
ADD_NEW_AN_AREA_USER_TAG = "//div[contains(@class, 'results')]//*[contains(text(), '{}')]"
ADD_NEW_AN_AREA_YES_BUTTON = "(//*[contains(@class, 'ok-btn')])[last()]"
ADD_NEW_AN_AREA_ADD_USER_SUGGESTION = "//*[contains(@class,'OlivAC-suggestions') and not(contains(@style,'display: none'))]//*[contains(text(),'{}')]"

ADD_NEW_SCHOOL_APPROVAL_FLOW_LIST = "//div[contains(@class, 'approval-list')]//div[@class= 'text text-overflow']"
