# BASE PAGE
WEB_PAGES_LIST = "//div[@class='list-container-scroll']"
WEB_PAGE_NAME = "//div[@class='text text-overflow' and contains(text(),\"{}\")]"
ADD_NEW_WEB_BUTTON = "(//button[@class='btn btn-primary'])[1]"
WEB_MANAGEMENT_PAGE_CENTER_MESSAGE = "//div[@id='message-ctn']"
WEB_MANAGEMENT_PAGE_SEARCH_BOX = "//input[contains(@aria-label,'Search for pages')]"
WEB_MANAGEMENT_ROW = "//div[contains(@class,'list-container')]//div[contains(@class,'text text-overflow')]"
CLOSE_ALERT_ICON = "//span[contains(@class,'icon-remove')]"

# BASE PAGE / Select site widget
WEB_SITE_TYPE = "//div[@class='modal-content printable']//strong[text()='{}']"
NEXT_BUTTON_SELECT_SITE = "//div[@class='modal-content printable']//div[@class='modal-footer']//button[contains(@class,'ok-btn')]"
CANCEL_BUTTON_SELECT_SITE = "//div[@class='modal-content printable']//div[@class='modal-footer']//button[contains(@class,'cancel-btn')]"

# BASE PAGE / Eclipse Menu
ECLIPSE_BUTTON_SITE = "//i[contains(@class,'icon-menu')]"
EDIT_BUTTON_SITE = "//li[@data-action='edit']"
DELETE_BUTTON_SITE = "//li[@data-action='delete']"
DELETE_BUTTON_BY_NAME_SITE = "//div[contains(text(),'{}')]/ancestor::div//i[contains(@class,'icon-menu')]"
ACTION_DELETE_SITE = "//*[contains(@data-action,'delete')]"
BUTTON_YES = "//button[contains(text(),'Yes')]"
CONFIRM_DELETE_BUTTON_SITE = "//div[@class='modal-content printable']//button[contains(@class,'ok-btn')]"
HEADER_TITLE_INPUT = "//div[contains(@id, 'div_id_header_title')]//input"

# WEB MANAGEMENT
WEB_MANAGEMENT_WIDGET = "//div[@id='widget-detail-modal' and @class='widget-detail widget-detail--on']"
CONVERSATION_SELECTION = "//select[@id='id_conversation']//following-sibling::span"
CONVERSATION_TEMPLATE_NAME_SELECTION = "//ul[contains(@id,'conversation-results')]//child::li//child::div[contains(text(),'{}')]"
CONVERSATION_NAME_SEARCH_BOX = "//input[@class='select2-search__field']"
CONVERSATION_SELECTED_NAME = "//div[@class='selected-conversation']//span[text()='{}']"
CONVERSATION_NAME_VALUE = "//*[contains(@id,'select2-id_conversation-result')]//*[contains(text(),'{}')]"
WEB_MANAGEMENT_SAVE_BUTTON = "//div[@class='pull-right iframe-save-button']//button[contains(@class,'btn-save') and not(contains(@disabled,'disabled'))]"
ICON_CLOSE_MODAL = "//div[contains(@id,'widget-detail-modal')]//i[contains(@class,'icon icon-remove close-widget-detail')]"
WEB_MANAGEMENT_REMOVE_BUTTON = "//button[@class='btn btn-red btn-remove']"
WEB_LONG_URL = "//input[@id='id_company_url']"
WEB_SHORT_URL = "//input[@id='id_company_short_url']"
SITE_NAME_WEB_WIDGET = "//input[@id='id_name']"
SEARCH_WEB_PAGE = "//input[contains(@placeholder,'Search for pages')]"
JOB_SEARCH_TOGGLE = "//label[contains(@for,'job_search_on')]"
CAPTURE_CONVERSATION = "//select[@id='id_start_interaction_type']"
CAPTURE_JOB_SEARCH = "//option[contains(@name,'job_search_on')]"
CANDIDATE_CARE_SEARCH = "//*[contains(@for,'knowledge_base')]"
KNOWLEDGE_BASE = "//div[contains(text(),'Knowledge Base')]"
YOU_CAN_FIND_YOUR_SITE = "//label[contains(text(),'You can find your site here:')]"
THE_WIDGET_ONLY_APPEAR_LABEL = "//label[contains(text(),'The widget will only appear on these domains.')]"
JOB_SEARCH_PARAMETER_LABEL_WIDGET = "//div[contains(@id,'conv_targeting')]//span[contains(text(),'Job Search Parameters')]"
ADD_ATTRIBUTE_BUTTON = "(//button[contains(@class,'btn btn-default add-attribute')])[1]"
JOB_CATEGORY_ATTRIBUTE = "//span[contains(text(),'Attribute')]/parent::div//*[contains(@aria-label,'Attribute')]"
ATTRIBUTE_VALUE = "(//*[contains(@aria-label,'Attribute Value')])[{}]"
INPUT_TARGETING_RULE = "//input[contains(@name,'conv_targ_name')]"
BUTTON_ADD_TARGETING_RULE = "//button[contains(@id,'add_conv_targ')]"
LIMIT_SEARCH_TOGGLE = "(//label[contains(@for,'search_limit_attr_uid')])[{}]"
ATTRIBUTE_DROPDOWN = "(//span[contains(text(),'Attribute')]/parent::div//input[contains(@name,'attribute')])[{}]"
ALL_JOB_FEEDS_DROPDOWN = "//input[contains(@class, 'job-feed-input')]"
SELECT_ALL_JOB_FEEDS_CHECKBOX = "//div[contains(@class, 'fade top in')]//label[contains(normalize-space(), 'Select All Job Feeds')]"
WIDGET_GEOGRAPHIC_TARGETING_TOGGLE = "//label[contains(@for, 'restrict_ip')]"
WIDGET_GEOGRAPHIC_TARGETING_SEARCH_TEXTBOX = "//*[contains(@id, 'geo_targeting')]"
WIDGET_GEOGRAPHIC_TARGETING_COUNTRY_ITEM = "//*[contains(@id, 'countries')]//*[contains(normalize-space(), '{}')]"
ADD_NEW_TARGETING_RULE_INPUT = "//*[contains(@id, 'id_conv_targ_name')]"
ADD_NEW_TARGETING_RULE_BUTTON = "//*[contains(@id, 'add_conv_targ')]"
DEFAULT_JOB_FEED_DROPDOWN = "//*[contains(@id, 'rule-edit-form')]//following-sibling::*[contains(@value, 'Default job feed')]"
CANCEL_SELECT_ALL_JOB_FEEDS_WIDGET_BUTTON = "//div[contains(@class, 'fade top in')]//button[contains(@class, 'cancel-btn')]"
WEB_MANAGEMENT_RATING_TOGGLE = "//label[contains(@for,'conversation_rating') and contains(@class,toggle-btn)]"
WEB_MANAGEMENT_RATING_SELECT = "//select[@id='id_rating']"
WEB_MANAGEMENT_RATING_OPTION = "//select[@id='id_rating']//option[normalize-space()='{}']"
WIDGET_AI_RESUME_MATCHING_TOGGLE = "//*[contains(@for, 'ai_resume_on')]"
BRANDING_DROPDOWN = "//*[@id='id_job_brand_id']"
BRANDING_DROPDOWN_VALUE = "//*[@id='id_job_brand_id']//option[contains(text(), '{}')]"
BRANDING_DROPDOWN_SELECTED_VALUE = "//*[@id='id_job_brand_id']//option[@selected and contains(text(), '{}')]"

#WEB MANAGEMENT / WIDGET / ADD NEW TARGETING RULE
WEB_MANAGEMENT_WIDGET_SELECT_JOB_FEEDS_FOR_TARGETING_RULE = "(//div[contains(@class, 'fade top in')]//input[contains(@class, 'job-feed-checkbox')]//following-sibling::span)[{}]"
WEB_MANAGEMENT_WIDGET_TARGETING_RULE_APPLY_BUTTON = "//div[contains(@class, 'popover-content')]//button[contains(@class, 'btn-apply')]"
WEB_MANAGEMENT_WIDGET_JOB_FEED_CHECKBOX = "//div[contains(@class, 'popover-content')]//span"
WEB_MANAGEMENT_WIDGET_JOB_FEED_CHECKBOX_INDEX = "(//div[contains(@class, 'popover-content')]//span)[{}]"

# MODAL ADD NEW TARGETING RULE
JOB_SEARCH_PARAMETER_ON_MODAL = "//div[contains(text(),'Determine where the conversation will display on')]/ancestor::div[contains(@class,'modal-body ')]//*[contains(text(),'Job Search Parameters')]"
JOB_SEARCH_TOGGLE_ON_MODAL = "//label[contains(@for,'conv_targeting_js_on')]"
CAPTURE_CONVERSATION_ON_MODAL = "(//select[contains(@name,'start_interaction_type')])[2]"
ADD_ATTRIBUTE_BUTTON_ON_MODAL = "(//*[contains(@class,'btn btn-default add-attribute')])[3]"
SAVE_BUTTON_ON_MODAL = "//*[contains(@class,'btn btn-primary disabled')]"
KNOWLEDGE_BASE_ON_MODAL = "//label[@for='conversation_targeting_knowledge_base']"

# WIDGET CONVERSATION
DOMAIN_SECURITY_WIDGET = "//div[@class='selectize-input items not-full']//input"
KNOWLEDGE_BASE_TOGGLE = "//label[@for='knowledge_base']"
KNOWLEDGE_BASE_TYPE = "//input[@name='kb_type_selected']//following-sibling::label[contains(text(),'{}')]"
WIDGET_JOB_SEARCH_ITEM = "//select[@id='id_start_interaction_type']//*[contains(text(), '{}')]"

# WEB MANAGEMENT / LANDING SITE
WEB_MANAGEMENT_CONVERSATION_SELECTION_DROPDOWN = "//*[contains(@id,'select2-id_conversation-container')]"
WEB_MANAGEMENT_CONVERSATION_SEARCH_INPUT = "//*[contains(@placeholder,'Search for conversation')]"
WEB_MANAGEMENT_CONVERSATION_DROPDOWN_ITEM = "//*[contains(@class, 'select2-results__options')]//div[contains(text(), '{}')]"
