# LOCATION ADDRESS
AUTOMATION_JOB_FEEDS_PROD_LOCATION = "189 Hannaford Drive,South Burlington,Vermont,5403,"
AUTOMATION_JOB_FEEDS_PROD_LOCATION_2 = "189 Hannafords Dr, South Burlington, VT 05403, USA"
LOCATION_ADDRESS_LOCATION_MAPPING = "LOCATION_MAPPING_LOCATION_NAME"
LOCATION_ADDRESS_MP020 = "118 Moore DrivePort Jeffrey, IA 3152"

# LOCATION TYPE
LOCATION_CITY_CALIFORNIA_CA = "California CA"
LOCATION_CITY_VT_UNITED_STATES = "(VT) United States"
LOCATION_CITY_FLORIDA = "Florida"
LOCATION_CITY_NORTH_CAROLINA = "North Carolina"
LOCATION_CITY_TEXAS_TX = "Texas TX"
LOCATION_CITY_NEW_YORK = "New York"
LOCATION_NAME_VINTNERS_PLACE= "Vintners Place"
LOCATION_CITY_SAN_JOSE = "San Jose"
LOCATION_CITY_HILO = "Hilo"
LOCATION_ADDRESS_HANNAFORD_DRIVE = "189 Hannaford Drive"
LOCATION_ADDRESS_HANNAFORD_DR = '189 Hannafords Dr'
AREA_NAME_SOUTH_BURLINGTON = "South Burlington"
LOCATION_NAME_US = "United States"
LOCATION_PHOENIX = "Phoenix"
LOCATION_TUCSON = "Tucson"
LOCATION_GILBERT = "Gilbert"
LOCATION_SCOTTSDALE = "Scottsdale"
LOCATION_GLENDALE = "Glendale"
LOCATION_DALLAS = "Dallas"
LOCATION_HAWAII_ISLAND = "Hawaii island"
LOCATION_AMSTERDAM = "Amsterdam"

# Location name for testing
LOCATION_NAME_1 = "Team Location"
LOCATION_NAME_2 = "Vintners Place"
LOCATION_NAME_3 = "Mahatant Place"
LOCATION_STREET_TRUNG_NU_VUONG = "Trung Nu Vuong"
LOCATION_STREET_NGUYEN_HUU_THO = "Nguyen Huu Tho"

# LOCATION STATE
LOCATION_STATE_VERMON = "Vermon"
LOCATION_STATE_NORWICH = "Norwich"
LOCATION_STATE_CALIFORNIA = "California"
LOCATION_STATE_ALASKA = "Alaska"
LOCATION_STATE_HAWAII = "Hawaii"
